Repository AppFlowy-IO/AppFlowy, pull requests merged in 2022-11, with the labels that each got.

#1394 fix request focus when InputTextField is added
  frontend/app_flowy/lib/plugins/grid/presentation/widgets/common/text_field.dart
Labels: hacktoberfest, HACKTOBERFEST-ACCEPTED

#1401 ci: Add dmg support for MacOS and add the .dmg to the release
  .github/workflows/release.yml
  frontend/scripts/dmg_assets/AppFlowyInstallerBackground.jpg
Labels: improvements, hacktoberfest, HACKTOBERFEST-ACCEPTED, infra

#1386 feat: create deb package for linux (#1303)
  .github/workflows/release.yml
Labels: infra

#1384 Close popover on text field tap
  frontend/app_flowy/lib/plugins/grid/presentation/widgets/common/text_field.dart
  frontend/app_flowy/lib/plugins/grid/presentation/widgets/header/type_option/select_option.dart
Labels: bug, grid, hacktoberfest, HACKTOBERFEST-ACCEPTED

#1435 fix: NetworkType null safety issues
  frontend/app_flowy/lib/core/network_monitor.dart
  frontend/app_flowy/pubspec.lock
  frontend/app_flowy/pubspec.yaml
  frontend/rust-lib/flowy-net/src/entities/network_state.rs
Labels: infra

#1442 fix: Application name in Windows taskbar.
  frontend/app_flowy/windows/runner/Runner.rc
Labels: bug

#1461 ci: add .exe installer support for Windows releases #1305
  .github/workflows/release.yml
  frontend/scripts/windows_installer/flowy_logo.ico
  frontend/scripts/windows_installer/inno_setup_config.iss
Labels: improvements, infra

#1510 fix: [Bug] Inconsistent font weights #1488
  frontend/app_flowy/lib/startup/tasks/app_widget.dart
  frontend/app_flowy/packages/flowy_infra/lib/theme.dart
Labels: bug
