Repository AppFlowy-IO/AppFlowy, pull requests merged in 2023-10, with the labels that each got.

#3604 fix: restore page banner ui improvement
  frontend/appflowy_flutter/lib/plugins/document/presentation/banner.dart
Labels: HACKTOBERFEST-ACCEPTED

#3591 feat: emoji picker improvement
  frontend/appflowy_flutter/integration_test/util/database_test_op.dart
  frontend/appflowy_flutter/lib/plugins/database_view/widgets/row/row_banner.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/emoji_picker_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/emoji_picker/emoji_picker.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/emoji_picker/src/config.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/emoji_picker/src/default_emoji_picker_view.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/emoji_picker/src/emoji_lists.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/emoji_picker/src/emoji_picker.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/emoji_picker/src/emoji_picker_builder.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/emoji_picker/src/emoji_view_state.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/emoji_picker/src/models/category_models.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/emoji_picker/src/models/emoji_model.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/emoji_picker/src/models/recent_emoji_model.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/document_header_node_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/emoji_popover.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/plugins.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/emoji_picker/emoji_menu_item.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/emoji_picker/emoji_picker.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/emoji_picker/src/default_emoji_picker_view.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/emoji_picker/src/emji_picker_config.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/emoji_picker/src/emoji_lists.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/emoji_picker/src/emoji_picker.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/emoji_picker/src/emoji_picker_builder.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/emoji_picker/src/emoji_view_state.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/emoji_picker/src/flowy_emoji_picker_config.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/emoji_picker/src/models/emoji_category_models.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/emoji_picker/src/models/emoji_model.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/emoji_picker/src/models/recent_emoji_model.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/emoji_picker/emoji_picker.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/emoji_picker/src/config.dart
  frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/dandelion.dart
  frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/lavender.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/scrolling/styled_scroll_bar.dart
  frontend/resources/translations/en.json
Labels: improvements

#3705 feat: improve translations ja_JP
  frontend/resources/translations/ja-JP.json
Labels: HACKTOBERFEST-ACCEPTED

#3722 fix: slash command panel bugs
  frontend/appflowy_tauri/src-tauri/Cargo.lock
  frontend/appflowy_tauri/src-tauri/Cargo.toml
  frontend/appflowy_tauri/src/appflowy_app/components/document/BlockSlash/BlockSlashMenu.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/document/BlockSlash/index.hooks.ts
  frontend/appflowy_tauri/src/appflowy_app/components/document/TextBlock/useTurnIntoBlockEvents.ts
  frontend/appflowy_tauri/src/appflowy_app/components/document/_shared/InlineBlock/PageInline.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/document/_shared/SubscribeNode.hooks.ts
  frontend/appflowy_tauri/src/appflowy_app/components/document/_shared/usePanelSearchText.ts
  frontend/appflowy_tauri/src/appflowy_app/stores/effects/workspace/page/page_controller.ts
  frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async-actions/blocks/insert.ts
  frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async-actions/blocks/update.ts
  frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async-actions/mention.ts
  frontend/appflowy_tauri/src/appflowy_app/stores/reducers/document/async-actions/turn_to.ts
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
Labels: bug, tauri, react

#3751 fix: fixed the horizontal scrollbar disappearing in grid view
  frontend/appflowy_flutter/lib/plugins/database_view/grid/presentation/grid_page.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/scrolling/styled_scrollview.dart
Labels: HACKTOBERFEST-ACCEPTED

#3766 fix: font size text being displayed out of range.
  frontend/appflowy_flutter/lib/plugins/document/presentation/more/font_size_switcher.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/more/more_button.dart
Labels: HACKTOBERFEST-ACCEPTED

#3612 Added tooltip when hovering over No-Data
  frontend/appflowy_flutter/lib/plugins/database_view/calendar/presentation/calendar_page.dart
  frontend/resources/translations/en.json
Labels: HACKTOBERFEST-ACCEPTED
