Repository AppFlowy-IO/AppFlowy, pull requests merged in 2024-09, with the labels that each got.

#6158 chore: remove unused translation
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_plan_view.dart
  frontend/resources/translations/en.json
Labels: v0.6.8

#6155 chore: update FR-fr translations
  frontend/resources/translations/fr-FR.json
  frontend/resources/translations/vi-VN.json
Labels: translation, v0.6.8

#6164 chore: bump version 0.6.8
  CHANGELOG.md
  frontend/resources/translations/en.json
Labels: v0.6.8

#5853 fix: display duplicate entry
  frontend/appflowy_web_app/src/components/as-template/AsTemplate.tsx
  frontend/appflowy_web_app/src/components/as-template/creator/CreatorAvatar.tsx
  frontend/appflowy_web_app/src/components/as-template/related-template/TemplateItem.tsx
  frontend/appflowy_web_app/src/components/database/components/calendar/event/Event.tsx
  frontend/appflowy_web_app/src/components/publish/header/PublishViewHeader.tsx
  frontend/appflowy_web_app/src/components/publish/header/duplicate/Duplicate.tsx
  frontend/appflowy_web_app/src/utils/color.ts
  frontend/resources/translations/en.json
Labels: v0.6.8

#6168 chore: downgrade macOS version in iOS CI to avoid "no space left" error
  .github/workflows/ios_ci.yaml
  frontend/scripts/makefile/mobile.toml
Labels: v0.6.9

#6170 chore(flutter): bump sentry version to fix building
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.6.9

#6167 feat: added delete account functionality
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
  frontend/rust-lib/flowy-server/src/af_cloud/impls/user/cloud_service_impl.rs
  frontend/rust-lib/flowy-user-pub/src/cloud.rs
  frontend/rust-lib/flowy-user/src/event_handler.rs
  frontend/rust-lib/flowy-user/src/event_map.rs
  frontend/rust-lib/flowy-user/src/user_manager/manager.rs
Labels: v0.6.9

#6103 feat: support account deletion
  frontend/Makefile.toml
  frontend/appflowy_flutter/integration_test/cloud/anon_user_continue_test.dart
  frontend/appflowy_flutter/integration_test/cloud/appflowy_cloud_auth_test.dart
  frontend/appflowy_flutter/integration_test/cloud/user_setting_sync_test.dart
  frontend/appflowy_flutter/integration_test/shared/auth_operation.dart
  frontend/appflowy_flutter/integration_test/shared/settings.dart
  frontend/appflowy_flutter/ios/Podfile.lock
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page_header.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_setting_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/setting/settings_popup_menu.dart
  frontend/appflowy_flutter/lib/mobile/presentation/setting/user_session_setting_group.dart
  frontend/appflowy_flutter/lib/user/application/user_service.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/sign_in_or_logout_button.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/shared_widget.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/account/account.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/account/account_deletion.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/account/account_sign_in_out.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/account/account_user_profile.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_account_view.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/_restart_app_button.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/dialogs.dart
  frontend/appflowy_flutter/pubspec.yaml
  frontend/resources/translations/en.json
Labels: v0.6.9

#6175 fix: build error in release mode
  frontend/appflowy_tauri/src-tauri/Cargo.lock
  frontend/appflowy_tauri/src-tauri/Cargo.toml
  frontend/appflowy_web_app/src-tauri/Cargo.lock
  frontend/appflowy_web_app/src-tauri/Cargo.toml
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
Labels: v0.6.9

#6177 fix: incorrect right-lick menu position on Desktop
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.6.9

#6119 feat: enable apple sign in on desktop version
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/desktop_sign_in_screen.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/third_party_sign_in_button.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/third_party_sign_in_buttons.dart
  frontend/appflowy_flutter/lib/user/presentation/widgets/auth_form_container.dart
Labels: v0.6.9

#6183 chore(mobile): dismiss the keyboard when tap outside on login
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/magic_link_sign_in_buttons.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text_field.dart
Labels: v0.6.9

#6187 feat: exclude ARMv7 architecture for Android builds
  frontend/appflowy_flutter/android/app/build.gradle
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/appflowy_mobile_toolbar_item.dart
  frontend/scripts/makefile/mobile.toml
Labels: v0.6.9

#6182 fix(flutter): various grid ui issues
  frontend/appflowy_flutter/integration_test/desktop/board/board_field_test.dart
  frontend/appflowy_flutter/integration_test/desktop/database/database_cell_test.dart
  frontend/appflowy_flutter/integration_test/desktop/database/database_field_test.dart
  frontend/appflowy_flutter/integration_test/desktop/database/database_row_page_test.dart
  frontend/appflowy_flutter/integration_test/shared/database_test_op.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_quick_field_editor.dart
  frontend/appflowy_flutter/lib/plugins/database/application/field/field_editor_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/application/row/row_detail_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/header/desktop_field_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/header/grid_header.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/checklist_cell_editor.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/mobile_checklist_cell_editor.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/relation_cell_editor.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/field/field_editor.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/row/row_property.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/setting/setting_property_list.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/test/bloc_test/board_test/create_or_edit_field_test.dart
  frontend/appflowy_flutter/test/bloc_test/board_test/util.dart
  frontend/appflowy_flutter/test/bloc_test/grid_test/field/edit_field_test.dart
  frontend/appflowy_flutter/test/bloc_test/grid_test/util.dart
  frontend/resources/translations/en.json
  frontend/scripts/code_generation/freezed/generate_freezed.sh
Labels: v0.6.9

#6194 fix(flutter_desktop): board ui bugs
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/card_cell_skeleton/date_card_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/card_cell_skeleton/text_card_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/row/row_banner.dart
Labels: v0.6.9

#5904 chore: updat the Ukrainian translation
  frontend/resources/translations/fr-FR.json
  frontend/resources/translations/uk-UA.json
Labels: translation, v0.6.9

#6148 chore: update FR-fr translations
  frontend/resources/translations/fr-FR.json
Labels: translation, v0.6.9

#6196 chore: update translation
  frontend/resources/translations/en.json
Labels: translation, v0.6.9

#6203 fix: launch review 0.6.9 issues
  frontend/appflowy_flutter/ios/Runner/Info.plist
  frontend/appflowy_flutter/lib/mobile/presentation/database/board/mobile_board_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/setting/user_session_setting_group.dart
  frontend/appflowy_flutter/lib/plugins/database/board/presentation/board_page.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/grid_page.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/mobile_grid_page.dart
  frontend/appflowy_flutter/lib/plugins/inline_actions/handlers/inline_page_reference.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/workspace_start_screen/desktop_workspace_start_screen.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/workspace_start_screen/mobile_workspace_start_screen.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/account/account_deletion.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_billing_view.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_plan_view.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_shortcuts_view.dart
  frontend/resources/translations/el-GR.json
  frontend/resources/translations/en.json
Labels: v0.6.9

#6229 fix(flutter_desktop): more checklist multiline issues
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/checklist_cell_editor.dart
  frontend/appflowy_flutter/macos/Podfile.lock
Labels: v0.6.9

#6201 Update zh-CN translations
  frontend/resources/translations/fr-FR.json
  frontend/resources/translations/zh-CN.json
Labels: translation, v0.6.9

#6206 fix: redirect to login page after deleting account on Android
  frontend/appflowy_flutter/lib/mobile/presentation/setting/user_session_setting_group.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/loading.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/account/account_deletion.dart
Labels: v0.6.9

#6224 chore: update jp-JP translations
  frontend/resources/translations/ja-JP.json
Labels: translation, v0.6.9

#6141 chore: update ru-RU translations
  frontend/resources/translations/ru-RU.json
Labels: translation, v0.6.9

#6184 Update CHANGELOG.md
  CHANGELOG.md
Labels: v0.6.8

#6240 fix: hover color in different color schemes
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/shared_widget.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space_header.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/space_more_popup.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_add_button.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/hover.dart
Labels: v0.6.9

#6244 fix: android share log file permission
  frontend/appflowy_flutter/android/app/build.gradle
  frontend/appflowy_flutter/lib/mobile/presentation/home/setting/settings_popup_menu.dart
  frontend/appflowy_flutter/lib/mobile/presentation/page_item/mobile_view_item.dart
  frontend/appflowy_flutter/lib/plugins/base/emoji/emoji_text.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/image_placeholder.dart
  frontend/appflowy_flutter/lib/shared/popup_menu/appflowy_popup_menu.dart
  frontend/appflowy_flutter/lib/util/share_log_files.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.6.9

#6245 feat: file block on mobile
  frontend/appflowy_flutter/ios/Podfile.lock
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/file/file_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/add_block_toolbar_item.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/resources/translations/en.json
Labels: v0.6.9

#6256 Chore: Update CHANGELOG.md incl v0.6.9
  CHANGELOG.md
Labels: v0.6.9

#6250 fix: more default image extensions
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/custom_cover_picker_bloc.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/upload_image_menu/widgets/upload_image_file_widget.dart
  frontend/appflowy_flutter/lib/util/default_extensions.dart
Labels: v0.7.0

#6264 fix: the last block of a doc is randomly moved to the first position of the doc
  frontend/appflowy_flutter/lib/plugins/document/application/editor_transaction_adapter.dart
  frontend/appflowy_flutter/macos/Podfile.lock
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.7.0

#6270 feat(flutter_desktop): colored column names in kanban board
  frontend/appflowy_flutter/lib/plugins/database/board/application/board_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/board/application/column_header_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/board/presentation/board_page.dart
  frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_checkbox_column_header.dart
  frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_column_header.dart
  frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_editable_column_header.dart
  frontend/appflowy_flutter/lib/plugins/database/domain/group_service.dart
  frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/default_colorscheme.dart
  frontend/resources/translations/en.json
  frontend/rust-lib/event-integration-test/src/database_event.rs
  frontend/rust-lib/event-integration-test/tests/database/local_test/group_test.rs
  frontend/rust-lib/flowy-database2/src/entities/group_entities/group.rs
  frontend/rust-lib/flowy-database2/src/entities/group_entities/group_changeset.rs
  frontend/rust-lib/flowy-database2/src/event_handler.rs
  frontend/rust-lib/flowy-database2/src/event_map.rs
  frontend/rust-lib/flowy-database2/src/notification.rs
  frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
  frontend/rust-lib/flowy-database2/src/services/database_view/notifier.rs
  frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs
  frontend/rust-lib/flowy-database2/src/services/group/action.rs
  frontend/rust-lib/flowy-database2/src/services/group/controller.rs
  frontend/rust-lib/flowy-database2/src/services/group/controller_impls/default_controller.rs
  frontend/rust-lib/flowy-database2/src/services/group/entities.rs
Labels: v0.7.0

#6307 chore: show full name of groups on hover
  frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_checkbox_column_header.dart
  frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_column_header.dart
  frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_editable_column_header.dart
Labels: v0.7.0

#6306 fix: reordering or creating a row while sorts are active
  frontend/appflowy_flutter/integration_test/desktop/board/board_row_test.dart
  frontend/appflowy_flutter/lib/plugins/database/application/field/field_info.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/grid_page.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/row/action.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/row/row.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/shared_widget.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/dialogs.dart
  frontend/resources/translations/en.json
Labels: v0.7.0

#6309 fix: view title doesn't update after renaming from 'more' button
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/cover/document_immersive_cover.dart
Labels: bug, v0.7.0

#6291 chore: downgrade appimage builder
  frontend/scripts/linux_distribution/appimage/AppImageBuilder.yml
Labels: v0.7.0

#6285 feat: support dragging the block to reorder
  frontend/appflowy_flutter/lib/plugins/document/document_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_list.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_option_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/draggable_option_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/resizeable_image.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/favorites/favorite_menu_bloc.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/widget/flowy_tooltip.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/resources/translations/en.json
Labels: v0.7.0

#6328 fix: make icon of primary cells align to top
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/card_cell_skeleton/text_card_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_grid/desktop_grid_text_cell.dart
Labels: v0.7.0

#6321 fix: inputting backtick will crash when using French IME
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/backtick_character_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/plugins.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.7.0

#6329 fix(flutter_desktop): incorrect row meta in row detail page
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/grid_page.dart
Labels: v0.7.0

#6327 feat: support adjusting document width
  frontend/appflowy_flutter/ios/Podfile.lock
  frontend/appflowy_flutter/lib/core/config/kv_keys.dart
  frontend/appflowy_flutter/lib/plugins/database_document/database_document_page.dart
  frontend/appflowy_flutter/lib/plugins/document/application/document_appearance_cubit.dart
  frontend/appflowy_flutter/lib/plugins/document/document_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/document_header_node_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_workspace_view.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/shared/setting_list_tile.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/resources/translations/en.json
Labels: v0.7.0

#6338 feat: support moveTo feature in more action menu
  frontend/appflowy_flutter/integration_test/shared/common_operations.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page.dart
  frontend/appflowy_flutter/lib/workspace/application/sidebar/space/space_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/move_to/move_page_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/sidebar_workspace.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_more_action_button.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/more_view_actions/more_view_actions.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/more_view_actions/widgets/common_view_action.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/more_view_actions/widgets/font_size_action.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/more_view_actions/widgets/view_meta_info.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.7.0

#6342 feat: support settings on sign in page
  frontend/appflowy_flutter/ios/Podfile.lock
  frontend/appflowy_flutter/lib/shared/settings/show_settings.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/desktop_sign_in_screen.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/mobile_sign_in_screen.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/sign_in_anonymous_button.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/third_party_sign_in_buttons.dart
  frontend/appflowy_flutter/lib/util/share_log_files.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_manage_data_view.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/settings_dialog.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/setting_cloud.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_menu.dart
  frontend/appflowy_flutter/macos/Podfile.lock
Labels: v0.7.0

#6345 fix: icon doesn't align to the editor if the editor is not initialized
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/document_header_node_widget.dart
Labels: v0.7.0

#6354 fix: settings page minor issues
  frontend/appflowy_flutter/lib/workspace/presentation/settings/settings_dialog.dart
  frontend/appflowy_flutter/macos/Podfile.lock
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/primary_rounded_button.dart
  frontend/resources/translations/en.json
Labels: v0.7.0

#6357 Update translations zh-TW
  frontend/resources/translations/ja-JP.json
  frontend/resources/translations/zh-TW.json
Labels: translation, v0.7.1

#6367 fix: launch review issues 0.7.0
  frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_checkbox_column_header.dart
  frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_column_header.dart
  frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_editable_column_header.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/card/card.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/card/container/card_container.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/select_option_cell_editor.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/field/type_option_editor/media.dart
Labels: v0.7.0

#6365 fix: 0.7.0 launch review issues
  frontend/appflowy_flutter/integration_test/cloud/cloud_runner.dart
  frontend/appflowy_flutter/integration_test/cloud/document/document_drag_block_test.dart
  frontend/appflowy_flutter/integration_test/cloud/sidebar/sidebar_move_page_test.dart
  frontend/appflowy_flutter/integration_test/cloud/workspace/collaborative_workspace_test.dart
  frontend/appflowy_flutter/integration_test/cloud/workspace/workspace_settings_test.dart
  frontend/appflowy_flutter/integration_test/desktop/reminder/document_reminder_test.dart
  frontend/appflowy_flutter/integration_test/shared/common_operations.dart
  frontend/appflowy_flutter/integration_test/shared/constants.dart
  frontend/appflowy_flutter/integration_test/shared/document_test_operations.dart
  frontend/appflowy_flutter/integration_test/shared/util.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/draggable_option_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/util.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/visual_drag_area.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/move_to/move_page_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/shared_widget.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_more_action_button.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_workspace_view.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/settings_dialog.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/resources/translations/en.json
Labels: v0.7.0

#6377 fix: sidebar move page test
  frontend/appflowy_flutter/integration_test/cloud/cloud_runner.dart
  frontend/appflowy_flutter/integration_test/cloud/sidebar/sidebar_move_page_test.dart
  frontend/appflowy_flutter/integration_test/cloud/workspace/workspace_settings_test.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/move_to/move_page_menu.dart
  frontend/appflowy_flutter/pubspec.lock
Labels: v0.7.0

#6380 feat: add numpadSubtract as zoom out keycode
  frontend/appflowy_flutter/integration_test/desktop/uncategorized/zoom_in_out_test.dart
  frontend/appflowy_flutter/integration_test/desktop_runner_3.dart
  frontend/appflowy_flutter/integration_test/shared/common_operations.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/hotkeys.dart
Labels: v0.7.0

#6386 feat: support appflowy cloud in sign-in settings page
  frontend/appflowy_flutter/integration_test/desktop/settings/settings_runner.dart
  frontend/appflowy_flutter/integration_test/desktop/settings/sign_in_page_settings_test.dart
  frontend/appflowy_flutter/lib/flutter/af_dropdown_menu.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/desktop_sign_in_screen.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/settings_dialog.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/shared/settings_dropdown.dart
Labels: v0.7.0

#6369 fix(flutter_desktop): select option kanban groups not updating
  frontend/appflowy_flutter/integration_test/desktop/board/board_group_test.dart
  frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs
Labels: v0.7.0

#6376 fix: semi-transparent colors being forced to full opacity in FlowySvg
  frontend/appflowy_flutter/packages/flowy_svg/lib/src/flowy_svg.dart
Labels: v0.7.0

#6381 fix: row cover improvements
  frontend/appflowy_flutter/integration_test/desktop/database/database_row_cover_test.dart
  frontend/appflowy_flutter/integration_test/desktop/database/database_row_page_test.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_cover_image_test.dart
  frontend/appflowy_flutter/integration_test/shared/database_test_op.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/board/mobile_board_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/mobile_card_detail_screen.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/card/mobile_card_content.dart
  frontend/appflowy_flutter/lib/plugins/database/application/row/related_row_detail_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/application/row/row_banner_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/calendar/presentation/calendar_event_card.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/application/row/row_detail_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/card/card.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_row_detail/desktop_row_detail_media_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/row/row_banner.dart
  frontend/appflowy_flutter/lib/plugins/database_document/database_document_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/desktop_cover.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/document_header_node_widget.dart
  frontend/appflowy_flutter/lib/plugins/shared/cover_type_ext.dart
  frontend/appflowy_flutter/lib/shared/af_image.dart
  frontend/appflowy_tauri/src-tauri/Cargo.toml
  frontend/appflowy_web_app/src-tauri/Cargo.toml
  frontend/resources/translations/en.json
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
  frontend/rust-lib/flowy-database2/src/entities/row_entities.rs
  frontend/rust-lib/flowy-database2/src/entities/type_option_entities/media_entities.rs
  frontend/rust-lib/flowy-database2/src/event_handler.rs
  frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/media_type_option/media_type_option.rs
  frontend/rust-lib/flowy-database2/tests/database/mock_data/grid_mock_data.rs
Labels: v0.7.0

#6388 fix: potential ai_repository not init
  frontend/appflowy_flutter/integration_test/cloud/appflowy_cloud_auth_test.dart
  frontend/appflowy_flutter/integration_test/cloud/document/document_delete_block_test.dart
  frontend/appflowy_flutter/integration_test/cloud/document/document_drag_block_test.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_copy_and_paste_test.dart
  frontend/appflowy_flutter/lib/plugins/document/application/document_bloc.dart
  frontend/appflowy_flutter/lib/plugins/document/application/editor_transaction_adapter.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_option_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/paste_from_image.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/smart_edit_bloc.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/smart_edit_node_widget.dart
  frontend/appflowy_flutter/test/bloc_test/smart_edit_test/smart_editor_bloc_test.dart
Labels: v0.7.0

#6387 fix: edge case for text filters
  frontend/rust-lib/flowy-database2/src/services/field/type_options/text_type_option/text_filter.rs
Labels: v0.7.1

#6288 feat: date filter
  frontend/appflowy_flutter/integration_test/desktop/database/database_filter_test.dart
  frontend/appflowy_flutter/integration_test/shared/database_test_op.dart
  frontend/appflowy_flutter/lib/plugins/database/application/field/field_info.dart
  frontend/appflowy_flutter/lib/plugins/database/domain/filter_service.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/application/filter/date_filter_editor_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/application/filter/filter_create_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/date.dart
  frontend/appflowy_flutter/lib/util/int64_extension.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text_field.dart
Labels: v0.7.1

#6397 chore: install deps using pacman
  .github/workflows/docker_ci.yml
  .github/workflows/release.yml
  frontend/scripts/docker-buildfiles/Dockerfile
Labels: v0.7.1

#6399 feat: allow filtering by date end
  frontend/appflowy_flutter/integration_test/desktop/database/database_filter_test.dart
  frontend/appflowy_flutter/integration_test/shared/database_test_op.dart
  frontend/appflowy_flutter/lib/plugins/database/application/field/filter_entities.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/application/filter/filter_editor_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/date.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/appflowy_date_picker.dart
  frontend/resources/translations/en.json
  frontend/rust-lib/flowy-database2/src/entities/filter_entities/date_filter.rs
  frontend/rust-lib/flowy-database2/src/services/cell/cell_operation.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/date_type_option/date_filter.rs
  frontend/rust-lib/flowy-database2/src/services/group/controller_impls/date_controller.rs
  frontend/rust-lib/flowy-database2/src/services/group/controller_impls/select_option_controller/util.rs
  frontend/rust-lib/flowy-database2/tests/database/filter_test/advanced_filter_test.rs
  frontend/rust-lib/flowy-database2/tests/database/filter_test/date_filter_test.rs
  frontend/rust-lib/flowy-database2/tests/database/group_test/script.rs
  frontend/rust-lib/flowy-database2/tests/database/pre_fill_cell_test/pre_fill_row_according_to_filter_test.rs
Labels: v0.7.1

#6401 feat(mobile): add database filters
  frontend/appflowy_flutter/lib/mobile/presentation/database/board/mobile_board_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/board/widgets/group_card_header.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_filter_bottom_sheet.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_filter_bottom_sheet_cubit.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_filter_condition_list.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_sort_bottom_sheet.dart
  frontend/appflowy_flutter/lib/plugins/database/application/field/filter_entities.dart
  frontend/appflowy_flutter/lib/plugins/database/board/presentation/board_page.dart
  frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_column_header.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/application/filter/filter_editor_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/checklist.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/date.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/number.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/select_option/select_option.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/text.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/url.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/header/field_type_extension.dart
  frontend/appflowy_flutter/lib/plugins/database/tab_bar/mobile/mobile_tab_bar_header.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/extension.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/mobile_select_option_editor.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/setting/mobile_database_controls.dart
  frontend/appflowy_flutter/lib/util/field_type_extension.dart
  frontend/appflowy_web_app/src/components/database/__tests__/DatabaseWithFilter.cy.tsx
  frontend/resources/translations/en.json
Labels: v0.7.1

#6353 feat: support cover title
  frontend/appflowy_flutter/integration_test/desktop/database/database_row_cover_test.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_codeblock_paste_test.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_copy_and_paste_test.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_create_and_delete_test.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_title_test.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_cover_image_test.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_image_block_test.dart
  frontend/appflowy_flutter/integration_test/desktop/settings/shortcuts_settings_test.dart
  frontend/appflowy_flutter/integration_test/desktop/sidebar/sidebar_test.dart
  frontend/appflowy_flutter/integration_test/desktop/uncategorized/zoom_in_out_test.dart
  frontend/appflowy_flutter/integration_test/desktop_runner_3.dart
  frontend/appflowy_flutter/integration_test/shared/common_operations.dart
  frontend/appflowy_flutter/integration_test/shared/document_test_operations.dart
  frontend/appflowy_flutter/integration_test/shared/expectation.dart
  frontend/appflowy_flutter/lib/plugins/document/application/document_bloc.dart
  frontend/appflowy_flutter/lib/plugins/document/document_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/cover_title_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/cover_editor_bloc.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/cover_title.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/document_cover_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/plugins.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/shared_context/shared_context.dart
  frontend/appflowy_flutter/lib/workspace/application/sidebar/space/space_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/folder/_section_folder.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/shared/rename_view_dialog.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/shared/sidebar_new_page_button.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space_header.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.7.1

#6406 fix: grid cell date time test
  frontend/appflowy_flutter/integration_test/desktop/database/database_cell_test.dart
Labels: v0.7.1

#6410 feat: support window tiling on macOS
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/view_title_bar.dart
  frontend/appflowy_flutter/macos/Runner/MainFlutterWindow.swift
Labels: v0.7.1

#6412 fix: paste doesn't work sometimes in the first try
  frontend/appflowy_flutter/integration_test/desktop/document/document_copy_and_paste_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_paste_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/paste_from_in_app_json.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/custom_image_block_component/custom_image_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/custom_image_block_component/image_menu.dart
  frontend/appflowy_flutter/lib/util/default_extensions.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/dialogs.dart
Labels: v0.7.1

#6424 fix(flutter_desktop): board card rebuild issue
  frontend/appflowy_flutter/lib/plugins/database/widgets/card/card.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/card/card_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/card/container/card_container.dart
  frontend/appflowy_flutter/pubspec.lock
Labels: v0.7.1

#6430 fix(flutter_desktop): field info not updating in sort info
  frontend/appflowy_flutter/integration_test/desktop/database/database_sort_test.dart
  frontend/appflowy_flutter/integration_test/shared/database_test_op.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_sort_bottom_sheet.dart
  frontend/appflowy_flutter/lib/plugins/database/application/defines.dart
  frontend/appflowy_flutter/lib/plugins/database/application/field/field_controller.dart
  frontend/appflowy_flutter/lib/plugins/database/application/field/sort_entities.dart
  frontend/appflowy_flutter/lib/plugins/database/domain/sort_service.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/application/grid_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/application/sort/sort_editor_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/sort/order_panel.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/sort/sort_editor.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/sort/sort_info.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/sort/sort_menu.dart
Labels: v0.7.1

#6428 chore: grid ui improvements
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/grid_page.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/layout/layout.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/layout/sizes.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/create_filter_list.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/footer/grid_footer.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/header/desktop_field_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/header/grid_header.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/header/mobile_grid_header.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/row/action.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/row/row.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/sort/create_sort_list.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/sort/order_panel.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/sort/sort_editor.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/toolbar/filter_button.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/toolbar/grid_setting_bar.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/toolbar/sort_button.dart
  frontend/appflowy_flutter/lib/plugins/database/tab_bar/desktop/tab_bar_add_button.dart
  frontend/appflowy_flutter/lib/plugins/database/tab_bar/desktop/tab_bar_header.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_grid/desktop_grid_date_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_grid/desktop_grid_timestamp_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/extension.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/relation_cell_editor.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/select_option_cell_editor.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/field/field_editor.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/field/field_type_list.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/field/type_option_editor/date/date_time_format.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/field/type_option_editor/media.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/field/type_option_editor/number.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/field/type_option_editor/relation.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/field/type_option_editor/select/select_option.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/field/type_option_editor/select/select_option_editor.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/field/type_option_editor/translate.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/group/database_group.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/row/cells/cell_container.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/row/row_property.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/setting/database_layout_selector.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/setting/database_setting_action.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/setting/setting_button.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/setting/setting_property_list.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/widgets/clear_date_button.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/widgets/date_type_option_button.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/widgets/end_time_button.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/button.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/icon_button.dart
  frontend/resources/flowy_icons/16x/add_less_padding.svg
  frontend/resources/flowy_icons/16x/ai_indicator.svg
Labels: v0.7.1

#6429 feat: support copy/cut command when the selection is collapsed
  frontend/appflowy_flutter/integration_test/desktop/document/document_shortcuts_test.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_test_runner.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_copy_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_cut_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/plugins.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/shortcuts/character_shortcuts.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/shortcuts/command_shortcuts.dart
  frontend/appflowy_flutter/lib/workspace/application/settings/shortcuts/settings_shortcuts_cubit.dart
  frontend/appflowy_flutter/lib/workspace/application/settings/shortcuts/settings_shortcuts_service.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/appflowy_flutter/test/bloc_test/shortcuts_test/shortcuts_cubit_test.dart
Labels: v0.7.1

#6415 feat: custom database field icons
  frontend/appflowy_flutter/integration_test/desktop/database/database_field_test.dart
  frontend/appflowy_flutter/integration_test/shared/database_test_op.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/widgets/mobile_row_property_list.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/widgets/option_text_field.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_create_field_screen.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_field_picker_list.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_full_field_editor.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_quick_field_editor.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_field_list.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_filter_bottom_sheet.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_sort_bottom_sheet.dart
  frontend/appflowy_flutter/lib/plugins/database/application/field/field_editor_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/application/field/field_info.dart
  frontend/appflowy_flutter/lib/plugins/database/calendar/presentation/calendar_event_editor.dart
  frontend/appflowy_flutter/lib/plugins/database/domain/field_service.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/choicechip.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/create_filter_list.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/header/desktop_field_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/header/mobile_field_button.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/sort/create_sort_list.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/field/field_editor.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/group/database_group.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/setting/setting_property_list.dart
  frontend/appflowy_flutter/lib/util/field_type_extension.dart
  frontend/appflowy_tauri/src-tauri/Cargo.lock
  frontend/appflowy_tauri/src-tauri/Cargo.toml
  frontend/appflowy_web_app/src-tauri/Cargo.lock
  frontend/appflowy_web_app/src-tauri/Cargo.toml
  frontend/resources/flowy_icons/16x/ai_summary.svg
  frontend/resources/flowy_icons/16x/ai_translate.svg
  frontend/resources/flowy_icons/16x/checkbox.svg
  frontend/resources/flowy_icons/16x/checklist.svg
  frontend/resources/flowy_icons/16x/created_time.svg
  frontend/resources/flowy_icons/16x/date.svg
  frontend/resources/flowy_icons/16x/last_edited_time.svg
  frontend/resources/flowy_icons/16x/multiselect.svg
  frontend/resources/flowy_icons/16x/number.svg
  frontend/resources/flowy_icons/16x/relation.svg
  frontend/resources/flowy_icons/16x/single_select.svg
  frontend/resources/flowy_icons/16x/text.svg
  frontend/resources/flowy_icons/16x/time.svg
  frontend/resources/flowy_icons/16x/url.svg
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
  frontend/rust-lib/flowy-database2/src/entities/field_entities.rs
  frontend/rust-lib/flowy-database2/src/event_handler.rs
  frontend/rust-lib/flowy-database2/src/manager.rs
  frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
  frontend/rust-lib/flowy-database2/tests/database/field_test/script.rs
  frontend/rust-lib/flowy-database2/tests/database/field_test/test.rs
  frontend/scripts/tool/update_collab_source.sh
Labels: v0.7.1
