Repository AppFlowy-IO/AppFlowy, pull requests merged in 2024-03, with the labels that each got.

#4783 feat: support image block
  frontend/appflowy_tauri/package.json
  frontend/appflowy_tauri/pnpm-lock.yaml
  frontend/appflowy_tauri/src/appflowy_app/application/document/document.types.ts
  frontend/appflowy_tauri/src/appflowy_app/assets/image.svg
  frontend/appflowy_tauri/src/appflowy_app/components/_shared/image_upload/Colors.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/_shared/image_upload/EmbedLink.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/_shared/image_upload/Unsplash.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/_shared/image_upload/UploadImage.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/_shared/image_upload/index.ts
  frontend/appflowy_tauri/src/appflowy_app/components/_shared/popover/Popover.hooks.ts
  frontend/appflowy_tauri/src/appflowy_app/components/editor/command/index.ts
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/blocks/image/ImageActions.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/blocks/image/ImageBlock.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/blocks/image/ImageEmpty.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/blocks/image/ImageRender.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/blocks/image/ImageResizer.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/blocks/image/UploadPopover.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/blocks/image/index.ts
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/blocks/math_equation/MathEquation.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/editor/Editor.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/editor/Element.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/inline_nodes/link/LinkEditContent.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/inline_nodes/link/LinkEditInput.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/tools/block_actions/BlockOperationMenu.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/tools/command_panel/slash_command_panel/SlashCommandPanel.hooks.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/tools/selection_toolbar/SelectionActions.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/tools/selection_toolbar/SelectionToolbar.hooks.ts
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/tools/selection_toolbar/SelectionToolbar.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/tools/selection_toolbar/actions/align/Align.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/tools/selection_toolbar/actions/bold/Bold.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/tools/selection_toolbar/actions/href/Href.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/tools/selection_toolbar/actions/inline_code/InlineCode.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/tools/selection_toolbar/actions/italic/Italic.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/tools/selection_toolbar/actions/strikethrough/StrikeThrough.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/tools/selection_toolbar/actions/underline/Underline.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/editor.scss
  frontend/appflowy_tauri/src/appflowy_app/components/editor/plugins/shortcuts/hotkey.ts
  frontend/appflowy_tauri/src/appflowy_app/components/editor/plugins/shortcuts/index.ts
  frontend/appflowy_tauri/src/appflowy_app/components/editor/plugins/shortcuts/shortcuts.hooks.ts
  frontend/appflowy_tauri/src/appflowy_app/components/editor/stores/block.ts
  frontend/appflowy_tauri/src/appflowy_app/components/editor/stores/index.ts
  frontend/appflowy_tauri/src/appflowy_app/components/editor/stores/selected.ts
  frontend/appflowy_tauri/src/appflowy_app/components/layout/Layout.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/layout/collapse_menu_button/CollapseMenuButton.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/layout/nested_page/MoreButton.tsx
  frontend/appflowy_tauri/src/appflowy_app/utils/get_modifier.ts
  frontend/appflowy_tauri/src/appflowy_app/utils/hotkeys.ts
  frontend/appflowy_tauri/src/appflowy_app/utils/open_url.ts
  frontend/resources/translations/en.json
Labels: editor, tauri, react

#4820 feat: support uploading local image
  frontend/appflowy_tauri/src-tauri/Cargo.lock
  frontend/appflowy_tauri/src-tauri/Cargo.toml
  frontend/appflowy_tauri/src-tauri/tauri.conf.json
  frontend/appflowy_tauri/src/appflowy_app/application/document/document.types.ts
  frontend/appflowy_tauri/src/appflowy_app/components/_shared/image_upload/LocalImage.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/_shared/image_upload/UploadImage.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/_shared/image_upload/UploadTabs.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/_shared/image_upload/index.ts
  frontend/appflowy_tauri/src/appflowy_app/components/_shared/view_title/cover/CoverPopover.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/_shared/view_title/cover/ViewCover.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/blocks/image/ImageEmpty.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/blocks/image/ImageRender.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/blocks/image/ImageResizer.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/blocks/image/UploadPopover.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/blocks/math_equation/MathEquation.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/editor.scss
  frontend/appflowy_tauri/src/appflowy_app/utils/mui.ts
  frontend/appflowy_tauri/src/appflowy_app/utils/upload_image.ts
  frontend/resources/translations/en.json
Labels: tauri, react

#4841 fix: support upload and render image(.git, .webp, .svg)
  frontend/appflowy_tauri/src/appflowy_app/components/_shared/image_upload/EmbedLink.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/_shared/image_upload/LocalImage.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/_shared/keyboard_navigation/KeyboardNavigation.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/database/components/field_types/checklist/AddNewOption.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/database/components/field_types/checklist/ChecklistCellActions.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/database/components/field_types/checklist/ChecklistItem.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/database/components/field_types/select/SelectOptionModifyMenu.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/database/components/field_types/select/select_cell_actions/SelectCellActions.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/database/components/field_types/text/EditTextCellInput.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/database/database.scss
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/blocks/image/ImageRender.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/blocks/image/ImageResizer.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/inline_nodes/link/LinkEditContent.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/editor.scss
  frontend/appflowy_tauri/src/appflowy_app/utils/upload_image.ts
  frontend/resources/translations/en.json
Labels: tauri, react

#4855 fix: launch review 0.5.1
  frontend/appflowy_flutter/lib/plugins/database/calendar/presentation/calendar_event_editor.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/application/calculations/field_type_calc_ext.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/grid_page.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/calculations/calculate_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/calculations/calculations_row.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/more_view_actions/more_view_actions.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/more_view_actions/widgets/view_meta_info.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/scrolling/styled_scroll_bar.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/scrolling/styled_scrollview.dart
  frontend/resources/translations/en.json
  frontend/rust-lib/flowy-database2/src/entities/calculation/calculation_entities.rs
  frontend/rust-lib/flowy-database2/src/services/calculations/service.rs
Labels: bug, v0.5.1

#4890 chore: 052
  CHANGELOG.md
  frontend/Makefile.toml
  frontend/appflowy_flutter/pubspec.yaml
Labels: bug, v0.5.2

#4828 fix: number and select filter logic
  frontend/.vscode/tasks.json
  frontend/appflowy_flutter/integration_test/desktop/database/database_filter_test.dart
  frontend/appflowy_flutter/lib/plugins/database/domain/filter_service.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/application/filter/filter_create_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/application/filter/select_option_filter_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/application/filter/select_option_filter_list_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/select_option/condition_list.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/select_option/option_list.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/select_option/select_option.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/select_option/select_option_loader.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/text.dart
  frontend/appflowy_flutter/test/bloc_test/grid_test/filter/filter_menu_test.dart
  frontend/appflowy_flutter/test/bloc_test/grid_test/filter/filter_rows_by_text_test.dart
  frontend/appflowy_tauri/src/appflowy_app/application/database/filter/filter_data.ts
  frontend/appflowy_tauri/src/appflowy_app/application/database/filter/filter_types.ts
  frontend/appflowy_tauri/src/appflowy_app/components/database/components/filter/FilterConditionSelect.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/database/components/filter/select_filter/SelectFilter.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/database/components/filter/select_filter/SelectFilterValue.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/database/components/filter/text_filter/TextFilterValue.tsx
  frontend/resources/translations/am-ET.json
  frontend/resources/translations/ar-SA.json
  frontend/resources/translations/ca-ES.json
  frontend/resources/translations/ckb-KU.json
  frontend/resources/translations/de-DE.json
  frontend/resources/translations/en.json
  frontend/resources/translations/es-VE.json
  frontend/resources/translations/eu-ES.json
  frontend/resources/translations/fa.json
  frontend/resources/translations/fr-CA.json
  frontend/resources/translations/fr-FR.json
  frontend/resources/translations/hin.json
  frontend/resources/translations/hu-HU.json
  frontend/resources/translations/id-ID.json
  frontend/resources/translations/it-IT.json
  frontend/resources/translations/ja-JP.json
  frontend/resources/translations/ko-KR.json
  frontend/resources/translations/pl-PL.json
  frontend/resources/translations/pt-BR.json
  frontend/resources/translations/pt-PT.json
  frontend/resources/translations/ru-RU.json
  frontend/resources/translations/sv-SE.json
  frontend/resources/translations/th-TH.json
  frontend/resources/translations/tr-TR.json
  frontend/resources/translations/uk-UA.json
  frontend/resources/translations/ur.json
  frontend/resources/translations/vi-VN.json
  frontend/resources/translations/zh-CN.json
  frontend/resources/translations/zh-TW.json
  frontend/rust-lib/flowy-database2/src/entities/filter_entities/select_option_filter.rs
  frontend/rust-lib/flowy-database2/src/entities/filter_entities/text_filter.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/number_type_option/number_filter.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/selection_type_option/multi_select_type_option.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/selection_type_option/select_filter.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/selection_type_option/single_select_type_option.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/text_type_option/text_filter.rs
  frontend/rust-lib/flowy-database2/tests/database/filter_test/select_option_filter_test.rs
  frontend/rust-lib/flowy-database2/tests/database/filter_test/text_filter_test.rs
Labels: v0.5.3

#4900 chore: bump client api and collab
  frontend/appflowy_tauri/src-tauri/Cargo.lock
  frontend/appflowy_tauri/src-tauri/Cargo.toml
  frontend/appflowy_web/wasm-libs/Cargo.lock
  frontend/appflowy_web/wasm-libs/Cargo.toml
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
Labels: v0.5.2

#4903 fix: mobile keyboard issues
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.5.3

#4898 feat: support changing the workspace icon
  frontend/appflowy_flutter/integration_test/cloud/cloud_runner.dart
  frontend/appflowy_flutter/integration_test/cloud/workspace/change_name_and_icon_test.dart
  frontend/appflowy_flutter/integration_test/cloud/workspace/collaborative_workspace_test.dart
  frontend/appflowy_flutter/integration_test/shared/workspace.dart
  frontend/appflowy_flutter/lib/workspace/application/user/user_workspace_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar_workspace.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_icon.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_menu.dart
  frontend/resources/translations/en.json
  frontend/rust-lib/event-integration/src/user_event.rs
  frontend/rust-lib/event-integration/tests/user/af_cloud_test/workspace_test.rs
  frontend/rust-lib/flowy-user/src/user_manager/manager_user_workspace.rs
Labels: new feature, v0.5.3

#4899 feat: support-OAuth-login
  .github/workflows/tauri_ci.yaml
  .github/workflows/tauri_release.yml
  frontend/appflowy_tauri/.gitignore
  frontend/appflowy_tauri/src-tauri/.gitignore
  frontend/appflowy_tauri/src-tauri/Cargo.lock
  frontend/appflowy_tauri/src-tauri/Cargo.toml
  frontend/appflowy_tauri/src-tauri/Info.plist
  frontend/appflowy_tauri/src-tauri/env.development
  frontend/appflowy_tauri/src-tauri/env.production
  frontend/appflowy_tauri/src-tauri/src/init.rs
  frontend/appflowy_tauri/src-tauri/src/main.rs
  frontend/appflowy_tauri/src-tauri/tauri.conf.json
  frontend/appflowy_tauri/src/appflowy_app/AppMain.hooks.ts
  frontend/appflowy_tauri/src/appflowy_app/AppMain.tsx
  frontend/appflowy_tauri/src/appflowy_app/application/folder/workspace.service.ts
  frontend/appflowy_tauri/src/appflowy_app/application/user/auth.service.ts
  frontend/appflowy_tauri/src/appflowy_app/components/_shared/devtool/AppFlowyDevTool.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/_shared/devtool/ManualSignInDialog.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/_shared/login/LoginButtonGroup.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/_shared/login/index.ts
  frontend/appflowy_tauri/src/appflowy_app/components/auth/LoginButtonGroup.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/auth/ProtectedRoutes.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/auth/Welcome.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/auth/auth.hooks.ts
  frontend/appflowy_tauri/src/appflowy_app/components/layout/workspace_manager/Workspace.hooks.ts
  frontend/appflowy_tauri/src/appflowy_app/components/layout/workspace_manager/Workspace.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/layout/workspace_manager/WorkspaceManager.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/settings/Login.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/settings/SettingsDialog.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/settings/my_account/AccountLogin.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/settings/workplace/WorkplaceDisplay.tsx
  frontend/appflowy_tauri/src/appflowy_app/stores/reducers/current-user/slice.ts
  frontend/appflowy_tauri/src/appflowy_app/stores/reducers/workspace/slice.ts
  frontend/appflowy_tauri/src/appflowy_app/utils/color.ts
  frontend/rust-lib/flowy-user/src/user_manager/manager.rs
Labels: tauri, react, v0.5.3

#4865 update German translations
  frontend/resources/translations/de-DE.json
Labels: translation, v0.5.3

#4922 feat: support el_GR language
  frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart
  frontend/appflowy_flutter/packages/flowy_infra/lib/language.dart
  project.inlang.json
Labels: translation, v0.5.3

#4880 refactor: group controller traits
  frontend/appflowy_flutter/lib/mobile/presentation/database/board/widgets/mobile_hidden_groups_column.dart
  frontend/appflowy_flutter/lib/plugins/database/board/application/board_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/board/application/group_controller.dart
  frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_hidden_groups.dart
  frontend/appflowy_flutter/test/bloc_test/board_test/group_by_multi_select_field_test.dart
  frontend/appflowy_tauri/src/appflowy_app/application/database/group/group_types.ts
  frontend/rust-lib/event-integration/tests/database/local_test/group_test.rs
  frontend/rust-lib/flowy-database2/src/entities/group_entities/group.rs
  frontend/rust-lib/flowy-database2/src/entities/group_entities/group_changeset.rs
  frontend/rust-lib/flowy-database2/src/event_handler.rs
  frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
  frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs
  frontend/rust-lib/flowy-database2/src/services/database_view/view_group.rs
  frontend/rust-lib/flowy-database2/src/services/database_view/views.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/type_option.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/type_option_cell.rs
  frontend/rust-lib/flowy-database2/src/services/group/action.rs
  frontend/rust-lib/flowy-database2/src/services/group/configuration.rs
  frontend/rust-lib/flowy-database2/src/services/group/controller.rs
  frontend/rust-lib/flowy-database2/src/services/group/controller_impls/checkbox_controller.rs
  frontend/rust-lib/flowy-database2/src/services/group/controller_impls/date_controller.rs
  frontend/rust-lib/flowy-database2/src/services/group/controller_impls/default_controller.rs
  frontend/rust-lib/flowy-database2/src/services/group/controller_impls/select_option_controller/multi_select_controller.rs
  frontend/rust-lib/flowy-database2/src/services/group/controller_impls/select_option_controller/single_select_controller.rs
  frontend/rust-lib/flowy-database2/src/services/group/controller_impls/select_option_controller/util.rs
  frontend/rust-lib/flowy-database2/src/services/group/controller_impls/url_controller.rs
  frontend/rust-lib/flowy-database2/src/services/group/entities.rs
  frontend/rust-lib/flowy-database2/src/services/group/group_builder.rs
  frontend/rust-lib/flowy-database2/src/services/group/mod.rs
  frontend/rust-lib/flowy-database2/tests/database/group_test/date_group_test.rs
  frontend/rust-lib/flowy-database2/tests/database/group_test/script.rs
  frontend/rust-lib/flowy-database2/tests/database/group_test/test.rs
Labels: v0.5.3

#4927 fix: legacy bugs on mobile
  frontend/appflowy_flutter/lib/mobile/presentation/base/app_bar_actions.dart
  frontend/appflowy_flutter/lib/mobile/presentation/base/mobile_view_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_buttons.dart
  frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_header.dart
  frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/show_mobile_bottom_sheet.dart
  frontend/appflowy_flutter/lib/mobile/presentation/setting/widgets/mobile_setting_item_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/document_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_notification.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_floating_toolbar/custom_mobile_floating_toolbar.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/_color_list.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/plugins.dart
  frontend/resources/flowy_icons/16x/m_bottom_sheet_close.svg
  frontend/resources/flowy_icons/24x/m_bottom_sheet_close.svg
  frontend/resources/translations/en.json
Labels: v0.5.3

#4891 refactor: mobile toolbar v3 design
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/_get_selection_color.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/aa_menu/_align_items.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/aa_menu/_bius_items.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/aa_menu/_block_items.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/aa_menu/_close_keyboard_or_menu_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/aa_menu/_color_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/aa_menu/_color_list.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/aa_menu/_font_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/aa_menu/_heading_and_text_items.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/aa_menu/_indent_items.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/aa_menu/_menu_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/aa_menu/_popup_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/aa_menu/_toolbar_theme.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/aa_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/add_block_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/appflowy_mobile_toolbar.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/appflowy_mobile_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/biusc_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/checkbox_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/indent_outdent_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/list_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/toolbar_item_builder.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/undo_redo_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/util.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/plugins.dart
  frontend/appflowy_flutter/lib/workspace/application/settings/appearance/mobile_appearance.dart
  frontend/resources/flowy_icons/16x/m_aa_indent.svg
  frontend/resources/flowy_icons/16x/m_aa_outdent.svg
  frontend/resources/flowy_icons/24x/m_aa_align_center.svg
  frontend/resources/flowy_icons/24x/m_aa_align_left.svg
  frontend/resources/flowy_icons/24x/m_aa_align_right.svg
  frontend/resources/flowy_icons/24x/m_aa_code.svg
  frontend/resources/flowy_icons/24x/m_aa_font_color.svg
  frontend/resources/flowy_icons/24x/m_aa_h1.svg
  frontend/resources/flowy_icons/24x/m_aa_h2.svg
  frontend/resources/flowy_icons/24x/m_aa_h3.svg
  frontend/resources/flowy_icons/24x/m_aa_indent.svg
  frontend/resources/flowy_icons/24x/m_aa_math.svg
  frontend/resources/flowy_icons/24x/m_aa_outdent.svg
  frontend/resources/flowy_icons/24x/m_aa_paragraph.svg
  frontend/resources/flowy_icons/24x/m_aa_quote.svg
  frontend/resources/flowy_icons/24x/m_toolbar_aa.svg
  frontend/resources/flowy_icons/24x/m_toolbar_add.svg
  frontend/resources/flowy_icons/24x/m_toolbar_bold.svg
  frontend/resources/flowy_icons/24x/m_toolbar_bulleted_list.svg
  frontend/resources/flowy_icons/24x/m_toolbar_calendar.svg
  frontend/resources/flowy_icons/24x/m_toolbar_checkbox.svg
  frontend/resources/flowy_icons/24x/m_toolbar_image.svg
  frontend/resources/flowy_icons/24x/m_toolbar_italic.svg
  frontend/resources/flowy_icons/24x/m_toolbar_keyboard.svg
  frontend/resources/flowy_icons/24x/m_toolbar_link.svg
  frontend/resources/flowy_icons/24x/m_toolbar_numbered_list.svg
  frontend/resources/flowy_icons/24x/m_toolbar_redo.svg
  frontend/resources/flowy_icons/24x/m_toolbar_strike.svg
  frontend/resources/flowy_icons/24x/m_toolbar_underline.svg
  frontend/resources/flowy_icons/24x/m_toolbar_undo.svg
Labels: new feature, v0.5.3

#4944 fix: use bg color for mobile url bottom sheet
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/mobile_grid/mobile_grid_url_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/mobile_row_detail/mobile_row_detail_url_cell.dart
Labels: v0.5.3

#4934 Feat/support list item style
  frontend/appflowy_tauri/src/appflowy_app/application/document/document.types.ts
  frontend/appflowy_tauri/src/appflowy_app/components/editor/command/index.ts
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/blocks/bulleted_list/BulletedListIcon.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/blocks/numbered_list/NumberListIcon.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/blocks/text/Text.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/tools/command_panel/mention_panel/MentionPanel.hooks.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/tools/command_panel/mention_panel/MentionPanel.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/tools/command_panel/mention_panel/MentionPanelContent.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/tools/command_panel/slash_command_panel/SlashCommandPanel.hooks.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/tools/selection_toolbar/SelectionToolbar.hooks.ts
  frontend/appflowy_tauri/src/appflowy_app/components/editor/editor.scss
  frontend/appflowy_tauri/src/appflowy_app/components/editor/plugins/shortcuts/withMarkdown.ts
  frontend/appflowy_tauri/src/appflowy_app/utils/list.ts
Labels: tauri, v0.5.3

#4935 chore: kanban filter mvp
  frontend/Makefile.toml
  frontend/appflowy_flutter/lib/plugins/database/application/field/field_info.dart
  frontend/appflowy_flutter/lib/plugins/database/board/application/board_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/board/presentation/board_page.dart
  frontend/appflowy_flutter/lib/plugins/database/board/presentation/toolbar/board_setting_bar.dart
  frontend/appflowy_flutter/lib/plugins/database/domain/filter_service.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/application/filter/filter_menu_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/application/filter/text_filter_editor_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/text.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/url.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/filter_info.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/filter_menu.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/filter_menu_item.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/toolbar/filter_button.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/toolbar/grid_setting_bar.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/setting/mobile_database_controls.dart
  frontend/appflowy_flutter/test/bloc_test/grid_test/filter/filter_menu_test.dart
  frontend/appflowy_tauri/src-tauri/Cargo.lock
  frontend/appflowy_tauri/src-tauri/Cargo.toml
  frontend/appflowy_web/wasm-libs/Cargo.toml
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
  frontend/rust-lib/flowy-database2/src/entities/filter_entities/date_filter.rs
  frontend/rust-lib/flowy-database2/src/entities/row_entities.rs
  frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
  frontend/rust-lib/flowy-database2/src/services/database_view/notifier.rs
  frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs
  frontend/rust-lib/flowy-database2/src/services/database_view/view_group.rs
  frontend/rust-lib/flowy-database2/src/services/database_view/view_sort.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/url_type_option/url_type_option_entities.rs
  frontend/rust-lib/flowy-database2/src/services/filter/entities.rs
  frontend/rust-lib/flowy-database2/src/services/group/action.rs
  frontend/rust-lib/flowy-database2/src/services/group/controller.rs
  frontend/rust-lib/flowy-database2/src/services/group/controller_impls/default_controller.rs
  frontend/rust-lib/flowy-database2/src/services/group/controller_impls/select_option_controller/multi_select_controller.rs
  frontend/rust-lib/flowy-database2/src/services/group/controller_impls/select_option_controller/single_select_controller.rs
  frontend/rust-lib/flowy-database2/src/services/group/group_builder.rs
  frontend/rust-lib/flowy-database2/src/services/sort/controller.rs
  frontend/rust-lib/flowy-database2/src/services/sort/entities.rs
  frontend/rust-lib/flowy-database2/tests/database/sort_test/script.rs
Labels: v0.5.3

#4937 feat: initial version for collab document
  frontend/appflowy_flutter/lib/mobile/application/mobile_router.dart
  frontend/appflowy_flutter/lib/mobile/presentation/base/mobile_view_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/editor/mobile_editor_screen.dart
  frontend/appflowy_flutter/lib/plugins/document/application/collab_document_adapter.dart
  frontend/appflowy_flutter/lib/plugins/document/application/doc_bloc.dart
  frontend/appflowy_flutter/lib/plugins/document/application/doc_service.dart
  frontend/appflowy_flutter/lib/plugins/document/application/doc_sync_bloc.dart
  frontend/appflowy_flutter/lib/plugins/document/application/document_data_pb_extension.dart
  frontend/appflowy_flutter/lib/plugins/document/document.dart
  frontend/appflowy_flutter/lib/plugins/document/document_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/document_sync_indicator.dart
  frontend/appflowy_flutter/lib/shared/feature_flags.dart
  frontend/appflowy_flutter/lib/startup/tasks/generate_router.dart
  frontend/appflowy_flutter/lib/user/application/auth/device_id.dart
  frontend/appflowy_flutter/lib/util/json_print.dart
  frontend/resources/translations/en.json
  frontend/rust-lib/event-integration/tests/document/af_cloud_test/edit_test.rs
  frontend/rust-lib/event-integration/tests/document/supabase_test/edit_test.rs
  frontend/rust-lib/flowy-document/src/entities.rs
Labels: collaboration, v0.5.3

#4954 chore: bump version 0.5.3
  CHANGELOG.md
  frontend/Makefile.toml
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.5.3

#4947 feat: support error for limit exceed
  frontend/rust-lib/flowy-error/src/code.rs
  frontend/rust-lib/flowy-error/src/impl_from/cloud.rs
  frontend/rust-lib/flowy-server/src/af_cloud/impls/user/cloud_service_impl.rs
  frontend/rust-lib/flowy-server/src/local_server/impls/user.rs
  frontend/rust-lib/flowy-server/src/supabase/api/user.rs
  frontend/rust-lib/flowy-user-pub/src/cloud.rs
Labels: v0.5.3

#4936 feat: support custom scrollbar
  frontend/appflowy_tauri/package.json
  frontend/appflowy_tauri/pnpm-lock.yaml
  frontend/appflowy_tauri/src/appflowy_app/application/folder/page.service.ts
  frontend/appflowy_tauri/src/appflowy_app/components/_shared/scroller/AFScroller.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/_shared/scroller/index.ts
  frontend/appflowy_tauri/src/appflowy_app/components/auth/Welcome.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/auth/auth.hooks.ts
  frontend/appflowy_tauri/src/appflowy_app/components/database/components/database_settings/FilterSettings.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/blocks/_shared/PlaceholderContent.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/blocks/text/Text.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/editor/CollaborativeEditor.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/editor/Editor.hooks.ts
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/editor/Editor.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/inline_nodes/mention/MentionLeaf.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/tools/block_actions/BlockActionsToolbar.hooks.ts
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/tools/block_actions/BlockActionsToolbar.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/tools/block_actions/utils.ts
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/tools/command_panel/slash_command_panel/SlashCommandPanel.hooks.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/tools/command_panel/slash_command_panel/SlashCommandPanelContent.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/tools/command_panel/slash_command_panel/const.ts
  frontend/appflowy_tauri/src/appflowy_app/components/editor/editor.scss
  frontend/appflowy_tauri/src/appflowy_app/components/editor/plugins/withBlockDelete.ts
  frontend/appflowy_tauri/src/appflowy_app/components/editor/provider/__tests__/action.test.ts
  frontend/appflowy_tauri/src/appflowy_app/components/editor/provider/__tests__/observe.test.ts
  frontend/appflowy_tauri/src/appflowy_app/components/editor/provider/provider.ts
  frontend/appflowy_tauri/src/appflowy_app/components/layout/Layout.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/layout/bread_crumb/BreadCrumb.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/layout/layout.scss
  frontend/appflowy_tauri/src/appflowy_app/components/layout/nested_page/NestedPage.hooks.ts
  frontend/appflowy_tauri/src/appflowy_app/components/layout/side_bar/Resizer.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/layout/top_bar/DeletePageSnackbar.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/layout/top_bar/TopBar.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/layout/workspace_manager/Workspace.hooks.ts
  frontend/appflowy_tauri/src/appflowy_app/components/layout/workspace_manager/WorkspaceManager.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/settings/SettingsDialog.tsx
  frontend/appflowy_tauri/src/appflowy_app/stores/reducers/current-user/slice.ts
  frontend/appflowy_tauri/src/appflowy_app/stores/reducers/pages/async_actions.ts
  frontend/appflowy_tauri/src/appflowy_app/stores/reducers/pages/slice.ts
  frontend/appflowy_tauri/src/styles/variables/dark.variables.css
  frontend/appflowy_tauri/src/styles/variables/light.variables.css
  frontend/appflowy_tauri/style-dictionary/tailwind/box-shadow.cjs
  frontend/appflowy_tauri/style-dictionary/tailwind/colors.cjs
  frontend/appflowy_tauri/style-dictionary/tokens/dark.json
  frontend/appflowy_tauri/style-dictionary/tokens/light.json
Labels: tauri, react, v0.5.4

#4943 feat: support default shortcuts
  frontend/appflowy_tauri/src/appflowy_app/application/document/document.service.ts
  frontend/appflowy_tauri/src/appflowy_app/components/_shared/popover/Popover.hooks.ts
  frontend/appflowy_tauri/src/appflowy_app/components/_shared/view_title/ViewBanner.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/_shared/view_title/ViewTitleInput.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/database/DatabaseTitle.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/database/components/database_settings/FilterSettings.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/database/components/database_settings/SortSettings.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/database/components/edit_record/EditRecord.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/database/components/edit_record/ExpandRecordModal.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/database/components/edit_record/RecordDocument.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/command/index.ts
  frontend/appflowy_tauri/src/appflowy_app/components/editor/command/mark.ts
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/blocks/page/Page.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/editor/CustomEditable.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/editor/Editor.hooks.ts
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/editor/Editor.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/tools/selection_toolbar/SelectionActions.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/tools/selection_toolbar/actions/align/Align.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/tools/selection_toolbar/actions/bold/Bold.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/tools/selection_toolbar/actions/href/Href.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/tools/selection_toolbar/actions/href/LinkActions.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/tools/selection_toolbar/actions/href/index.ts
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/tools/selection_toolbar/actions/inline_code/InlineCode.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/tools/selection_toolbar/actions/italic/Italic.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/tools/selection_toolbar/actions/strikethrough/StrikeThrough.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/components/tools/selection_toolbar/actions/underline/Underline.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/editor/editor.scss
  frontend/appflowy_tauri/src/appflowy_app/components/editor/plugins/copyPasted/index.ts
  frontend/appflowy_tauri/src/appflowy_app/components/editor/plugins/copyPasted/utils.ts
  frontend/appflowy_tauri/src/appflowy_app/components/editor/plugins/copyPasted/withCopy.ts
  frontend/appflowy_tauri/src/appflowy_app/components/editor/plugins/copyPasted/withPasted.ts
  frontend/appflowy_tauri/src/appflowy_app/components/editor/plugins/shortcuts/markdown.ts
  frontend/appflowy_tauri/src/appflowy_app/components/editor/plugins/shortcuts/shortcuts.hooks.ts
  frontend/appflowy_tauri/src/appflowy_app/components/editor/plugins/shortcuts/withMarkdown.ts
  frontend/appflowy_tauri/src/appflowy_app/components/editor/plugins/withBlockPlugins.ts
  frontend/appflowy_tauri/src/appflowy_app/components/editor/plugins/withPasted.ts
  frontend/appflowy_tauri/src/appflowy_app/components/editor/plugins/withSplitNodes.ts
  frontend/appflowy_tauri/src/appflowy_app/components/editor/provider/utils/action.ts
  frontend/appflowy_tauri/src/appflowy_app/components/layout/Layout.hooks.ts
  frontend/appflowy_tauri/src/appflowy_app/components/layout/Layout.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/layout/collapse_menu_button/CollapseMenuButton.tsx
  frontend/appflowy_tauri/src/appflowy_app/components/layout/layout.scss
  frontend/appflowy_tauri/src/appflowy_app/components/layout/nested_page/NestedPage.hooks.ts
  frontend/appflowy_tauri/src/appflowy_app/components/layout/top_bar/DeletePageSnackbar.tsx
  frontend/appflowy_tauri/src/appflowy_app/utils/hotkeys.ts
Labels: tauri, v0.5.4

#4960 fix: launch review issues
  frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/url_cell_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/select_option/condition_list.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/header/type_option/relation.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/editable_cell_skeleton/url.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/relation_cell_editor.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text_field.dart
Labels: bug, v0.5.3

#4961 fix: collab workspace issues
  frontend/appflowy_flutter/integration_test/shared/workspace.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_folders.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page_header.dart
  frontend/appflowy_flutter/lib/plugins/document/application/doc_service.dart
  frontend/appflowy_flutter/lib/shared/feature_flags.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/splash_screen.dart
  frontend/appflowy_flutter/lib/workspace/application/user/user_workspace_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/view/view_ext.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar_folder.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar_new_page_button.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar_workspace.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/toast.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/settings_dialog.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/members/workspace_member_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/members/workspace_member_page.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/dialogs.dart
  frontend/appflowy_flutter/packages/appflowy_result/lib/src/async_result.dart
  frontend/appflowy_flutter/packages/appflowy_result/lib/src/result.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/src/flowy_overlay/flowy_dialog.dart
  frontend/appflowy_tauri/src-tauri/Cargo.lock
  frontend/appflowy_tauri/src-tauri/Cargo.toml
  frontend/appflowy_web/wasm-libs/Cargo.toml
  frontend/resources/translations/en.json
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
  frontend/rust-lib/event-integration/tests/user/supabase_test/auth_test.rs
  frontend/rust-lib/flowy-error/src/code.rs
  frontend/rust-lib/flowy-error/src/impl_from/cloud.rs
  frontend/rust-lib/flowy-folder/src/entities/view.rs
  frontend/rust-lib/flowy-folder/src/event_handler.rs
  frontend/rust-lib/flowy-folder/src/event_map.rs
  frontend/rust-lib/flowy-folder/src/manager.rs
  frontend/rust-lib/flowy-folder/src/manager_observer.rs
  frontend/rust-lib/flowy-user/src/migrations/workspace_and_favorite_v1.rs
  frontend/rust-lib/flowy-user/src/migrations/workspace_trash_v1.rs
Labels: bug, v0.5.3

#4978 fix: discord notify ci
  .github/workflows/release.yml
Labels: ci, v0.5.3

#4980 chore: adjust select option editor
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/select_option_editor.dart
  frontend/resources/translations/en.json
Labels: v0.5.3

#4984 fix: create new page error on mobile
  frontend/appflowy_flutter/integration_test/mobile/home_page/create_new_page_test.dart
  frontend/appflowy_flutter/lib/mobile/presentation/favorite/mobile_favorite_folder.dart
  frontend/appflowy_flutter/lib/mobile/presentation/favorite/mobile_favorite_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_folders.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/section_folder/mobile_home_section_folder.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/section_folder/mobile_home_section_folder_header.dart
  frontend/appflowy_flutter/lib/shared/custom_image_cache_manager.dart
  frontend/appflowy_flutter/lib/shared/feature_flags.dart
  frontend/appflowy_flutter/lib/workspace/application/menu/prelude.dart
  frontend/appflowy_flutter/lib/workspace/application/menu/sidebar_root_views_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/folder/_section_folder.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar_folder.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_menu.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/resources/translations/en.json
Labels: bug, v0.5.3

#4990 feat: support for switching workspace on mobile
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_folders.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page_header.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/recent_folder/mobile_home_recent_views.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/workspaces/workspace_menu_bottom_sheet.dart
  frontend/appflowy_flutter/lib/mobile/presentation/setting/about/about_setting_group.dart
  frontend/appflowy_flutter/lib/shared/feature_flags.dart
  frontend/appflowy_flutter/lib/startup/tasks/generate_router.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_icon.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/feature_flags/feature_flag_page.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/feature_flags/mobile_feature_flag_screen.dart
  frontend/resources/translations/en.json
Labels: v0.5.3

#4991 feat: show member count on mobile
  frontend/appflowy_flutter/lib/mobile/presentation/favorite/mobile_favorite_folder.dart
  frontend/appflowy_flutter/lib/mobile/presentation/favorite/mobile_favorite_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/section_folder/mobile_home_section_folder.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/section_folder/mobile_home_section_folder_header.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/workspaces/workspace_menu_bottom_sheet.dart
  frontend/appflowy_flutter/lib/mobile/presentation/page_item/mobile_view_item.dart
  frontend/appflowy_flutter/lib/mobile/presentation/widgets/flowy_option_tile.dart
  frontend/appflowy_flutter/lib/workspace/application/favorite/favorite_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/favorite/favorite_listener.dart
  frontend/appflowy_flutter/lib/workspace/application/view/view_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar_workspace.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_icon.dart
Labels: bug, new feature, v0.5.3

#4993 fix: workspace names align issue
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_icon.dart
Labels: bug, v0.5.3

#4983 feat: collab cursor/selection
  frontend/appflowy_flutter/lib/core/config/kv_keys.dart
  frontend/appflowy_flutter/lib/mobile/presentation/base/mobile_view_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/recent_folder/mobile_home_recent_views.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/recent_folder/mobile_recent_view.dart
  frontend/appflowy_flutter/lib/mobile/presentation/setting/about/about_setting_group.dart
  frontend/appflowy_flutter/lib/mobile/presentation/setting/self_host/self_host_bottom_sheet.dart
  frontend/appflowy_flutter/lib/mobile/presentation/setting/self_host_setting_group.dart
  frontend/appflowy_flutter/lib/plugins/document/application/doc_awareness_metadata.dart
  frontend/appflowy_flutter/lib/plugins/document/application/doc_bloc.dart
  frontend/appflowy_flutter/lib/plugins/document/application/doc_collab_adapter.dart
  frontend/appflowy_flutter/lib/plugins/document/application/doc_collaborators_bloc.dart
  frontend/appflowy_flutter/lib/plugins/document/application/doc_listener.dart
  frontend/appflowy_flutter/lib/plugins/document/application/doc_service.dart
  frontend/appflowy_flutter/lib/plugins/document/application/doc_sync_bloc.dart
  frontend/appflowy_flutter/lib/plugins/document/application/doc_sync_state_listener.dart
  frontend/appflowy_flutter/lib/plugins/document/application/document_data_pb_extension.dart
  frontend/appflowy_flutter/lib/plugins/document/document.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/collaborator_avater_stack.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/document_collaborators.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/keyboard_height_observer.dart
  frontend/appflowy_flutter/lib/shared/feature_flags.dart
  frontend/appflowy_flutter/lib/startup/startup.dart
  frontend/appflowy_flutter/lib/startup/tasks/device_info_task.dart
  frontend/appflowy_flutter/lib/user/application/auth/device_id.dart
  frontend/appflowy_flutter/lib/util/color_generator/color_generator.dart
  frontend/appflowy_flutter/lib/util/color_to_hex_string.dart
  frontend/appflowy_flutter/lib/workspace/application/user/user_workspace_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar_workspace.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_icon.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/more_view_actions/more_view_actions.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/user_avatar.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/appflowy_tauri/src-tauri/Cargo.lock
  frontend/appflowy_tauri/src-tauri/Cargo.toml
  frontend/appflowy_web/wasm-libs/Cargo.toml
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
  frontend/rust-lib/flowy-core/src/deps_resolve/document_deps.rs
  frontend/rust-lib/flowy-document/src/document.rs
  frontend/rust-lib/flowy-document/src/entities.rs
  frontend/rust-lib/flowy-document/src/event_handler.rs
  frontend/rust-lib/flowy-document/src/event_map.rs
  frontend/rust-lib/flowy-document/src/manager.rs
  frontend/rust-lib/flowy-document/src/notification.rs
  frontend/rust-lib/flowy-document/tests/document/util.rs
  frontend/rust-lib/flowy-user/src/services/authenticate_user.rs
Labels: v0.5.4

#4992 chore: remove repetitive words
  frontend/appflowy_flutter/lib/startup/tasks/generate_router.dart
  frontend/rust-lib/flowy-folder/src/manager_observer.rs
Labels: v0.5.4

#4942 Leave workspace api
  frontend/rust-lib/event-integration/src/user_event.rs
  frontend/rust-lib/event-integration/tests/user/af_cloud_test/member_test.rs
  frontend/rust-lib/event-integration/tests/user/af_cloud_test/mod.rs
  frontend/rust-lib/event-integration/tests/user/af_cloud_test/util.rs
  frontend/rust-lib/event-integration/tests/user/af_cloud_test/workspace_test.rs
  frontend/rust-lib/flowy-server/src/af_cloud/impls/user/cloud_service_impl.rs
  frontend/rust-lib/flowy-user-pub/src/cloud.rs
  frontend/rust-lib/flowy-user/src/event_handler.rs
  frontend/rust-lib/flowy-user/src/event_map.rs
  frontend/rust-lib/flowy-user/src/user_manager/manager_user_workspace.rs
Labels: v0.5.4

#5011 feat: select option cell editor revamp
  frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/select_option_cell_editor_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/select_option_editor_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/application/field/type_option/select_option_type_option_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/application/field/type_option/select_type_option_actions.dart
  frontend/appflowy_flutter/lib/plugins/database/domain/select_option_cell_service.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/select_option/option_list.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_grid/desktop_grid_select_option_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_row_detail/desktop_row_detail_select_option_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/editable_cell_skeleton/select_option.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/mobile_grid/mobile_grid_select_option_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/mobile_row_detail/mobile_row_detail_select_cell_option.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/extension.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/mobile_select_option_editor.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/select_option_cell_editor.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/select_option_text_field.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/field/type_option_editor/select/select_option.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/field/type_option_editor/select/select_option_editor.dart
  frontend/appflowy_flutter/test/bloc_test/board_test/group_by_multi_select_field_test.dart
  frontend/appflowy_flutter/test/bloc_test/grid_test/cell/select_option_cell_test.dart
  frontend/appflowy_flutter/test/widget_test/select_option_text_field_test.dart
  frontend/resources/translations/en.json
Labels: improvements, grid, v0.5.4

#4994 Update DE translations
  frontend/resources/translations/ar-SA.json
  frontend/resources/translations/ca-ES.json
  frontend/resources/translations/cs-CZ.json
  frontend/resources/translations/de-DE.json
  frontend/resources/translations/es-VE.json
  frontend/resources/translations/eu-ES.json
  frontend/resources/translations/fa.json
  frontend/resources/translations/fr-CA.json
  frontend/resources/translations/fr-FR.json
  frontend/resources/translations/hu-HU.json
  frontend/resources/translations/id-ID.json
  frontend/resources/translations/it-IT.json
  frontend/resources/translations/ko-KR.json
  frontend/resources/translations/pl-PL.json
  frontend/resources/translations/pt-BR.json
  frontend/resources/translations/pt-PT.json
  frontend/resources/translations/ru-RU.json
  frontend/resources/translations/tr-TR.json
  frontend/resources/translations/vi-VN.json
  frontend/resources/translations/zh-CN.json
  frontend/resources/translations/zh-TW.json
Labels: i18n, v0.5.4

#4916 chore: update sv-SE.json
  frontend/resources/translations/ar-SA.json
  frontend/resources/translations/cs-CZ.json
  frontend/resources/translations/sv-SE.json
  project.inlang.json
  project.inlang/settings.json
Labels: i18n, v0.5.4
