Repository AppFlowy-IO/AppFlowy, pull requests merged in 2024-08, with the labels that each got.

#5826 chore: update rocksdb version 0.22.0
  .github/workflows/flutter_ci.yaml
  .github/workflows/rust_ci.yaml
  frontend/appflowy_tauri/src-tauri/Cargo.lock
  frontend/appflowy_tauri/src-tauri/Cargo.toml
  frontend/appflowy_web_app/src-tauri/Cargo.lock
  frontend/appflowy_web_app/src-tauri/Cargo.toml
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
Labels: v0.6.7

#5855 feat: improve reminder color in notification page
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/notifications/mobile_notifications_screen.dart
  frontend/appflowy_flutter/lib/mobile/presentation/notifications/widgets/shared.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_date_block.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
  frontend/appflowy_flutter/lib/user/application/reminder/reminder_bloc.dart
  frontend/appflowy_flutter/lib/user/application/reminder/reminder_extension.dart
Labels: v0.6.7

#5857 chore: optimzie emoji align on desktop
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_icon.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/view_title_bar.dart
Labels: v0.6.7

#5862 fix: + button in the navigation bar doesn't work when the space is not initialized
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_folders.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/section_folder/mobile_home_section_folder.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/section_folder/mobile_home_section_folder_header.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/space/mobile_space.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/tab/mobile_space_tab.dart
  frontend/appflowy_flutter/lib/mobile/presentation/mobile_bottom_navigation_bar.dart
Labels: v0.6.7

#5865 chore: optimize the workspace menu hover status
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space_header.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/sidebar_workspace.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/button.dart
Labels: v0.6.7

#5867 chore: expand inline menu width
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page_header.dart
  frontend/appflowy_flutter/lib/plugins/inline_actions/handlers/inline_page_reference.dart
  frontend/appflowy_flutter/lib/plugins/inline_actions/widgets/inline_actions_handler.dart
  frontend/appflowy_flutter/lib/plugins/inline_actions/widgets/inline_actions_menu_group.dart
Labels: v0.6.7

#5864 feat: support pasting image from Slack
  frontend/appflowy_flutter/integration_test/desktop/document/document_copy_and_paste_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_paste_command.dart
Labels: v0.6.7

#5877 fix: prevent shaking in nested lists deeper in AI message
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.6.7

#5885 fix: remove unused expanded widget
  frontend/appflowy_flutter/lib/shared/icon_emoji_picker/flowy_icon_emoji_picker.dart
Labels: v0.6.7

#5889 feat: optimize editor toolbar tooltip
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_inline_math_equation_test.dart
  frontend/appflowy_flutter/integration_test/desktop/uncategorized/open_ai_smart_menu_test.dart
  frontend/appflowy_flutter/integration_test/shared/base.dart
  frontend/appflowy_flutter/integration_test/shared/editor_test_operations.dart
  frontend/appflowy_flutter/lib/plugins/base/emoji/emoji_picker.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/align_toolbar_item/align_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/font/customize_font_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/inline_math_equation/inline_math_equation_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/smart_edit_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
  frontend/appflowy_flutter/lib/shared/icon_emoji_picker/colors.dart
  frontend/appflowy_flutter/lib/shared/icon_emoji_picker/emoji_search_bar.dart
  frontend/appflowy_flutter/lib/shared/icon_emoji_picker/emoji_skin_tone.dart
  frontend/appflowy_flutter/lib/shared/icon_emoji_picker/icon_picker.dart
  frontend/appflowy_flutter/lib/shared/icon_emoji_picker/icon_search_bar.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/widget/flowy_tooltip.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: improvements, v0.6.7

#5890 feat: move all the heading toolbar items into a popup menu
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/align_toolbar_item/align_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/heading/heading_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/plugins.dart
  frontend/resources/translations/en.json
Labels: improvements, v0.6.7

#5897 chore: optimize mobile ai chat page
  frontend/appflowy_flutter/ios/Podfile.lock
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_input_action_bloc.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/chat_input.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mobile_page_selector_sheet.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/add_block_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
Labels: improvements, v0.6.7

#5903 fix: launch review issues 067
  frontend/appflowy_flutter/lib/mobile/presentation/home/space/mobile_space_header.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/space/mobile_space_menu.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/chat_input.dart
  frontend/appflowy_flutter/lib/plugins/base/emoji/emoji_picker_header.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/string_extension.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/heading/heading_toolbar_item.dart
  frontend/appflowy_flutter/lib/shared/icon_emoji_picker/icon_picker.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/create_space_popup.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/manage_space_popup.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/shared_widget.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/space_icon.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/space_icon_popup.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/space_more_popup.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_actions.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/widget/flowy_tooltip.dart
  frontend/resources/translations/en.json
Labels: v0.6.7

#5848 chore: update German translations to state of v0.6.7
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_plan_comparison_dialog.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/resources/translations/ar-SA.json
  frontend/resources/translations/ca-ES.json
  frontend/resources/translations/ckb-KU.json
  frontend/resources/translations/cs-CZ.json
  frontend/resources/translations/de-DE.json
  frontend/resources/translations/en.json
  frontend/resources/translations/es-VE.json
  frontend/resources/translations/eu-ES.json
  frontend/resources/translations/fa.json
  frontend/resources/translations/fr-CA.json
  frontend/resources/translations/fr-FR.json
  frontend/resources/translations/he.json
  frontend/resources/translations/hu-HU.json
  frontend/resources/translations/id-ID.json
  frontend/resources/translations/it-IT.json
  frontend/resources/translations/ja-JP.json
  frontend/resources/translations/ko-KR.json
  frontend/resources/translations/pl-PL.json
  frontend/resources/translations/pt-BR.json
  frontend/resources/translations/pt-PT.json
  frontend/resources/translations/ru-RU.json
  frontend/resources/translations/sv-SE.json
  frontend/resources/translations/tr-TR.json
  frontend/resources/translations/uk-UA.json
  frontend/resources/translations/vi-VN.json
  frontend/resources/translations/vi.json
  frontend/resources/translations/zh-CN.json
  frontend/resources/translations/zh-TW.json
Labels: translation, v0.6.7

#5918 chore: update editor version
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_markdown_text.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/layout/sizes.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/header/mobile_grid_header.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/emoji_picker_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_cut_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_paste_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/paste_from_html.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/paste_from_in_app_json.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/paste_from_plain_text.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/plugins.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/quote/quote_block_shortcuts.dart
  frontend/appflowy_flutter/lib/plugins/shared/share/_shared.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/button.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.6.7

#5926 fix: link to two calendars in same doc may failed randomly
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/database/database_view_block_component.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_menu.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/resources/translations/en.json
Labels: v0.6.7

#5928 chore: polish upload image menu
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/upload_image_menu/upload_image_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/upload_image_menu/widgets/embed_image_url_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text.dart
Labels: v0.6.7

#5917 fix: list paste bug #5846
  frontend/appflowy_flutter/integration_test/desktop/document/document_copy_and_paste_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_cut_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_paste_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/editor_state_paste_node_extension.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/paste_from_html.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/paste_from_in_app_json.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/paste_from_plain_text.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.6.7

#5927 chore: remove stability ai
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/image_placeholder.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/multi_image_block_component/multi_image_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/multi_image_block_component/multi_image_placeholder.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/upload_image_menu/upload_image_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/upload_image_menu/widgets/open_ai_image_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/upload_image_menu/widgets/stability_ai_image_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/stability_ai/stability_ai_client.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/stability_ai/stability_ai_error.dart
  frontend/appflowy_flutter/lib/startup/deps_resolver.dart
  frontend/resources/translations/en.json
Labels: v0.6.7

#5936 chore: center confirm or cancel
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/shared_widget.dart
Labels: v0.6.7

#5941 feat: display no access page
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_page_block.dart
  frontend/appflowy_flutter/lib/plugins/shared/share/_shared.dart
  frontend/appflowy_flutter/lib/plugins/shared/share/publish_tab.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/shared/single_setting_action.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/button.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/primary_rounded_button.dart
  frontend/resources/translations/en.json
Labels: v0.6.7

#5948 chore: optimize recent section performance
  frontend/appflowy_flutter/lib/workspace/application/tabs/tabs_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/view_title/view_title_bar_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/view_title_bar.dart
Labels: v0.6.7

#5949 chore: bump version 0.6.7
  CHANGELOG.md
  frontend/appflowy_flutter/lib/mobile/presentation/mobile_bottom_navigation_bar.dart
  frontend/appflowy_flutter/lib/shared/red_dot.dart
  frontend/appflowy_flutter/lib/workspace/presentation/notifications/widgets/notification_button.dart
  frontend/appflowy_tauri/src-tauri/Cargo.lock
  frontend/appflowy_tauri/src-tauri/Cargo.toml
  frontend/appflowy_web_app/src-tauri/Cargo.lock
  frontend/appflowy_web_app/src-tauri/Cargo.toml
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
  frontend/rust-lib/flowy-user/src/user_manager/manager_user_awareness.rs
Labels: v0.6.7

#5930 chore: optimize generation speed
  frontend/appflowy_flutter/build.yaml
  frontend/appflowy_flutter/packages/appflowy_backend/pubspec.yaml
  frontend/appflowy_flutter/packages/appflowy_result/pubspec.yaml
  frontend/appflowy_flutter/packages/flowy_infra/pubspec.yaml
  frontend/appflowy_flutter/packages/flowy_infra_ui/pubspec.yaml
  frontend/appflowy_flutter/packages/flowy_svg/analysis_options.yaml
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/scripts/code_generation/flowy_icons/generate_flowy_icons.sh
  frontend/scripts/code_generation/freezed/generate_freezed.sh
  frontend/scripts/code_generation/generate.sh
  frontend/scripts/code_generation/language_files/generate_language_files.sh
  frontend/scripts/makefile/flutter.toml
Labels: improvements, v0.6.8

#5954 feat: optimize date picker & mention block
  frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_rename_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/application/editor_transaction_adapter.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_block.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_date_block.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/mobile_appflowy_date_picker.dart
Labels: v0.6.8

#5959 feat: integrate sentry flutter
  frontend/appflowy_flutter/dart_dependency_validator.yaml
  frontend/appflowy_flutter/ios/Podfile.lock
  frontend/appflowy_flutter/lib/env/env.dart
  frontend/appflowy_flutter/lib/mobile/application/user_profile/user_profile_bloc.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page.dart
  frontend/appflowy_flutter/lib/startup/startup.dart
  frontend/appflowy_flutter/lib/startup/tasks/prelude.dart
  frontend/appflowy_flutter/lib/startup/tasks/sentry.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/desktop_home_screen.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.6.8

#5975 feat: open the row page on mobile
  frontend/appflowy_flutter/lib/mobile/application/mobile_router.dart
  frontend/appflowy_flutter/lib/mobile/presentation/base/app_bar/app_bar.dart
  frontend/appflowy_flutter/lib/mobile/presentation/base/app_bar/app_bar_actions.dart
  frontend/appflowy_flutter/lib/mobile/presentation/base/mobile_view_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_rename_widget.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/mobile_card_detail_screen.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/widgets/row_page_button.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/application/calculations/calculations_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database_document/presentation/database_document_title.dart
  frontend/appflowy_flutter/lib/plugins/document/application/document_collaborators_bloc.dart
  frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/view_title_bar.dart
  frontend/resources/translations/en.json
Labels: v0.6.8

#5978 chore: add loading indicator when generating freezed file
  frontend/scripts/code_generation/freezed/generate_freezed.sh
Labels: v0.6.8

#5980 fix: unable to insert todo list via slash menu
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_database_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items.dart
  frontend/appflowy_flutter/lib/startup/tasks/sentry.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/resources/translations/en.json
Labels: bug, v0.6.8

#5986 feat: support inviting members on mobile
  frontend/appflowy_flutter/ios/Podfile.lock
  frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_view_item.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_setting_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/tab/mobile_space_tab.dart
  frontend/appflowy_flutter/lib/mobile/presentation/setting/user_session_setting_group.dart
  frontend/appflowy_flutter/lib/mobile/presentation/setting/workspace/invite_members_screen.dart
  frontend/appflowy_flutter/lib/mobile/presentation/setting/workspace/member_list.dart
  frontend/appflowy_flutter/lib/mobile/presentation/setting/workspace/workspace_setting_group.dart
  frontend/appflowy_flutter/lib/mobile/presentation/widgets/show_flowy_mobile_confirm_dialog.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/startup/tasks/generate_router.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/dialogs.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/divider.dart
  frontend/resources/translations/en.json
Labels: v0.6.8

#5987 fix: support pasting web image on mobile
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/clipboard_service.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_paste_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/paste_from_image.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_floating_toolbar/custom_mobile_floating_toolbar.dart
Labels: v0.6.8

#5989 chore: support monochrome icon on Android
  frontend/appflowy_flutter/android/app/src/main/ic_launcher-playstore.png
  frontend/appflowy_flutter/android/app/src/main/res/drawable/launcher_background.xml
  frontend/appflowy_flutter/android/app/src/main/res/drawable/launcher_foreground.xml
  frontend/appflowy_flutter/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  frontend/appflowy_flutter/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  frontend/appflowy_flutter/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  frontend/appflowy_flutter/android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  frontend/appflowy_flutter/android/app/src/main/res/mipmap-hdpi/ic_launcher_monochrome.png
  frontend/appflowy_flutter/android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  frontend/appflowy_flutter/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  frontend/appflowy_flutter/android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  frontend/appflowy_flutter/android/app/src/main/res/mipmap-mdpi/ic_launcher_monochrome.png
  frontend/appflowy_flutter/android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  frontend/appflowy_flutter/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  frontend/appflowy_flutter/android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  frontend/appflowy_flutter/android/app/src/main/res/mipmap-xhdpi/ic_launcher_monochrome.png
  frontend/appflowy_flutter/android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  frontend/appflowy_flutter/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  frontend/appflowy_flutter/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  frontend/appflowy_flutter/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_monochrome.png
  frontend/appflowy_flutter/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  frontend/appflowy_flutter/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  frontend/appflowy_flutter/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  frontend/appflowy_flutter/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_monochrome.png
  frontend/appflowy_flutter/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  frontend/appflowy_flutter/android/app/src/main/res/values/ic_launcher_background.xml
Labels: v0.6.8

#5992 feat: add ai bubble button on home page
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/tab/ai_bubble_button.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/tab/mobile_space_tab.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_welcome_page.dart
Labels: v0.6.8

#5995 chore: optimize row card page UI
  frontend/appflowy_flutter/lib/mobile/application/mobile_router.dart
  frontend/appflowy_flutter/lib/mobile/application/recent/recent_view_bloc.dart
  frontend/appflowy_flutter/lib/mobile/presentation/base/mobile_view_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/mobile_card_detail_screen.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/widgets/mobile_create_field_button.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/widgets/row_page_button.dart
  frontend/appflowy_flutter/lib/mobile/presentation/editor/mobile_editor_screen.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/favorite_folder/favorite_space.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/home_space/home_space.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_folders.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/recent_folder/recent_space.dart
  frontend/appflowy_flutter/lib/mobile/presentation/setting/support_setting_group.dart
  frontend/appflowy_flutter/lib/mobile/presentation/setting/workspace/invite_members_screen.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/layout/sizes.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/row/row.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/mobile_row_detail/mobile_row_detail_summary_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/mobile_row_detail/mobile_row_detail_translate_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/row/row_property.dart
  frontend/appflowy_flutter/lib/plugins/document/document.dart
  frontend/appflowy_flutter/lib/plugins/document/document_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_add_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_option_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/cover/document_immersive_cover.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/upload_image_menu/upload_image_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/upload_image_menu/widgets/embed_image_url_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/upload_image_menu/widgets/upload_image_file_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/loading.dart
  frontend/appflowy_flutter/lib/startup/tasks/generate_router.dart
  frontend/appflowy_flutter/lib/workspace/application/recent/cached_recent_service.dart
  frontend/appflowy_flutter/lib/workspace/application/sidebar/space/space_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/fix_data_widget.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/dialogs.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/button.dart
  frontend/scripts/code_generation/freezed/generate_freezed.sh
  frontend/scripts/code_generation/generate.sh
Labels: v0.6.8

#6017 fix: ignore case sensitive of image name when dragging image to document
  frontend/appflowy_flutter/lib/plugins/document/document_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/paste_from_image.dart
Labels: v0.6.8

#5973 Update translations - FR-FR
  frontend/resources/translations/fr-FR.json
Labels: translation, v0.6.8

#5991 Fix(Linux): Fixed AppImage build, removed Wayland Header
  frontend/appflowy_flutter/linux/my_application.cc
  frontend/scripts/linux_distribution/appimage/AppImageBuilder.yml
Labels: v0.6.8

#6034 chore: update member exceeded hint text
  frontend/appflowy_flutter/lib/mobile/presentation/setting/workspace/invite_members_screen.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/auto_completion_node_widget.dart
  frontend/resources/translations/en.json
Labels: v0.6.8

#6035 fix: ai writer generate button color
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/auto_completion_node_widget.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/shared_widget.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_actions.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/shared/single_setting_action.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/button.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/primary_rounded_button.dart
Labels: v0.6.8

#6039 fix: update settings menu color
  frontend/appflowy_flutter/lib/mobile/presentation/home/setting/settings_popup_menu.dart
  frontend/appflowy_flutter/lib/mobile/presentation/setting/workspace/invite_members_screen.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/dialogs.dart
Labels: v0.6.8

#6071 feat: customize transition animation for popup menu
  frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_view_item.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page_header.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/setting/settings_popup_menu.dart
  frontend/appflowy_flutter/lib/mobile/presentation/notifications/widgets/settings_popup_menu.dart
  frontend/appflowy_flutter/lib/shared/popup_menu/appflowy_popup_menu.dart
  frontend/resources/translations/en.json
Labels: v0.6.8

#6074 fix: table render error
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/shared/empty_placeholder.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/workspace/application/sidebar/space/space_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.6.8

#6049 feat: support sign in with Apple
  frontend/appflowy_flutter/integration_test/shared/auth_operation.dart
  frontend/appflowy_flutter/ios/Runner.xcodeproj/project.pbxproj
  frontend/appflowy_flutter/ios/Runner/Info.plist
  frontend/appflowy_flutter/ios/Runner/Runner.entitlements
  frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_rename_widget.dart
  frontend/appflowy_flutter/lib/mobile/presentation/setting/cloud/appflowy_cloud_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/setting/user_session_setting_group.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/checklist_cell_editor.dart
  frontend/appflowy_flutter/lib/user/application/auth/af_cloud_auth_service.dart
  frontend/appflowy_flutter/lib/user/application/sign_in_bloc.dart
  frontend/appflowy_flutter/lib/user/presentation/helpers/handle_open_workspace_error.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/desktop_sign_in_screen.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/mobile_sign_in_screen.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/sign_in_screen.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/magic_link_sign_in_buttons.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/sign_in_agreement.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/sign_in_anonymous_button.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/sign_in_or_logout_button.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/third_party_sign_in_button.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/third_party_sign_in_buttons.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/widgets.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/shared/single_setting_action.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/mobile_appflowy_date_picker.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/dialogs.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/button.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text_field.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/widget/rounded_button.dart
  frontend/resources/flowy_icons/40x/m_apple_icon.svg
  frontend/resources/flowy_icons/40x/m_discord_icon.svg
  frontend/resources/flowy_icons/40x/m_github_icon.svg
  frontend/resources/flowy_icons/40x/m_google_icon.svg
  frontend/resources/translations/en.json
Labels: v0.6.8

#6093 fix: expand the icon to be the same size as the text in the heading block
  frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_hidden_groups.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_page_block.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
Labels: v0.6.8

#6082 feat: optimize sync error page
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_inline_page_test.dart
  frontend/appflowy_flutter/lib/mobile/presentation/base/animated_gesture.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page_header.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/shared/mobile_page_card.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/tab/ai_bubble_button.dart
  frontend/appflowy_flutter/lib/mobile/presentation/notifications/widgets/multi_select_notification_item.dart
  frontend/appflowy_flutter/lib/mobile/presentation/notifications/widgets/notification_item.dart
  frontend/appflowy_flutter/lib/plugins/document/document_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/appflowy_mobile_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/sync_error_page.dart
  frontend/appflowy_flutter/lib/plugins/shared/share/export_tab.dart
  frontend/appflowy_flutter/lib/plugins/shared/share/share_bloc.dart
  frontend/appflowy_flutter/lib/shared/popup_menu/appflowy_popup_menu.dart
  frontend/appflowy_flutter/lib/startup/startup.dart
  frontend/appflowy_flutter/lib/startup/tasks/platform_error_catcher.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/mobile_sign_in_screen.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/third_party_sign_in_button.dart
  frontend/appflowy_flutter/lib/workspace/application/settings/share/export_service.dart
  frontend/appflowy_flutter/lib/workspace/application/sidebar/space/space_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/footer/sidebar_footer.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/footer/sidebar_footer_button.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/dialogs.dart
  frontend/resources/flowy_icons/16x/icon_template.svg
  frontend/resources/flowy_icons/40x/icon_warning.svg
  frontend/resources/translations/en.json
  frontend/rust-lib/flowy-core/src/deps_resolve/folder_deps.rs
  frontend/rust-lib/flowy-database2/src/entities/share_entities.rs
  frontend/rust-lib/flowy-database2/src/event_handler.rs
  frontend/rust-lib/flowy-database2/src/event_map.rs
  frontend/rust-lib/flowy-database2/src/manager.rs
Labels: v0.6.8

#6097 fix: reset first page when switching space
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_inline_page_test.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/board/mobile_board_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_folders.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/space/mobile_space.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/mobile_grid_page.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/row/mobile_row.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/mobile_grid/mobile_grid_text_cell.dart
  frontend/appflowy_flutter/lib/plugins/document/document_page.dart
  frontend/appflowy_flutter/lib/shared/flowy_error_page.dart
  frontend/appflowy_flutter/lib/workspace/application/sidebar/space/space_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart
Labels: v0.6.8

#6065 fix: Modified to launch the app from docker-compose.
  frontend/scripts/docker-buildfiles/Dockerfile
Labels: v0.6.8

#6121 feat: upgrade template button style
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/footer/sidebar_footer.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/footer/sidebar_footer_button.dart
  frontend/resources/flowy_icons/16x/icon_delete.svg
  frontend/resources/flowy_icons/16x/icon_template.svg
Labels: v0.6.8

#6126 fix: typo in german translation
  frontend/resources/translations/de-DE.json
Labels: translation, v0.6.8

#6111 chore: updated Arabic translation
  frontend/resources/translations/ar-SA.json
Labels: translation, v0.6.8

#6058 chore: update it-IT translations
  frontend/resources/translations/it-IT.json
Labels: translation, v0.6.8

#6106 chore: update Fr-fr translations
  frontend/resources/translations/fr-FR.json
Labels: translation, v0.6.8

#6084 chore: update ar-SA and fr-FR translations
  frontend/resources/translations/ar-SA.json
  frontend/resources/translations/fr-FR.json
Labels: translation, v0.6.8

#6128 fix: android toast style
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/setting/workspace/member_list.dart
  frontend/appflowy_flutter/lib/shared/popup_menu/appflowy_popup_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/shared_widget.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/button.dart
Labels: v0.6.8
