Repository AppFlowy-IO/AppFlowy, pull requests merged in 2024-11, with the labels that each got.

#6681 fix: date reminder test
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_date_reminder_test.dart
Labels: v0.7.3

#6672 fix: owner can delete spaces created by other users
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/space_more_popup.dart
Labels: v0.7.3

#6692 chore: bump version 0.7.3
  frontend/Makefile.toml
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/smart_edit_node_widget.dart
  frontend/appflowy_flutter/packages/flowy_infra/pubspec.yaml
  frontend/appflowy_flutter/packages/flowy_infra_ui/pubspec.yaml
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.7.3

#6701 fix: settings site issues
  frontend/appflowy_flutter/integration_test/desktop/cloud/document/document_publish_test.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/workspace/workspace_settings_test.dart
  frontend/appflowy_flutter/lib/plugins/shared/share/_shared.dart
  frontend/appflowy_flutter/lib/plugins/shared/share/publish_tab.dart
  frontend/appflowy_flutter/lib/plugins/shared/share/share_bloc.dart
  frontend/appflowy_flutter/lib/plugins/shared/share/share_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/sites/constants.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/sites/domain/domain_item.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/sites/domain/domain_more_action.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/sites/domain/home_page_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/sites/publish_info_view_item.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/sites/published_page/published_view_item.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/sites/published_page/published_view_more_action.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/sites/settings_sites_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/sites/settings_sites_view.dart
  frontend/resources/translations/en.json
  frontend/scripts/code_generation/freezed/generate_freezed.cmd
Labels: v0.7.3

#6714 fix: toggle heading issues
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_toggle_heading_block_test.dart
  frontend/appflowy_flutter/lib/plugins/document/document_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_option_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_option_cubit.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/option/color_option_action.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/option/turn_into_option_action.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/heading/heading_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/shortcuts/heading_block_shortcuts.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toggle/toggle_block_component.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/resources/translations/en.json
Labels: v0.7.3

#6726 fix: align the namespace and toggle shortcuts
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toggle/toggle_block_shortcuts.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/sites/domain/domain_item.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/appflowy_flutter/test/unit_test/document/shortcuts/toggle_list_shortcut_test.dart
  frontend/resources/translations/en.json
Labels: v0.7.3

#6739 fix: block option interceptor
  frontend/appflowy_flutter/integration_test/desktop/document/document_block_option_test.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_test_runner_4.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/option_button.dart
Labels: v0.7.3

#6740 fix: application window is not visible on Windows
  frontend/appflowy_flutter/windows/runner/flutter_window.cpp
  frontend/appflowy_flutter/windows/runner/main.cpp
  frontend/appflowy_flutter/windows/runner/win32_window.cpp
  frontend/appflowy_flutter/windows/runner/win32_window.h
Labels: v0.7.3

#6730 fix: v0.7.3 additional launch review session issues
  frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/date_cell_editor_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_row_detail/desktop_row_detail_checklist_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/checklist_cell_editor.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/checklist_cell_textfield.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/appflowy_date_picker_base.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/desktop_date_picker.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/widgets/reminder_selector.dart
  frontend/appflowy_flutter/test/bloc_test/grid_test/cell/date_cell_bloc_test.dart
  frontend/appflowy_tauri/src-tauri/Cargo.lock
  frontend/appflowy_tauri/src-tauri/Cargo.toml
  frontend/appflowy_web_app/src-tauri/Cargo.lock
  frontend/appflowy_web_app/src-tauri/Cargo.toml
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
  frontend/rust-lib/flowy-user/src/user_manager/manager_user_awareness.rs
Labels: v0.7.3

#6746 chore: bump collab
  frontend/appflowy_tauri/src-tauri/Cargo.lock
  frontend/appflowy_tauri/src-tauri/Cargo.toml
  frontend/appflowy_web_app/src-tauri/Cargo.lock
  frontend/appflowy_web_app/src-tauri/Cargo.toml
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
Labels: v0.7.3

#6747 feat: include member count in get_workspace API
  frontend/rust-lib/flowy-server/src/af_cloud/impls/user/cloud_service_impl.rs
  frontend/rust-lib/flowy-server/src/local_server/impls/user.rs
  frontend/rust-lib/flowy-sqlite/migrations/2024-11-08-102351_workspace_member_count/down.sql
  frontend/rust-lib/flowy-sqlite/migrations/2024-11-08-102351_workspace_member_count/up.sql
  frontend/rust-lib/flowy-sqlite/src/schema.rs
  frontend/rust-lib/flowy-user-pub/src/entities.rs
  frontend/rust-lib/flowy-user-pub/src/session.rs
  frontend/rust-lib/flowy-user/src/entities/user_profile.rs
  frontend/rust-lib/flowy-user/src/services/sqlite_sql/workspace_sql.rs
Labels: v0.7.4

#6763 fix: hidden group name overflow
  frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_hidden_groups.dart
Labels: v0.7.4

#6719 feat: integrate codemagic for testing ios/android
  .github/workflows/ios_ci.yaml
  .github/workflows/mobile_ci.yml
  codemagic.yaml
  frontend/appflowy_flutter/integration_test/mobile/document/page_style_test.dart
  frontend/appflowy_flutter/integration_test/mobile/home_page/create_new_page_test.dart
  frontend/appflowy_flutter/integration_test/mobile/sign_in/anonymous_sign_in_test.dart
  frontend/appflowy_flutter/integration_test/mobile_runner_1.dart
  frontend/appflowy_flutter/integration_test/runner.dart
  frontend/appflowy_flutter/lib/mobile/presentation/base/mobile_view_page.dart
  frontend/appflowy_flutter/pubspec.lock
Labels: v0.7.4

#6764 feat: support creating and managing a space on mobile
  .github/workflows/ios_ci.yaml
  frontend/appflowy_flutter/integration_test/desktop/cloud/data_migration/anon_user_data_migration_test.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/document/document_publish_test.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/sidebar/sidebar_move_page_test.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/uncategorized/appflowy_cloud_auth_test.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/uncategorized/document_sync_test.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/uncategorized/user_setting_sync_test.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/workspace/change_name_and_icon_test.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/workspace/collaborative_workspace_test.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/workspace/share_menu_test.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/workspace/workspace_icon_test.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/workspace/workspace_settings_test.dart
  frontend/appflowy_flutter/integration_test/mobile/cloud/cloud_runner.dart
  frontend/appflowy_flutter/integration_test/mobile/cloud/document/publish_test.dart
  frontend/appflowy_flutter/integration_test/mobile/cloud/document/share_link_test.dart
  frontend/appflowy_flutter/integration_test/mobile/cloud/space/space_test.dart
  frontend/appflowy_flutter/integration_test/mobile/cloud/workspace/workspace_operations_test.dart
  frontend/appflowy_flutter/integration_test/mobile/document/page_style_test.dart
  frontend/appflowy_flutter/integration_test/mobile/document/title_test.dart
  frontend/appflowy_flutter/integration_test/mobile/home_page/create_new_page_test.dart
  frontend/appflowy_flutter/integration_test/mobile/sign_in/anonymous_sign_in_test.dart
  frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/show_mobile_bottom_sheet.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/space/constants.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/space/manage_space_widget.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/space/mobile_space.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/space/mobile_space_menu.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/space/space_menu_bottom_sheet.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/space/space_permission_bottom_sheet.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/space/widgets.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/tab/mobile_space_tab.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/workspaces/create_workspace_menu.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/workspaces/workspace_menu_bottom_sheet.dart
  frontend/appflowy_flutter/lib/shared/icon_emoji_picker/icon.dart
  frontend/appflowy_flutter/lib/shared/icon_emoji_picker/icon_picker.dart
  frontend/appflowy_flutter/lib/startup/tasks/generate_router.dart
  frontend/appflowy_flutter/lib/util/navigator_context_extension.dart
  frontend/appflowy_flutter/lib/util/string_extension.dart
  frontend/appflowy_flutter/lib/workspace/application/sidebar/space/space_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/shared/sidebar_new_page_button.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/create_space_popup.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space_header.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/account/account_deletion.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/account/account_sign_in_out.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/sites/published_page/published_view_item.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/files/settings_file_exporter_widget.dart
  frontend/appflowy_flutter/packages/appflowy_backend/lib/ffi.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/button.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/resources/translations/en.json
Labels: v0.7.4

#6775 Support uploading webp
  .github/workflows/mobile_ci.yml
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_image_block_test.dart
  frontend/appflowy_flutter/lib/shared/patterns/common_patterns.dart
Labels: v0.7.4

#6758 feat: optimize the workspace menu loading speed
  .github/workflows/rust_ci.yaml
  frontend/appflowy_flutter/integration_test/desktop/cloud/workspace/collaborative_workspace_test.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/workspaces/workspace_menu_bottom_sheet.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_actions.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/sidebar_workspace.dart
  frontend/rust-lib/flowy-user/src/user_manager/manager_user_workspace.rs
Labels: v0.7.4

#6766 feat: last publish name
  .github/workflows/ios_ci.yaml
  .github/workflows/rust_ci.yaml
  frontend/appflowy_flutter/integration_test/desktop/cloud/document/document_publish_test.dart
  frontend/appflowy_flutter/lib/mobile/presentation/base/view_page/more_bottom_sheet.dart
  frontend/appflowy_flutter/lib/plugins/shared/share/publish_tab.dart
  frontend/appflowy_flutter/lib/plugins/shared/share/share_bloc.dart
  frontend/appflowy_flutter/lib/shared/error_code/error_code_map.dart
  frontend/resources/translations/en.json
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
  frontend/rust-lib/flowy-folder/src/entities/publish.rs
Labels: v0.7.4

#6780 feat: optimize the font menu speed
  frontend/appflowy_flutter/integration_test/desktop/document/document_test_runner_4.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_toolbar_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/font/customize_font_toolbar_item.dart
Labels: v0.7.4

#6717 chore: update zh-CN translations
  frontend/resources/translations/zh-CN.json
Labels: translation, v0.7.4

#6669 fix(flutter_desktop): document search
  frontend/appflowy_flutter/integration_test/desktop/document/document_find_menu_test.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_test_runner_4.dart
  frontend/appflowy_flutter/lib/plugins/document/document_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/find_and_replace/find_and_replace_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/cover_title.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/document_cover_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/shared_context/shared_context.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text_input.dart
Labels: v0.7.4

#6791 fix(mobile): selecting date from cupertino date widget resets time
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/mobile_date_picker.dart
Labels: v0.7.4

#6792 fix: launch 0.7.4 review issues on desktop
  frontend/appflowy_flutter/integration_test/desktop/cloud/workspace/change_name_and_icon_test.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/workspace/collaborative_workspace_test.dart
  frontend/appflowy_flutter/integration_test/mobile_runner_1.dart
  frontend/appflowy_flutter/integration_test/shared/workspace.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_markdown_text.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_actions.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_menu.dart
  frontend/rust-lib/flowy-ai/src/local_ai/watch.rs
Labels: v0.7.4

#6798 feat: support editing path name on mobile
  frontend/appflowy_flutter/integration_test/mobile/cloud/document/publish_test.dart
  frontend/appflowy_flutter/lib/mobile/presentation/base/view_page/more_bottom_sheet.dart
  frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_view_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/space/mobile_space_menu.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/workspaces/create_workspace_menu.dart
  frontend/appflowy_flutter/lib/plugins/shared/share/share_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/dialogs.dart
  frontend/resources/translations/en.json
Labels: v0.7.4

#6821 fix: cannot paste text into the title of the doc
  frontend/appflowy_flutter/integration_test/desktop/document/document_title_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_paste_command.dart
Labels: v0.7.4

#6819 fix: tab change speed + remove favorite option
  frontend/appflowy_flutter/lib/workspace/application/tabs/tab_menu_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/home_stack.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/tabs/flowy_tab.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/tabs/tabs_manager.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/tab_bar_item.dart
Labels: v0.7.4

#6828 feat: wrap code block code
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_editor_style.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.7.4

#6824 feat: support creating subpage block in row detail page
  frontend/appflowy_flutter/integration_test/desktop/database/database_row_page_test.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_sub_page_test.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_outline_block_test.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/row/row_document.dart
  frontend/appflowy_flutter/lib/plugins/database_document/database_document_page.dart
  frontend/appflowy_flutter/lib/plugins/database_document/presentation/database_document_title.dart
  frontend/appflowy_flutter/lib/plugins/document/document_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/util.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/cover_title.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/appflowy_mobile_toolbar.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/outline/outline_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/shared_context/shared_context.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/sub_page/sub_page_block_component.dart
Labels: v0.7.4

#6745 chore: inno setup ignore version on .exe
  frontend/scripts/windows_installer/inno_setup_config.iss
Labels: platform-windows, v0.7.5

#6835 chore: bump flutter chat ui version
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_bloc.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_entity.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_message_service.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_user_message_bloc.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_user_message_bubble_bloc.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/animated_chat_list.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/desktop_ai_prompt_input.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/mobile_ai_prompt_input.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_related_question.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_theme.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_user_invalid_message.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/layout_define.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_message_bubble.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_text_message.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/user_message_bubble.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/user_text_message.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/scroll_to_bottom.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/resources/flowy_icons/16x/ai_scroll_to_bottom.svg
Labels: v0.7.5

#6836 chore: simplify chat user message bloc and widgets
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_user_message_bloc.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_user_message_bubble_bloc.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_message_bubble.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/user_message_bubble.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/user_text_message.dart
Labels: v0.7.5

#6841 chore: delete upload task when upload size exceed limit
  frontend/appflowy_tauri/src-tauri/Cargo.lock
  frontend/appflowy_tauri/src-tauri/Cargo.toml
  frontend/appflowy_web_app/src-tauri/Cargo.lock
  frontend/appflowy_web_app/src-tauri/Cargo.toml
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
  frontend/rust-lib/event-integration-test/src/lib.rs
  frontend/rust-lib/event-integration-test/src/user_event.rs
  frontend/rust-lib/event-integration-test/tests/document/af_cloud_test/file_upload_test.rs
  frontend/rust-lib/flowy-core/src/config.rs
  frontend/rust-lib/flowy-core/src/integrate/server.rs
  frontend/rust-lib/flowy-core/src/integrate/trait_impls.rs
  frontend/rust-lib/flowy-core/src/integrate/user.rs
  frontend/rust-lib/flowy-document/src/event_handler.rs
  frontend/rust-lib/flowy-document/src/manager.rs
  frontend/rust-lib/flowy-document/tests/document/util.rs
  frontend/rust-lib/flowy-server-pub/src/native/af_cloud_config.rs
  frontend/rust-lib/flowy-server/src/af_cloud/impls/file_storage.rs
  frontend/rust-lib/flowy-server/src/af_cloud/server.rs
  frontend/rust-lib/flowy-storage-pub/src/chunked_byte.rs
  frontend/rust-lib/flowy-storage-pub/src/cloud.rs
  frontend/rust-lib/flowy-storage-pub/src/storage.rs
  frontend/rust-lib/flowy-storage/src/manager.rs
  frontend/rust-lib/flowy-storage/src/sqlite_sql.rs
  frontend/rust-lib/flowy-storage/src/uploader.rs
  frontend/rust-lib/flowy-storage/tests/multiple_part_upload_test.rs
Labels: v0.7.5

#6856 feat: support skipping in-memory update transaction
  frontend/appflowy_flutter/integration_test/desktop/cloud/document/document_ai_writer_test.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/document/document_test_runner.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_image_block_test.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_multi_image_block_test.dart
  frontend/appflowy_flutter/lib/plugins/document/application/document_bloc.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/text_robot.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/auto_completion_node_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/outline/outline_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/transaction_handler/editor_transaction_service.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/appflowy_flutter/test/unit_test/document/text_robot/text_robot_test.dart
Labels: v0.7.5

#6831 feat: simple table redesign
  frontend/appflowy_flutter/integration_test/desktop/document/document_test_runner_4.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_simple_table_test.dart
  frontend/appflowy_flutter/lib/plugins/document/application/document_data_pb_extension.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/visual_drag_area.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/file/file_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/keyboard_interceptor/keyboard_interceptor.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/shortcuts/command_shortcuts.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/table/shared_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/table/shortcuts/simple_table_arrow_down_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/table/shortcuts/simple_table_arrow_left_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/table/shortcuts/simple_table_arrow_right_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/table/shortcuts/simple_table_arrow_up_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/table/shortcuts/simple_table_backspace_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/table/shortcuts/simple_table_commands.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/table/shortcuts/simple_table_tab_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/table/shortcuts/table_command_extension.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/table/simple_table_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/table/simple_table_cell_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/table/simple_table_constants.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/table/simple_table_more_action.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/table/simple_table_row_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/table/table_operations/table_content_operation.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/table/table_operations/table_delete_operation.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/table/table_operations/table_duplicate_operation.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/table/table_operations/table_header_operation.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/table/table_operations/table_insert_operation.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/table/table_operations/table_map_operation.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/table/table_operations/table_node_extension.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/table/table_operations/table_operations.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/table/table_operations/table_style_operation.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/color_picker.dart
  frontend/appflowy_flutter/test/unit_test/simple_table/simple_table_contente_operation_test.dart
  frontend/appflowy_flutter/test/unit_test/simple_table/simple_table_delete_operation_test.dart
  frontend/appflowy_flutter/test/unit_test/simple_table/simple_table_duplicate_operation_test.dart
  frontend/appflowy_flutter/test/unit_test/simple_table/simple_table_header_operation_test.dart
  frontend/appflowy_flutter/test/unit_test/simple_table/simple_table_insert_operation_test.dart
  frontend/appflowy_flutter/test/unit_test/simple_table/simple_table_style_operation_test.dart
  frontend/appflowy_flutter/test/unit_test/simple_table/simple_table_test_helper.dart
  frontend/resources/flowy_icons/16x/table_align_center.svg
  frontend/resources/flowy_icons/16x/table_align_left.svg
  frontend/resources/flowy_icons/16x/table_align_right.svg
  frontend/resources/flowy_icons/16x/table_clear_content.svg
  frontend/resources/flowy_icons/16x/table_header_column.svg
  frontend/resources/flowy_icons/16x/table_header_row.svg
  frontend/resources/flowy_icons/16x/table_insert_above.svg
  frontend/resources/flowy_icons/16x/table_insert_below.svg
  frontend/resources/flowy_icons/16x/table_insert_left.svg
  frontend/resources/flowy_icons/16x/table_insert_right.svg
  frontend/resources/flowy_icons/16x/table_reorder_column.svg
  frontend/resources/flowy_icons/16x/table_reorder_row.svg
  frontend/resources/translations/en.json
Labels: v0.7.5, v0.7.6

#6860 fix: RwLock race condition during group controller instantiation
  frontend/appflowy_flutter/lib/plugins/database/application/tab_bar_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/board/presentation/board_page.dart
  frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs
  frontend/rust-lib/flowy-database2/src/services/database_view/view_group.rs
  frontend/rust-lib/flowy-database2/src/services/database_view/views.rs
  frontend/rust-lib/flowy-database2/src/services/group/action.rs
  frontend/rust-lib/flowy-database2/src/services/group/controller.rs
  frontend/rust-lib/flowy-database2/src/services/group/controller_impls/date_controller.rs
  frontend/rust-lib/flowy-database2/src/services/group/controller_impls/default_controller.rs
  frontend/rust-lib/flowy-database2/src/services/group/controller_impls/select_option_controller/multi_select_controller.rs
  frontend/rust-lib/flowy-database2/src/services/group/controller_impls/select_option_controller/single_select_controller.rs
  frontend/rust-lib/flowy-database2/src/services/group/group_builder.rs
  frontend/rust-lib/flowy-database2/tests/database/group_test/url_group_test.rs
Labels: v0.7.6

#6883 fix: unable to render code block in ai writer block
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/markdown_text_robot.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/ai_writer_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/ask_ai_action_bloc.dart
  frontend/appflowy_flutter/test/unit_test/document/text_robot/markdown_text_robot_test.dart
Labels: v0.7.6
