Repository AppFlowy-IO/AppFlowy, pull requests merged in 2024-05, with the labels that each got.

#5235 fix: export created at and last modified cells to csv
  frontend/rust-lib/flowy-database2/src/services/share/csv/export.rs
  frontend/rust-lib/flowy-database2/tests/database/share_test/export_test.rs
Labels: bug, v0.5.6

#5214 Fix/new group clear splash
  frontend/appflowy_flutter/lib/mobile/presentation/database/board/widgets/mobile_board_trailing.dart
  frontend/appflowy_flutter/lib/mobile/presentation/widgets/flowy_mobile_quick_action_button.dart
  frontend/resources/translations/en.json
Labels: v0.5.6

#5158 feat: support mention page on mobile
  frontend/appflowy_flutter/lib/plugins/database/widgets/row/row_document.dart
  frontend/appflowy_flutter/lib/plugins/document/document.dart
  frontend/appflowy_flutter/lib/plugins/document/document_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/collaborator_avater_stack.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_notification.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_block.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_page_block.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mobile_page_selector_sheet.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/add_block_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/appflowy_mobile_toolbar.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/util.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
  frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/command_palette.dart
  frontend/resources/translations/en.json
Labels: v0.5.6

#5243 feat: adjust toolbar count based on the screen size
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/appflowy_mobile_toolbar.dart
Labels: v0.5.6

#5244 chore: upgrade editor version
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: bug, v0.5.6

#5266 fix: kanban related launch review issues
  frontend/appflowy_flutter/lib/plugins/database/widgets/row/row_banner.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/row/row_detail.dart
  frontend/resources/translations/en.json
Labels: v0.5.6

#5251 feat: request permission again if the user denied the photo permission
  frontend/appflowy_flutter/android/app/src/main/AndroidManifest.xml
  frontend/appflowy_flutter/ios/Podfile
  frontend/appflowy_flutter/ios/Podfile.lock
  frontend/appflowy_flutter/ios/Runner.xcodeproj/project.pbxproj
  frontend/appflowy_flutter/lib/mobile/presentation/widgets/show_flowy_mobile_confirm_dialog.dart
  frontend/appflowy_flutter/lib/plugins/document/application/document_collab_adapter.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/page_style/_page_style_cover_image.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/members/workspace_member_page.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/resources/translations/en.json
Labels: bug, v0.5.6

#5268 chore: remove debug print
  frontend/appflowy_flutter/lib/plugins/document/application/document_collab_adapter.dart
Labels: bug, v0.5.6

#5269 fix: the cursor will jump up when creating a new document on desktop.
  frontend/appflowy_flutter/integration_test/desktop/uncategorized/appearance_settings_test.dart
  frontend/appflowy_flutter/ios/Podfile.lock
  frontend/appflowy_flutter/lib/mobile/presentation/setting/font/font_picker_screen.dart
  frontend/appflowy_flutter/lib/mobile/presentation/setting/font/font_setting.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/document_header_node_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/service/openai_client.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/page_style/_page_style_layout.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/font_family_setting.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/view_title_bar.dart
  frontend/appflowy_flutter/test/bloc_test/home_test/trash_bloc_test.dart
  frontend/resources/translations/en.json
Labels: bug, v0.5.6

#5267 fix: korean IME issue on Windows
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: bug, v0.5.6

#5271 chore: drop old user awarenss when open workspace
  frontend/rust-lib/flowy-user/src/user_manager/manager_user_awareness.rs
  frontend/rust-lib/flowy-user/src/user_manager/manager_user_workspace.rs
Labels: bug, v0.5.6

#5263 fix: launch review improvements
  frontend/appflowy_flutter/lib/mobile/application/mobile_router.dart
  frontend/appflowy_flutter/lib/mobile/presentation/favorite/mobile_favorite_folder.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/favorite_folder/mobile_home_favorite_folder.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/recent_folder/mobile_home_recent_views.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/section_folder/mobile_home_section_folder.dart
  frontend/appflowy_flutter/lib/mobile/presentation/page_item/mobile_view_item.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/setting/setting_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/emoji_picker_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/code_block/code_language_screen.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/font/customize_font_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/add_block_toolbar_item.dart
  frontend/appflowy_flutter/lib/workspace/application/recent/cached_recent_service.dart
  frontend/appflowy_flutter/lib/workspace/application/recent/recent_views_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/home_stack.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/folder/_favorite_folder.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/folder/_folder_header.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar_folder.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_account_view.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/files/settings_file_exporter_widget.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/font_family_setting.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_customize_shortcuts_view.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_menu_element.dart
  frontend/resources/translations/en.json
Labels: bug, v0.5.6

#5272 fix: assert on uploading image on macos
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/upload_image_file_widget.dart
Labels: bug, v0.5.6

#5276 fix: color selection compatible with older versions
  frontend/appflowy_flutter/lib/mobile/presentation/home/recent_folder/mobile_recent_view.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/cover/document_immersive_cover.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/desktop_cover.dart
  frontend/appflowy_flutter/lib/util/string_extension.dart
  frontend/appflowy_flutter/packages/flowy_infra/lib/theme_extension.dart
Labels: bug, v0.5.6

#5282 fix: ws connect with invalid token
  frontend/appflowy_tauri/src-tauri/Cargo.lock
  frontend/appflowy_tauri/src-tauri/Cargo.toml
  frontend/appflowy_web/wasm-libs/Cargo.lock
  frontend/appflowy_web/wasm-libs/Cargo.toml
  frontend/appflowy_web_app/src-tauri/Cargo.lock
  frontend/appflowy_web_app/src-tauri/Cargo.toml
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
  frontend/rust-lib/flowy-core/Cargo.toml
  frontend/rust-lib/flowy-error/Cargo.toml
  frontend/rust-lib/flowy-server/Cargo.toml
  frontend/rust-lib/flowy-server/src/af_cloud/server.rs
Labels: bug, v0.5.6

#5279 feat: support system default font family on desktop
  frontend/appflowy_flutter/integration_test/desktop/uncategorized/appearance_settings_test.dart
  frontend/appflowy_flutter/lib/mobile/application/page_style/document_page_style_bloc.dart
  frontend/appflowy_flutter/lib/mobile/presentation/base/mobile_view_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/setting/font/font_picker_screen.dart
  frontend/appflowy_flutter/lib/mobile/presentation/setting/font/font_setting.dart
  frontend/appflowy_flutter/lib/plugins/document/application/document_appearance_cubit.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/cover/document_immersive_cover.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/upload_image_file_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/aa_menu/_font_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/page_style/_page_style_cover_image.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/page_style/_page_style_layout.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
  frontend/appflowy_flutter/lib/shared/permission/permission_checker.dart
  frontend/appflowy_flutter/lib/util/font_family_extension.dart
  frontend/appflowy_flutter/lib/util/google_font_family_extension.dart
  frontend/appflowy_flutter/lib/workspace/application/appearance_defaults.dart
  frontend/appflowy_flutter/lib/workspace/application/settings/appearance/base_appearance.dart
  frontend/appflowy_flutter/lib/workspace/application/settings/appearance/desktop_appearance.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/font_family_setting.dart
  frontend/appflowy_flutter/test/bloc_test/app_setting_test/appearance_test.dart
  frontend/appflowy_flutter/test/bloc_test/app_setting_test/document_appearance_test.dart
  frontend/appflowy_flutter/test/widget_test/theme_font_family_setting_test.dart
  frontend/rust-lib/flowy-user/src/entities/user_setting.rs
Labels: new feature, v0.5.6

#5278 chore: translate english to traditional chinese
  frontend/resources/translations/ar-SA.json
  frontend/resources/translations/ca-ES.json
  frontend/resources/translations/ckb-KU.json
  frontend/resources/translations/cs-CZ.json
  frontend/resources/translations/de-DE.json
  frontend/resources/translations/es-VE.json
  frontend/resources/translations/eu-ES.json
  frontend/resources/translations/fa.json
  frontend/resources/translations/fr-CA.json
  frontend/resources/translations/fr-FR.json
  frontend/resources/translations/hu-HU.json
  frontend/resources/translations/id-ID.json
  frontend/resources/translations/it-IT.json
  frontend/resources/translations/ja-JP.json
  frontend/resources/translations/ko-KR.json
  frontend/resources/translations/pl-PL.json
  frontend/resources/translations/pt-BR.json
  frontend/resources/translations/pt-PT.json
  frontend/resources/translations/ru-RU.json
  frontend/resources/translations/sv-SE.json
  frontend/resources/translations/tr-TR.json
  frontend/resources/translations/vi-VN.json
  frontend/resources/translations/vi.json
  frontend/resources/translations/zh-CN.json
  frontend/resources/translations/zh-TW.json
Labels: translation, v0.5.7

#5288 refactor: mobile view page
  .github/workflows/ios_ci.yaml
  frontend/appflowy_flutter/integration_test/mobile/page_style/document_page_style_test.dart
  frontend/appflowy_flutter/integration_test/mobile_runner.dart
  frontend/appflowy_flutter/integration_test/shared/common_operations.dart
  frontend/appflowy_flutter/integration_test/shared/expectation.dart
  frontend/appflowy_flutter/lib/mobile/application/base/mobile_view_page_bloc.dart
  frontend/appflowy_flutter/lib/mobile/presentation/base/mobile_view_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/base/view_page/app_bar_buttons.dart
  frontend/appflowy_flutter/lib/mobile/presentation/base/view_page/more_bottom_sheet.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_page_block.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
  frontend/appflowy_flutter/lib/workspace/application/view/view_ext.dart
Labels: improvements, v0.5.7

#5270 feat: add kanban shortcuts
  frontend/appflowy_flutter/integration_test/desktop/board/board_add_row_test.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_database_test.dart
  frontend/appflowy_flutter/integration_test/desktop/sidebar/sidebar_test.dart
  frontend/appflowy_flutter/integration_test/shared/database_test_op.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/board/board.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/board/mobile_board_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/board/widgets/group_card_header.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/board/widgets/mobile_hidden_groups_column.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/mobile_card_detail_screen.dart
  frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/relation_cell_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/application/field/type_option/relation_type_option_cubit.dart
  frontend/appflowy_flutter/lib/plugins/database/application/row/row_cache.dart
  frontend/appflowy_flutter/lib/plugins/database/application/row/row_service.dart
  frontend/appflowy_flutter/lib/plugins/database/board/application/board_actions_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/board/application/board_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/board/presentation/board_page.dart
  frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_column_header.dart
  frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_focus_scope.dart
  frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_hidden_groups.dart
  frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_shortcut_container.dart
  frontend/appflowy_flutter/lib/plugins/database/calendar/application/calendar_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/calendar/application/calendar_event_editor_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/calendar/presentation/calendar_event_card.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/application/grid_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/row/action.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/card/card.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/card/container/card_container.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/card_cell_skeleton/card_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/card_cell_skeleton/text_card_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/editable_cell_skeleton/text.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/row/row_action.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/row/row_banner.dart
  frontend/appflowy_flutter/lib/shared/conditional_listenable_builder.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/appflowy_flutter/test/bloc_test/board_test/create_card_test.dart
  frontend/appflowy_flutter/test/bloc_test/board_test/create_or_edit_field_test.dart
  frontend/appflowy_flutter/test/bloc_test/board_test/group_by_checkbox_field_test.dart
  frontend/appflowy_flutter/test/bloc_test/board_test/group_by_multi_select_field_test.dart
  frontend/appflowy_flutter/test/bloc_test/board_test/group_by_unsupport_field_test.dart
  frontend/rust-lib/event-integration-test/src/database_event.rs
  frontend/rust-lib/event-integration-test/tests/database/local_test/test.rs
  frontend/rust-lib/flowy-database2/src/entities/row_entities.rs
  frontend/rust-lib/flowy-database2/src/entities/type_option_entities/relation_entities.rs
  frontend/rust-lib/flowy-database2/src/event_handler.rs
  frontend/rust-lib/flowy-database2/src/event_map.rs
  frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
  frontend/rust-lib/flowy-database2/tests/database/group_test/script.rs
Labels: new feature, kanban board, v0.5.7

#5294 fix: remove the shadow color from the back button if not in immersive mode.
  frontend/appflowy_flutter/lib/mobile/presentation/base/mobile_view_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/base/view_page/app_bar_buttons.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/cover/document_immersive_cover.dart
Labels: bug, v0.5.7

#5300 feat: add support for scaling the application with a factor range of 0.5 to 2.0
  frontend/appflowy_flutter/lib/core/config/kv_keys.dart
  frontend/appflowy_flutter/lib/main.dart
  frontend/appflowy_flutter/lib/startup/startup.dart
  frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart
  frontend/appflowy_flutter/lib/startup/tasks/app_window_size_manager.dart
  frontend/appflowy_flutter/lib/startup/tasks/windows.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/hotkeys.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: improvements, v0.5.7

#5307 fix: kanban board card text input inconsistency
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/card_cell_skeleton/text_card_cell.dart
Labels: bug, kanban board, v0.5.7

#5316 chore: udpated yrs to v0.18.8
  frontend/appflowy_tauri/src-tauri/Cargo.toml
  frontend/appflowy_web/wasm-libs/Cargo.toml
  frontend/appflowy_web_app/src-tauri/Cargo.toml
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
Labels: v0.5.8

#5309 chore: improve floating mobile toolbar animation for iOS
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_floating_toolbar/custom_mobile_floating_toolbar.dart
Labels: improvements, mobile, v0.5.8

#5265 feat: settings manage data
  frontend/appflowy_flutter/integration_test/desktop/uncategorized/switch_folder_test.dart
  frontend/appflowy_flutter/integration_test/shared/settings.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/encrypt_secret_screen.dart
  frontend/appflowy_flutter/lib/workspace/application/settings/settings_dialog_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_manage_data_view.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/settings_dialog.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/shared/setting_action.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/files/setting_file_import_appflowy_data_view.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/files/settings_export_file_widget.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/files/settings_file_cache_widget.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/files/settings_file_customize_location_view.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_file_system_view.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_menu.dart
  frontend/resources/translations/en.json
Labels: v0.5.8

#5315 fix: ensure text update bug doesn't happen on number/url
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/card_cell_skeleton/text_card_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/editable_cell_skeleton/number.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/editable_cell_skeleton/url.dart
Labels: bug, v0.5.8

#5329 fix: font family warning
  frontend/appflowy_flutter/lib/shared/google_fonts_extension.dart
Labels: bug, v0.5.8

#5321 Update German translations
  frontend/resources/translations/de-DE.json
  frontend/resources/translations/es-VE.json
Labels: translation, v0.5.8

#5331 feat: support pressing enter key to insert new line within callout block
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_shortcuts.dart
Labels: improvements, v0.5.8

#5334 fix: add space above logo on welcome screen
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/desktop_sign_in_screen.dart
Labels: bug, v0.5.8

#5335 Update German translations
  frontend/resources/translations/ar-SA.json
  frontend/resources/translations/ca-ES.json
  frontend/resources/translations/ckb-KU.json
  frontend/resources/translations/cs-CZ.json
  frontend/resources/translations/de-DE.json
  frontend/resources/translations/en.json
  frontend/resources/translations/es-VE.json
  frontend/resources/translations/eu-ES.json
  frontend/resources/translations/fa.json
  frontend/resources/translations/fr-CA.json
  frontend/resources/translations/fr-FR.json
  frontend/resources/translations/hu-HU.json
  frontend/resources/translations/id-ID.json
  frontend/resources/translations/it-IT.json
  frontend/resources/translations/ja-JP.json
  frontend/resources/translations/ko-KR.json
  frontend/resources/translations/pl-PL.json
  frontend/resources/translations/pt-BR.json
  frontend/resources/translations/pt-PT.json
  frontend/resources/translations/ru-RU.json
  frontend/resources/translations/sv-SE.json
  frontend/resources/translations/tr-TR.json
  frontend/resources/translations/vi-VN.json
  frontend/resources/translations/vi.json
  frontend/resources/translations/zh-CN.json
  frontend/resources/translations/zh-TW.json
Labels: translation, v0.5.8

#5356 Update fr-FR.json: fix typo
  frontend/resources/translations/fr-FR.json
Labels: translation, v0.5.8

#5369 Support Ukrainian language #5350
  project.inlang/settings.json
Labels: translation, v0.5.8

#5370 fix: heading node validate failed
  frontend/appflowy_flutter/lib/plugins/document/application/document_data_pb_extension.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/error/error_block_component_builder.dart
  frontend/resources/translations/en.json
Labels: bug, v0.5.8

#5366 fix: chaning field type #5360
  frontend/appflowy_flutter/integration_test/desktop/board/board_field_test.dart
  frontend/appflowy_flutter/integration_test/shared/database_test_op.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/card/mobile_card_content.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/card/card.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/card/card_bloc.dart
Labels: v0.5.8

#5371 fix: use full update states instead of patch update
  frontend/appflowy_flutter/lib/plugins/document/application/document_bloc.dart
  frontend/appflowy_tauri/src-tauri/Cargo.lock
  frontend/appflowy_tauri/src-tauri/Cargo.toml
  frontend/appflowy_web/wasm-libs/Cargo.toml
  frontend/appflowy_web_app/src-tauri/Cargo.lock
  frontend/appflowy_web_app/src-tauri/Cargo.toml
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
Labels: bug, v0.5.8

#5375 fix: infinite loop when getting ancestor for orphan view
  frontend/rust-lib/event-integration-test/src/folder_event.rs
  frontend/rust-lib/event-integration-test/tests/folder/local_test/folder_test.rs
  frontend/rust-lib/flowy-folder/src/manager.rs
Labels: bug, v0.5.8

#5381 chore: add limitation when importing csv file
  frontend/rust-lib/flowy-database2/src/manager.rs
Labels: bug, v0.5.8

#5376 fix: unable to remove the remote selection when the user close the page on mobile
  frontend/appflowy_flutter/lib/plugins/document/application/document_bloc.dart
  frontend/appflowy_flutter/lib/plugins/document/application/document_collab_adapter.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/page_style/_page_style_cover_image.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/page_style/_page_style_icon.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/page_style/_page_style_layout.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
Labels: bug, v0.5.8

#5367 fix: launch review 0.5.8
  frontend/appflowy_flutter/integration_test/desktop/document/document_more_actions_test.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_test_runner.dart
  frontend/appflowy_flutter/integration_test/shared/common_operations.dart
  frontend/appflowy_flutter/lib/mobile/presentation/setting/font/font_picker_screen.dart
  frontend/appflowy_flutter/lib/plugins/base/emoji/emoji_picker.dart
  frontend/appflowy_flutter/lib/user/application/user_listener.dart
  frontend/appflowy_flutter/lib/util/theme_extension.dart
  frontend/appflowy_flutter/lib/workspace/application/settings/date_time/time_format_ext.dart
  frontend/appflowy_flutter/lib/workspace/application/settings/workspace/workspace_settings_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_icon.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_account_view.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_manage_data_view.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_workspace_view.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/shared/af_dropdown_menu_entry.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/shared/settings_dropdown.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/members/workspace_member_page.dart
  frontend/resources/flowy_icons/24x/settings_selected_theme.svg
  frontend/resources/translations/en.json
  frontend/rust-lib/flowy-folder/src/notification.rs
Labels: v0.5.8

#5382 Update German translations
  frontend/resources/translations/ar-SA.json
  frontend/resources/translations/ca-ES.json
  frontend/resources/translations/ckb-KU.json
  frontend/resources/translations/cs-CZ.json
  frontend/resources/translations/de-DE.json
  frontend/resources/translations/en.json
  frontend/resources/translations/es-VE.json
  frontend/resources/translations/eu-ES.json
  frontend/resources/translations/fa.json
  frontend/resources/translations/fr-CA.json
  frontend/resources/translations/fr-FR.json
  frontend/resources/translations/hu-HU.json
  frontend/resources/translations/id-ID.json
  frontend/resources/translations/it-IT.json
  frontend/resources/translations/ja-JP.json
  frontend/resources/translations/ko-KR.json
  frontend/resources/translations/pl-PL.json
  frontend/resources/translations/pt-BR.json
  frontend/resources/translations/pt-PT.json
  frontend/resources/translations/ru-RU.json
  frontend/resources/translations/sv-SE.json
  frontend/resources/translations/tr-TR.json
  frontend/resources/translations/uk-UA.json
  frontend/resources/translations/vi-VN.json
  frontend/resources/translations/vi.json
  frontend/resources/translations/zh-CN.json
  frontend/resources/translations/zh-TW.json
Labels: translation, v0.5.9

#5414 fix: accept multi-key combination for customizing shortcuts & removes duplicates
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/workspace/application/settings/shortcuts/settings_shortcuts_cubit.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_customize_shortcuts_view.dart
Labels: bug, v0.5.9

#5416 chore: improve hover and text colors in dark mode
  frontend/appflowy_flutter/lib/workspace/presentation/home/home_stack.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/shared/sidebar_new_page_button.dart
  frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/default_colorscheme.dart
Labels: improvements, v0.5.9

#5404 fix: dragging the Unsplash cover triggers an assertion error
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/page_style/_page_style_cover_image.dart
Labels: bug, v0.5.9

#5386 Add hotkey to reset app scale
  frontend/appflowy_flutter/lib/workspace/presentation/home/hotkeys.dart
Labels: improvements, v0.5.9

#5199 feat: video block support
  .github/workflows/flutter_ci.yaml
  frontend/appflowy_flutter/android/app/src/main/AndroidManifest.xml
  frontend/appflowy_flutter/ios/Podfile.lock
  frontend/appflowy_flutter/ios/Runner/Info.plist
  frontend/appflowy_flutter/lib/main.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/custom_image_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/add_block_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/video/upload_video_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/video/video_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/video/video_placeholder.dart
  frontend/appflowy_flutter/lib/shared/patterns/common_patterns.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/resources/flowy_icons/16x/m_add_block_video.svg
  frontend/resources/translations/en.json
  frontend/scripts/docker-buildfiles/Dockerfile
  frontend/scripts/install_dev_env/install_linux.sh
  frontend/scripts/linux_distribution/appimage/AppImageBuilder.yml
Labels: v0.5.9

#5205 Update translations
  frontend/resources/translations/de-DE.json
  frontend/resources/translations/es-VE.json
Labels: translation, v0.5.9

#5421 Update German translations
  frontend/resources/translations/de-DE.json
  frontend/resources/translations/en.json
Labels: translation, v0.5.9

#5428 feat: add border to selected unsplash image
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/unsplash_image_widget.dart
Labels: improvements, v0.5.9

#5302 feat: integrate show notification button option
  frontend/appflowy_flutter/lib/core/config/kv_keys.dart
  frontend/appflowy_flutter/lib/workspace/application/settings/notifications/notification_settings_cubit.dart
  frontend/appflowy_flutter/lib/workspace/presentation/notifications/widgets/notification_button.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_notifications_view.dart
  frontend/resources/translations/de-DE.json
  frontend/resources/translations/en.json
  frontend/resources/translations/es-VE.json
Labels: improvements, v0.5.9

#5439 fix: some list icons don't align with the paragraph
  frontend/Makefile.toml
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/bulleted_list/bulleted_list_icon.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/todo_list/todo_list_icon.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_menu.dart
  frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/default_colorscheme.dart
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.5.9

#5440 fix: notification test
  frontend/appflowy_flutter/integration_test/desktop/settings/notifications_settings_test.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/section_folder/mobile_home_section_folder.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/shared/mobile_view_card.dart
  frontend/appflowy_flutter/lib/workspace/application/recent/cached_recent_service.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text.dart
Labels: v0.5.9

#5444 fix: sidebar issues
  frontend/appflowy_flutter/lib/mobile/application/recent/recent_view_bloc.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/favorite_folder/favorite_space.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/home_space/home_space.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/recent_folder/recent_space.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/shared/mobile_view_card.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/tab/_tab_bar.dart
  frontend/appflowy_flutter/lib/mobile/presentation/mobile_bottom_navigation_bar.dart
  frontend/appflowy_flutter/lib/mobile/presentation/page_item/mobile_view_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/cover/document_immersive_cover.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/icon/icon_selector.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/page_style/_page_style_icon.dart
  frontend/appflowy_flutter/lib/workspace/application/view/view_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/favorites/favorite_folder.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/favorites/favorite_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/favorites/favorite_menu_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/favorites/favorite_pin_action.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/footer/sidebar_footer.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
  frontend/resources/flowy_icons/16x/m_collapse.svg
  frontend/resources/translations/el-GR.json
  frontend/resources/translations/en.json
Labels: bug, v0.5.9
