Repository AppFlowy-IO/AppFlowy, pull requests merged in 2024-06, with the labels that each got.

#5443 fix: launch review 0.5.9
  .github/actions/flutter_build/action.yml
  .github/actions/flutter_integration_test/action.yml
  .github/workflows/release.yml
  frontend/appflowy_flutter/integration_test/shared/base.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/video/upload_video_menu.dart
  frontend/appflowy_flutter/lib/shared/patterns/common_patterns.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/af_focus_manager.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/desktop_home_screen.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/hotkeys.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/favorites/favorite_more_actions.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/shared/sidebar_setting.dart
  frontend/appflowy_flutter/linux/flutter/dart_ffi/binding.h
  frontend/resources/translations/en.json
  frontend/scripts/linux_distribution/appimage/AppImageBuilder.yml
Labels: bug, v0.5.9

#5447 chore: call FolderEventSetLatestView when opening page on mobile
  frontend/appflowy_flutter/lib/mobile/application/mobile_router.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/menu_shared_state.dart
  frontend/rust-lib/dart-ffi/src/lib.rs
Labels: improvements, v0.5.9

#5450 feat: integrate add new page button on mobile
  frontend/appflowy_flutter/lib/mobile/presentation/mobile_bottom_navigation_bar.dart
  frontend/appflowy_flutter/lib/mobile/presentation/page_item/mobile_view_item.dart
  frontend/appflowy_flutter/lib/workspace/application/workspace/workspace_service.dart
  frontend/resources/flowy_icons/24x/m_home_unselected.svg
Labels: v0.5.9

#5454 fix: workspace id not match
  frontend/rust-lib/flowy-document/src/event_handler.rs
  frontend/rust-lib/flowy-document/src/manager.rs
Labels: v0.5.9

#5453 fix: improve sidebar UI
  frontend/appflowy_flutter/lib/core/frameless_window.dart
  frontend/appflowy_flutter/lib/plugins/database/board/board.dart
  frontend/appflowy_flutter/lib/plugins/database/calendar/calendar.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/grid.dart
  frontend/appflowy_flutter/lib/plugins/database_document/database_document_plugin.dart
  frontend/appflowy_flutter/lib/plugins/document/document.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/cover_editor.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/desktop_cover.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/document_header_node_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/migration/editor_migration.dart
  frontend/appflowy_flutter/lib/workspace/application/view/view_ext.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/favorites/favorite_folder.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/folder/_folder_header.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/folder/_section_folder.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/footer/sidebar_footer.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/header/sidebar_top_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/shared/sidebar_folder.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/shared/sidebar_new_page_button.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/shared/sidebar_setting.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_icon.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/sidebar_workspace.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_add_button.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/navigation.dart
  frontend/appflowy_flutter/lib/workspace/presentation/notifications/widgets/notification_button.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/favorite_button.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/float_bubble/question_bubble.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/pop_up_action.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/view_title_bar.dart
  frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/default_colorscheme.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/widget/flowy_tooltip.dart
  frontend/appflowy_flutter/packages/flowy_svg/lib/src/flowy_svg.dart
  frontend/resources/flowy_icons/16x/favorited.svg
  frontend/resources/flowy_icons/16x/help_center.svg
  frontend/resources/flowy_icons/16x/icon_board.svg
  frontend/resources/flowy_icons/16x/icon_calendar.svg
  frontend/resources/flowy_icons/16x/icon_document.svg
  frontend/resources/flowy_icons/16x/icon_grid.svg
  frontend/resources/flowy_icons/16x/icon_import.svg
  frontend/resources/flowy_icons/16x/workspace_drop_down_menu_hide.svg
  frontend/resources/flowy_icons/16x/workspace_drop_down_menu_show.svg
  frontend/resources/flowy_icons/24x/favorite_header_icon.svg
  frontend/resources/flowy_icons/24x/new_app.svg
  frontend/resources/flowy_icons/24x/sidebar_footer_trash.svg
Labels: bug, v0.5.9

#5449 fix: font not found error log
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
  frontend/appflowy_flutter/lib/shared/google_fonts_extension.dart
  frontend/appflowy_flutter/lib/workspace/application/settings/appearance/appearance_cubit.dart
  frontend/appflowy_flutter/lib/workspace/application/settings/appearance/base_appearance.dart
  frontend/appflowy_flutter/test/bloc_test/app_setting_test/appearance_test.dart
  frontend/appflowy_flutter/test/widget_test/direction_setting_test.dart
Labels: v0.5.9

#5460 fix: some keys conflict with board shortcuts
  frontend/appflowy_flutter/lib/plugins/database/board/presentation/board_page.dart
  frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_column_header.dart
  frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_shortcut_container.dart
  frontend/appflowy_flutter/lib/plugins/shared/callback_shortcuts.dart
Labels: v0.5.9

#5461 feat: change user avatar corner radius
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/header/sidebar_user.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/user_avatar.dart
Labels: bug, v0.5.9

#5463 feat: support slide actions on mobile
  frontend/appflowy_flutter/ios/Podfile.lock
  frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_add_new_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_view_item_body.dart
  frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/default_mobile_action_pane.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/favorite_folder/mobile_home_favorite_folder.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_folders.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page_header.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/recent_folder/recent_space.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/section_folder/mobile_home_section_folder.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/section_folder/mobile_home_section_folder_header.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/shared/mobile_view_card.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/workspaces/workspace_menu_bottom_sheet.dart
  frontend/appflowy_flutter/lib/mobile/presentation/page_item/mobile_slide_action_button.dart
  frontend/appflowy_flutter/lib/mobile/presentation/page_item/mobile_view_item.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/favorites/favorite_folder.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/header/sidebar_top_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_icon.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/sidebar_workspace.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/widget/flowy_tooltip.dart
Labels: v0.5.9

#5476 chore: update chat icon
  frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_add_new_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_view_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/default_mobile_action_pane.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/mobile_card_detail_screen.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_quick_field_editor.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_view_quick_actions.dart
  frontend/appflowy_flutter/lib/mobile/presentation/page_item/mobile_view_item.dart
  frontend/appflowy_flutter/lib/workspace/application/favorite/favorite_service.dart
  frontend/appflowy_flutter/windows/runner/flutter_window.cpp
  frontend/resources/flowy_icons/16x/chat_ai_page.svg
  frontend/resources/flowy_icons/16x/workspace_three_dots.svg
  frontend/resources/translations/en.json
Labels: v0.5.9

#5473 fix: search improvements
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/search_field.dart
  frontend/appflowy_tauri/src-tauri/Cargo.toml
  frontend/appflowy_web/wasm-libs/Cargo.toml
  frontend/appflowy_web_app/src-tauri/Cargo.lock
  frontend/appflowy_web_app/src-tauri/Cargo.toml
  frontend/rust-lib/flowy-core/src/deps_resolve/folder_deps.rs
  frontend/rust-lib/flowy-core/src/deps_resolve/user_deps.rs
  frontend/rust-lib/flowy-core/src/lib.rs
  frontend/rust-lib/flowy-folder/src/entities/workspace.rs
  frontend/rust-lib/flowy-folder/src/manager.rs
  frontend/rust-lib/flowy-folder/src/manager_init.rs
  frontend/rust-lib/flowy-search-pub/src/entities.rs
  frontend/rust-lib/flowy-search/src/folder/indexer.rs
  frontend/rust-lib/flowy-sqlite/src/schema.rs
  frontend/rust-lib/flowy-user-pub/src/workspace_service.rs
  frontend/rust-lib/flowy-user/src/user_manager/manager_user_workspace.rs
Labels: v0.5.9

#5477 fix: use bitsdojo_window on windows
  frontend/appflowy_flutter/lib/startup/tasks/windows.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/appflowy_flutter/windows/runner/main.cpp
Labels: v0.5.9

#5456 Update German translations
  frontend/resources/translations/de-DE.json
Labels: translation, v0.5.9

#5479 chore: disable sync indicator
  frontend/appflowy_flutter/lib/mobile/presentation/base/mobile_view_page.dart
  frontend/appflowy_flutter/lib/plugins/database/tab_bar/tab_bar_view.dart
  frontend/appflowy_flutter/lib/plugins/database_document/database_document_page.dart
  frontend/appflowy_flutter/lib/plugins/document/document.dart
  frontend/appflowy_flutter/lib/plugins/document/document_page.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text.dart
Labels: v0.5.9

#5484 zh-CN translation
  frontend/resources/translations/zh-CN.json
Labels: translation, v0.6.0

#5500 chore: remove build bot
  .github/workflows/build_bot.yaml
Labels: improvements, ci, v0.6.0

#5505 fix: remove member request on launch
  frontend/appflowy_flutter/lib/workspace/application/user/user_workspace_bloc.dart
Labels: v0.6.0

#5499 Update translations for tr_TR
  frontend/resources/translations/tr-TR.json
Labels: translation, v0.6.0

#5248 feat: enable group condition
  frontend/appflowy_flutter/lib/plugins/database/application/field/field_controller.dart
  frontend/appflowy_flutter/lib/plugins/database/application/field/field_info.dart
  frontend/appflowy_flutter/lib/plugins/database/application/setting/group_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/board/application/board_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/domain/group_service.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/group/database_group.dart
  frontend/appflowy_flutter/test/bloc_test/board_test/group_by_date_test.dart
  frontend/resources/translations/en.json
  frontend/rust-lib/event-integration-test/src/database_event.rs
  frontend/rust-lib/event-integration-test/tests/database/local_test/test.rs
  frontend/rust-lib/flowy-database2/src/entities/group_entities/configuration.rs
  frontend/rust-lib/flowy-database2/src/entities/group_entities/group.rs
  frontend/rust-lib/flowy-database2/src/event_handler.rs
  frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
  frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs
  frontend/rust-lib/flowy-database2/src/services/group/controller_impls/date_controller.rs
Labels: v0.5.9

#5513 chore: update editor version
  frontend/appflowy_flutter/android/app/build.gradle
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/appflowy_mobile_toolbar.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
  frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: bug, mobile, v0.6.0

#5517 feat: introduce space to manage the pages
  frontend/appflowy_flutter/integration_test/cloud/workspace/collaborative_workspace_test.dart
  frontend/appflowy_flutter/ios/Podfile.lock
  frontend/appflowy_flutter/lib/core/config/kv_keys.dart
  frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/default_mobile_action_pane.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_folders.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/shared/mobile_view_card.dart
  frontend/appflowy_flutter/lib/mobile/presentation/page_item/mobile_view_item.dart
  frontend/appflowy_flutter/lib/workspace/application/sidebar/space/space_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/view/view_ext.dart
  frontend/appflowy_flutter/lib/workspace/application/workspace/workspace_service.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/header/sidebar_top_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/create_space_popup.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/manage_space_popup.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/shared_widget.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space_header.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/space_action_type.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/space_icon.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/space_icon_popup.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/space_more_popup.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_more_action_button.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text.dart
  frontend/resources/flowy_icons/16x/space_add.svg
  frontend/resources/flowy_icons/16x/space_icon.svg
  frontend/resources/flowy_icons/16x/space_icon_1.svg
  frontend/resources/flowy_icons/16x/space_icon_10.svg
  frontend/resources/flowy_icons/16x/space_icon_11.svg
  frontend/resources/flowy_icons/16x/space_icon_12.svg
  frontend/resources/flowy_icons/16x/space_icon_13.svg
  frontend/resources/flowy_icons/16x/space_icon_14.svg
  frontend/resources/flowy_icons/16x/space_icon_15.svg
  frontend/resources/flowy_icons/16x/space_icon_2.svg
  frontend/resources/flowy_icons/16x/space_icon_3.svg
  frontend/resources/flowy_icons/16x/space_icon_4.svg
  frontend/resources/flowy_icons/16x/space_icon_5.svg
  frontend/resources/flowy_icons/16x/space_icon_6.svg
  frontend/resources/flowy_icons/16x/space_icon_7.svg
  frontend/resources/flowy_icons/16x/space_icon_8.svg
  frontend/resources/flowy_icons/16x/space_icon_9.svg
  frontend/resources/flowy_icons/16x/space_lock.svg
  frontend/resources/flowy_icons/16x/space_manage.svg
  frontend/resources/flowy_icons/16x/space_permission_dropdown.svg
  frontend/resources/flowy_icons/16x/space_permission_private.svg
  frontend/resources/flowy_icons/16x/space_permission_public.svg
  frontend/resources/translations/en.json
Labels: new feature, v0.6.0

#5349 feat: timer field
  frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_field_bottom_sheets.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_full_field_editor.dart
  frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/time_cell_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/application/cell/cell_controller_builder.dart
  frontend/appflowy_flutter/lib/plugins/database/application/cell/cell_data_loader.dart
  frontend/appflowy_flutter/lib/plugins/database/application/field/field_info.dart
  frontend/appflowy_flutter/lib/plugins/database/domain/filter_service.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/application/filter/filter_create_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/application/filter/time_filter_editor_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/time.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/filter_info.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/filter_menu_item.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/card_cell_builder.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/card_cell_skeleton/time_card_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/card_cell_style_maps/desktop_board_card_cell_style.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/card_cell_style_maps/mobile_board_card_cell_style.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_grid/desktop_grid_time_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_row_detail/desktop_row_detail_time_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/editable_cell_builder.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/editable_cell_skeleton/time.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/mobile_grid/mobile_grid_time_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/mobile_row_detail/mobile_row_detail_time_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/field/field_type_list.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/field/type_option_editor/builder.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/field/type_option_editor/time.dart
  frontend/appflowy_flutter/lib/util/field_type_extension.dart
  frontend/appflowy_flutter/lib/util/time.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/test/unit_test/util/time.dart
  frontend/resources/translations/en.json
  frontend/rust-lib/event-integration-test/src/database_event.rs
  frontend/rust-lib/flowy-database2/src/entities/field_entities.rs
  frontend/rust-lib/flowy-database2/src/entities/filter_entities/mod.rs
  frontend/rust-lib/flowy-database2/src/entities/filter_entities/time_filter.rs
  frontend/rust-lib/flowy-database2/src/entities/filter_entities/util.rs
  frontend/rust-lib/flowy-database2/src/entities/macros.rs
  frontend/rust-lib/flowy-database2/src/entities/type_option_entities/mod.rs
  frontend/rust-lib/flowy-database2/src/entities/type_option_entities/time_entities.rs
  frontend/rust-lib/flowy-database2/src/services/cell/cell_operation.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/mod.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/text_type_option/text_type_option.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/time_type_option/mod.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/time_type_option/time.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/time_type_option/time_entities.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/time_type_option/time_filter.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/type_option.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/type_option_cell.rs
  frontend/rust-lib/flowy-database2/src/services/filter/controller.rs
  frontend/rust-lib/flowy-database2/src/services/filter/entities.rs
  frontend/rust-lib/flowy-database2/tests/database/cell_test/test.rs
  frontend/rust-lib/flowy-database2/tests/database/field_test/test.rs
  frontend/rust-lib/flowy-database2/tests/database/field_test/util.rs
  frontend/rust-lib/flowy-database2/tests/database/filter_test/mod.rs
  frontend/rust-lib/flowy-database2/tests/database/filter_test/time_filter_test.rs
  frontend/rust-lib/flowy-database2/tests/database/mock_data/board_mock_data.rs
  frontend/rust-lib/flowy-database2/tests/database/mock_data/grid_mock_data.rs
  frontend/rust-lib/flowy-database2/tests/database/share_test/export_test.rs
Labels: v0.6.0

#5531 Fix space issues
  frontend/appflowy_flutter/lib/workspace/application/favorite/favorite_service.dart
  frontend/appflowy_flutter/lib/workspace/application/recent/cached_recent_service.dart
  frontend/appflowy_flutter/lib/workspace/application/sidebar/space/space_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/view_title/view_title_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/header/sidebar_top_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/create_space_popup.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/manage_space_popup.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space_header.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/space_icon_popup.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/space_more_popup.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/navigation.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/view_title_bar.dart
  frontend/resources/translations/en.json
  frontend/rust-lib/flowy-folder/src/manager.rs
Labels: bug, v0.6.0

#5535 feat: improve view thumbnail
  frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_block_action_widget.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/favorite_folder/favorite_space.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/home_space/home_space.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/recent_folder/recent_space.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/shared/mobile_view_card.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/tab/_tab_bar.dart
  frontend/appflowy_flutter/lib/mobile/presentation/mobile_bottom_navigation_bar.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/collaborator_avater_stack.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/document_collaborators.dart
  frontend/resources/flowy_icons/16x/m_layout.svg
  frontend/resources/flowy_icons/24x/m_board_thumbnail.svg
  frontend/resources/flowy_icons/24x/m_calendar_thumbnail.svg
  frontend/resources/flowy_icons/24x/m_chat_thumbnail.svg
  frontend/resources/flowy_icons/24x/m_document_thumbnail.svg
  frontend/resources/flowy_icons/24x/m_grid_thumbnail.svg
Labels: improvements, v0.6.0

#5538 feat: improve hover color in dark mode
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space_header.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/space_more_popup.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_menu_element.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/more_view_actions/more_view_actions.dart
  frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/default_colorscheme.dart
Labels: improvements, v0.6.0

#5543 feat: improve upgrade space toast
  frontend/appflowy_flutter/lib/mobile/presentation/home/favorite_folder/favorite_space.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/recent_folder/recent_space.dart
  frontend/appflowy_flutter/lib/mobile/presentation/mobile_bottom_navigation_bar.dart
  frontend/appflowy_flutter/lib/workspace/application/sidebar/space/space_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/space_migration.dart
  frontend/resources/flowy_icons/16x/space_arrow_right.svg
  frontend/resources/flowy_icons/16x/upgrade.svg
  frontend/resources/flowy_icons/16x/upgrade_close.svg
  frontend/resources/translations/en.json
Labels: improvements, v0.6.0

#5544 fix: migrate the private views only if they are not empty
  frontend/appflowy_flutter/lib/workspace/application/sidebar/space/space_bloc.dart
Labels: bug, v0.6.0

#5549 feat: improve space UX
  frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/default_mobile_action_pane.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/favorite_folder/favorite_space.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_folders.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/recent_folder/recent_space.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/shared/empty_placeholder.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/shared/mobile_page_card.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/space/mobile_space.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
  frontend/appflowy_flutter/lib/workspace/application/settings/appearance/desktop_appearance.dart
  frontend/appflowy_flutter/lib/workspace/application/sidebar/space/space_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/hotkeys.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/favorites/favorite_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/shared/sidebar_new_page_button.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/create_space_popup.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/shared_widget.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space_header.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/space_action_type.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/space_migration.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_action_type.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/resources/flowy_icons/16x/icon_board.svg
  frontend/resources/flowy_icons/16x/more.svg
  frontend/resources/flowy_icons/16x/space_lock.svg
  frontend/resources/flowy_icons/24x/m_board_thumbnail.svg
  frontend/resources/translations/en.json
Labels: bug, v0.6.0

#5551 chore: turn off the billing feature
  frontend/appflowy_flutter/lib/shared/feature_flags.dart
Labels: v0.6.0

#5553 feat: add a pinned icon after page name
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/favorites/favorite_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
  frontend/resources/flowy_icons/16x/favorite_pin.svg
Labels: improvements, v0.6.0

#5547 fix: settings improvements
  frontend/appflowy_flutter/integration_test/cloud/cloud_runner.dart
  frontend/appflowy_flutter/integration_test/desktop/database/database_row_test.dart
  frontend/appflowy_flutter/integration_test/desktop/settings/settings_billing_test.dart
  frontend/appflowy_flutter/integration_test/desktop/settings/settings_runner.dart
  frontend/appflowy_flutter/integration_test/shared/auth_operation.dart
  frontend/appflowy_flutter/integration_test/shared/database_test_op.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_field_bottom_sheets.dart
  frontend/appflowy_flutter/lib/plugins/database/application/setting/group_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/filter_menu_item.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/card_cell_style_maps/calendar_card_cell_style.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/card_cell_style_maps/desktop_board_card_cell_style.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/card_cell_style_maps/mobile_board_card_cell_style.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/field/field_type_list.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/group/database_group.dart
  frontend/appflowy_flutter/lib/user/application/user_service.dart
  frontend/appflowy_flutter/lib/workspace/application/command_palette/command_palette_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/settings/appearance/desktop_appearance.dart
  frontend/appflowy_flutter/lib/workspace/application/settings/appearance/mobile_appearance.dart
  frontend/appflowy_flutter/lib/workspace/application/settings/plan/settings_plan_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/settings/plan/workspace_subscription_ext.dart
  frontend/appflowy_flutter/lib/workspace/application/settings/workspace/workspace_settings_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/user/user_workspace_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/shared/sidebar_setting.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_account_view.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_billing_view.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_plan_comparison_dialog.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_plan_view.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_workspace_view.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/settings_dialog.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/shared/flowy_gradient_button.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/shared/settings_dropdown.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/shared/settings_input_field.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/members/workspace_member_page.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/setting_appflowy_cloud.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_menu.dart
  frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/colorscheme.dart
  frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/dandelion.dart
  frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/default_colorscheme.dart
  frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/lavender.dart
  frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/lemonade.dart
  frontend/appflowy_flutter/packages/flowy_infra/lib/theme_extension.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/widget/flowy_tooltip.dart
  frontend/resources/flowy_icons/24x/check.svg
  frontend/resources/translations/en.json
  frontend/rust-lib/event-integration-test/src/folder_event.rs
  frontend/rust-lib/flowy-core/src/deps_resolve/search_deps.rs
  frontend/rust-lib/flowy-server/src/af_cloud/impls/user/cloud_service_impl.rs
  frontend/rust-lib/flowy-user-pub/src/cloud.rs
  frontend/rust-lib/flowy-user/src/event_handler.rs
  frontend/rust-lib/flowy-user/src/event_map.rs
  frontend/rust-lib/flowy-user/src/user_manager/manager_user_workspace.rs
Labels: v0.6.0

#5555 chore: change slash menu hover color
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
Labels: improvements, v0.6.0

#5565 fix: cursor jump randomly in check list item
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_row_detail/desktop_row_detail_checklist_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/checklist_cell_editor.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/checklist_cell_textfield.dart
Labels: bug, v0.6.0

#5571 chore: bump version 0.6.0
  CHANGELOG.md
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.6.0

#5574 fix: cursor height is inconsistent after upgrading to Flutter 3.22
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/appflowy_mobile_toolbar.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/keyboard_height_observer.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: bug, v0.6.0

#5586 fix: duplicated spaces could be created when migrating
  frontend/Makefile.toml
  frontend/appflowy_flutter/lib/mobile/presentation/home/space/mobile_space.dart
  frontend/appflowy_flutter/lib/mobile/presentation/mobile_bottom_navigation_bar.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/appflowy_mobile_toolbar.dart
  frontend/appflowy_flutter/lib/workspace/application/sidebar/space/space_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/view/view_service.dart
  frontend/appflowy_flutter/lib/workspace/application/workspace/workspace_service.dart
  frontend/appflowy_flutter/packages/flowy_infra/lib/uuid.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/rust-lib/event-integration-test/src/chat_event.rs
  frontend/rust-lib/event-integration-test/src/database_event.rs
  frontend/rust-lib/event-integration-test/src/document/document_event.rs
  frontend/rust-lib/event-integration-test/src/document_event.rs
  frontend/rust-lib/event-integration-test/src/folder_event.rs
  frontend/rust-lib/event-integration-test/tests/folder/local_test/script.rs
  frontend/rust-lib/flowy-folder/src/entities/view.rs
  frontend/scripts/linux_distribution/appimage/AppImageBuilder.yml
Labels: v0.6.1

#5612 feat: duplicate space
  frontend/Makefile.toml
  frontend/appflowy_flutter/lib/mobile/presentation/home/space/mobile_space.dart
  frontend/appflowy_flutter/lib/mobile/presentation/mobile_bottom_navigation_bar.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/appflowy_mobile_toolbar.dart
  frontend/appflowy_flutter/lib/workspace/application/sidebar/space/space_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/view/view_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/view/view_service.dart
  frontend/appflowy_flutter/lib/workspace/application/workspace/workspace_service.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space_header.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/space_action_type.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/space_more_popup.dart
  frontend/appflowy_flutter/packages/flowy_infra/lib/uuid.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/appflowy_tauri/src-tauri/Cargo.lock
  frontend/appflowy_tauri/src-tauri/Cargo.toml
  frontend/appflowy_web/wasm-libs/Cargo.toml
  frontend/appflowy_web_app/src-tauri/Cargo.lock
  frontend/appflowy_web_app/src-tauri/Cargo.toml
  frontend/resources/translations/en.json
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
  frontend/rust-lib/event-integration-test/src/chat_event.rs
  frontend/rust-lib/event-integration-test/src/database_event.rs
  frontend/rust-lib/event-integration-test/src/document/document_event.rs
  frontend/rust-lib/event-integration-test/src/document_event.rs
  frontend/rust-lib/event-integration-test/src/folder_event.rs
  frontend/rust-lib/event-integration-test/tests/folder/local_test/script.rs
  frontend/rust-lib/flowy-folder/src/entities/view.rs
  frontend/rust-lib/flowy-folder/src/event_handler.rs
  frontend/rust-lib/flowy-folder/src/event_map.rs
  frontend/rust-lib/flowy-folder/src/manager.rs
  frontend/rust-lib/flowy-folder/src/test_helper.rs
  frontend/rust-lib/flowy-folder/src/view_operation.rs
  frontend/scripts/linux_distribution/appimage/AppImageBuilder.yml
Labels: v0.6.2

#5618 feat: support moving page across spaces
  frontend/appflowy_flutter/lib/workspace/application/sidebar/folder/folder_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/sidebar/space/space_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/sidebar/space/space_search_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/favorites/favorite_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/move_to/move_page_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/shared_widget.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space_header.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_more_action_button.dart
  frontend/resources/flowy_icons/16x/magnifier.svg
Labels: v0.6.2

#5619 fix: prevent overfow of space name and view name
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/shared_widget.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space_header.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
Labels: bug, v0.6.2

#5585 chore: set document id
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_paste_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/paste_from_image.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/document_header_node_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/image_placeholder.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/image_util.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/auto_completion_node_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/page_style/_page_style_cover_image.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/page_style/page_style_bottom_sheet.dart
  frontend/rust-lib/event-integration-test/tests/chat/ai_tool_test.rs
  frontend/rust-lib/flowy-document/src/event_handler.rs
Labels: improvements, v0.6.2

#5628 feat: add key + as zoom-in key
  frontend/appflowy_flutter/lib/workspace/presentation/home/hotkeys.dart
Labels: bug, v0.6.2

#5627 feat: support creating database at the first level
  frontend/appflowy_flutter/lib/mobile/presentation/home/space/mobile_space.dart
  frontend/appflowy_flutter/lib/workspace/application/sidebar/space/space_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/desktop_home_screen.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/import/import_panel.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/shared/sidebar_new_page_button.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space_header.dart
Labels: v0.6.2

#5598 fix: fill field_settings on creating linked view
  frontend/rust-lib/flowy-core/src/deps_resolve/folder_deps.rs
  frontend/rust-lib/flowy-database2/src/manager.rs
  frontend/rust-lib/flowy-database2/src/services/database_view/layout_deps.rs
  frontend/rust-lib/flowy-folder/src/manager.rs
  frontend/rust-lib/flowy-folder/src/view_operation.rs
Labels: v0.6.2

#5637 chore: bump version 0.6.2
  CHANGELOG.md
  frontend/Makefile.toml
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.6.2

#5638 feat: open the duplicated space by default
  frontend/appflowy_flutter/lib/workspace/application/sidebar/space/space_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/view/view_service.dart
  frontend/rust-lib/flowy-folder/src/entities/view.rs
  frontend/rust-lib/flowy-folder/src/manager.rs
Labels: v0.6.2

#5648 fix: postpone fetching member
  frontend/appflowy_flutter/lib/workspace/application/user/user_workspace_bloc.dart
Labels: v0.6.2
