Repository AppFlowy-IO/AppFlowy, pull requests merged in 2024-12, with the labels that each got.

#6895 fix(mobile): lost initial scroll position on welcome page
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_welcome_page.dart
Labels: v0.7.6

#6900 fix: mobile camera android permission
  frontend/appflowy_flutter/android/app/src/main/AndroidManifest.xml
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/add_attachment_item.dart
Labels: v0.7.6

#6899 fix: tabs lr 0.7.6
  frontend/appflowy_flutter/integration_test/desktop/uncategorized/tabs_test.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/chat.dart
  frontend/appflowy_flutter/lib/plugins/blank/blank.dart
  frontend/appflowy_flutter/lib/plugins/database/tab_bar/tab_bar_view.dart
  frontend/appflowy_flutter/lib/plugins/database_document/database_document_plugin.dart
  frontend/appflowy_flutter/lib/plugins/document/document.dart
  frontend/appflowy_flutter/lib/plugins/trash/trash.dart
  frontend/appflowy_flutter/lib/workspace/application/tabs/tabs_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/home_stack.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/navigation.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/tabs/flowy_tab.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/tabs/tabs_manager.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/tab_bar_item.dart
  frontend/resources/translations/en.json
Labels: v0.7.6

#6898 Update translations
  frontend/resources/translations/th-TH.json
Labels: v0.7.6

#6871 feat: simple table issues
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_simple_table_test.dart
  frontend/appflowy_flutter/integration_test/desktop/uncategorized/import_files_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_list.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_option_cubit.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/option_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_copy_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_cut_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/keyboard_interceptor/keyboard_interceptor.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/util/ask_ai_node_extension.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/markdown_parsers.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/markdown_simple_table_parser.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/simple_table_parser.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/plugins.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/shortcuts/command_shortcuts.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/_shared_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_cell_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_constants.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_more_action.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_content_operation.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_delete_operation.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_duplicate_operation.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_header_operation.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_insert_operation.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_map_operation.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_node_extension.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_operations.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_style_operation.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_row_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_shortcuts/simple_table_arrow_down_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_shortcuts/simple_table_arrow_left_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_shortcuts/simple_table_arrow_right_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_shortcuts/simple_table_arrow_up_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_shortcuts/simple_table_backspace_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_shortcuts/simple_table_command_extension.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_shortcuts/simple_table_commands.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_shortcuts/simple_table_select_all_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_shortcuts/simple_table_tab_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/table/shortcuts/simple_table_commands.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/table/table_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/table/table_operations/table_operations.dart
  frontend/appflowy_flutter/lib/shared/markdown_to_document.dart
  frontend/appflowy_flutter/lib/workspace/application/export/document_exporter.dart
  frontend/appflowy_flutter/packages/flowy_infra/lib/theme_extension.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/appflowy_flutter/test/unit_test/simple_table/simple_table_contente_operation_test.dart
  frontend/appflowy_flutter/test/unit_test/simple_table/simple_table_delete_operation_test.dart
  frontend/appflowy_flutter/test/unit_test/simple_table/simple_table_duplicate_operation_test.dart
  frontend/appflowy_flutter/test/unit_test/simple_table/simple_table_header_operation_test.dart
  frontend/appflowy_flutter/test/unit_test/simple_table/simple_table_insert_operation_test.dart
  frontend/appflowy_flutter/test/unit_test/simple_table/simple_table_markdown_test.dart
  frontend/appflowy_flutter/test/unit_test/simple_table/simple_table_style_operation_test.dart
  frontend/appflowy_flutter/test/unit_test/simple_table/simple_table_test_helper.dart
Labels: v0.7.6

#6906 chore: remove rename dialog logic
  frontend/appflowy_flutter/lib/core/config/kv_keys.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/folder/_section_folder.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/shared/rename_view_dialog.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/shared/sidebar_new_page_button.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
Labels: v0.7.6

#6909 fix: pressing enter on a collapsible list toggle adds an additional new line
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_list.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/_shared_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_constants.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_node_extension.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toggle/toggle_block_shortcuts.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/appflowy_flutter/test/unit_test/document/shortcuts/toggle_list_shortcut_test.dart
  frontend/scripts/code_generation/language_files/generate_language_files.cmd
Labels: v0.7.6

#6896 feat: revamp mention page interactions in AI chat
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/ai_prompt_input_bloc.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_entity.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_input_action_bloc.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_input_action_control.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_input_control_cubit.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_message_service.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/chat_input_file.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/chat_input_span.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/chat_mention_page_menu.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/desktop_ai_prompt_input.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/mobile_ai_prompt_input.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input_action_menu.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_text_message.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/loading_indicator.dart
Labels: v0.7.7

#6897 fix(desktop): resize sidebar menu regression
  frontend/appflowy_flutter/lib/workspace/application/home/home_setting_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/home_layout.dart
  frontend/appflowy_flutter/packages/flowy_infra/lib/size.dart
Labels: v0.7.7

#6917 feat: open ai response url source in browser
  frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_metadata.dart
Labels: v0.7.7

#6920 fix: initial ai chat load
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_bloc.dart
Labels: v0.7.7

#6912 feat: support column and row reordering in tables
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/text_robot.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/_shared_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_cell_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_constants.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_more_action.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_map_operation.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_node_extension.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_operations.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_reorder_operation.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_border_builder.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_column_resize_handle.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_reorder_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_widget.dart
  frontend/appflowy_flutter/test/unit_test/simple_table/simple_table_reorder_operation_test.dart
  frontend/appflowy_flutter/test/unit_test/simple_table/simple_table_test_helper.dart
Labels: v0.7.8

#6927 fix: unable to open local file using afLaunchUrl function
  frontend/appflowy_flutter/lib/core/helpers/url_launcher.dart
  frontend/appflowy_flutter/lib/mobile/presentation/base/view_page/more_bottom_sheet.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_grid/desktop_grid_media_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_row_detail/desktop_row_detail_media_cell.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/file/file_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/file/file_util.dart
  frontend/appflowy_flutter/lib/shared/patterns/common_patterns.dart
  frontend/appflowy_flutter/lib/user/application/auth/af_cloud_auth_service.dart
  frontend/appflowy_flutter/lib/util/share_log_files.dart
  frontend/appflowy_flutter/lib/workspace/application/settings/ai/plugin_state_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_manage_data_view.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/theme_upload/theme_upload_learn_more_button.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/image_viewer/interactive_image_toolbar.dart
  frontend/appflowy_flutter/test/unit_test/url_launcher/url_launcher_test.dart
  frontend/resources/translations/en.json
Labels: v0.7.7, v0.7.8

#6930 feat(flutter_desktop): AI chat refer to UI
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_side_panel_bloc.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/chat.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_side_panel.dart
  frontend/appflowy_flutter/lib/workspace/application/tabs/tabs_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/home_stack.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/tabs/tabs_manager.dart
Labels: v0.7.8

#6933 fix(flutter): implement mention date transaction handler
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_date_reminder_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/child_page_transaction_handler.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/date_transaction_handler.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_block.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/sub_page/sub_page_transaction_handler.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/transaction_handler/editor_transaction_handler.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/transaction_handler/editor_transaction_service.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/transaction_handler/mention_transaction_handler.dart
Labels: v0.7.7

#6620 feat: add same delete design in database
  frontend/appflowy_flutter/lib/plugins/database/widgets/field/field_editor.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/button.dart
Labels: v0.7.7

#6949 fix(flutter_desktop): clicking on empty space when editing a cell sho…
  frontend/appflowy_flutter/integration_test/desktop/database/database_calendar_test.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_row_detail/desktop_row_detail_date_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_row_detail/desktop_row_detail_media_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_row_detail/desktop_row_detail_relation_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_row_detail/desktop_row_detail_select_option_cell.dart
Labels: v0.7.7

#6948 fix: hotfix issues for v0.7.7
  frontend/appflowy_flutter/integration_test/desktop/document/document_inline_sub_page_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/page_reference_commands.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/document_markdown_parsers.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/file_block_node_parser.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/link_preview_node_parser.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/markdown_parsers.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/simple_table_node_parser.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/plugins.dart
  frontend/appflowy_flutter/lib/plugins/inline_actions/inline_actions_menu.dart
  frontend/appflowy_flutter/lib/plugins/inline_actions/widgets/inline_actions_handler.dart
  frontend/appflowy_flutter/lib/plugins/shared/share/share_bloc.dart
  frontend/appflowy_flutter/lib/shared/markdown_to_document.dart
  frontend/appflowy_flutter/lib/workspace/application/sidebar/billing/sidebar_plan_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/sidebar/space/space_bloc.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/appflowy_flutter/test/unit_test/markdown/markdown_parser_test.dart
Labels: v0.7.7

#6946 feat(flutter_mobile): improve appearance of mention page selector
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/chat_mention_page_bottom_sheet.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/chat_mention_page_menu.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/mobile_ai_prompt_input.dart
Labels: v0.7.8

#6931 feat: support multiple lines in table cell
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_simple_table_test.dart
  frontend/appflowy_flutter/lib/plugins/document/application/document_validator.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/text_robot.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/numbered_list/numbered_list_icon.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/shortcuts/character_shortcuts.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/shortcuts/command_shortcuts.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/_shared_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_constants.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_delete_operation.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_insert_operation.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_node_extension.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_shortcuts/simple_table_backspace_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_shortcuts/simple_table_commands.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_shortcuts/simple_table_enter_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_add_column_and_row_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_add_column_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_add_row_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_column_resize_handle.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_widget.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.7.8

#6958 feat: support multiple blocks operation
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_image_block_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_option_cubit.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/draggable_option_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/option/color_option_action.dart
  frontend/appflowy_flutter/test/unit_test/document/option_menu/block_action_option_cubit_test.dart
Labels: v0.7.8

#6956 feat: set table to page width
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_simple_table_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/_shared_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_cell_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_constants.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_more_action.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_node_extension.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_style_operation.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_row_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_align_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_background_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_basic_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_border_builder.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_divider.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_reorder_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/widgets.dart
  frontend/resources/flowy_icons/16x/table_clear_content.svg
  frontend/resources/flowy_icons/16x/table_distribute_columns_evenly.svg
  frontend/resources/flowy_icons/16x/table_insert_above.svg
  frontend/resources/flowy_icons/16x/table_insert_below.svg
  frontend/resources/flowy_icons/16x/table_insert_left.svg
  frontend/resources/flowy_icons/16x/table_insert_right.svg
  frontend/resources/flowy_icons/16x/table_set_to_page_width.svg
  frontend/resources/translations/en.json
Labels: v0.7.8

#6925 feat: shrinkWrap grid in document
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_database_test.dart
  frontend/appflowy_flutter/lib/plugins/database/board/presentation/board_page.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/application/grid_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/grid_page.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/footer/grid_footer.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/row/row.dart
  frontend/appflowy_flutter/lib/plugins/database/tab_bar/tab_bar_view.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/built_in_page_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/database/database_view_block_component.dart
  frontend/appflowy_flutter/lib/workspace/application/view/view_ext.dart
  frontend/resources/flowy_icons/16x/load_more.svg
  frontend/resources/translations/en.json
Labels: v0.7.8

#6789 fix: rename untitled view
  frontend/appflowy_flutter/integration_test/desktop/cloud/cloud_runner.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/sidebar/sidebar_rename_untitled_test.dart
  frontend/appflowy_flutter/integration_test/shared/common_operations.dart
  frontend/appflowy_flutter/lib/plugins/database/tab_bar/desktop/tab_bar_header.dart
  frontend/appflowy_flutter/lib/plugins/database/tab_bar/mobile/mobile_tab_bar_header.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/favorites/favorite_more_actions.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
Labels: v0.7.8

#6964 feat: able to select language for the code block by arrow keys (#6905)
  frontend/appflowy_flutter/integration_test/desktop/uncategorized/code_block_language_selector_test.dart
  frontend/appflowy_flutter/integration_test/desktop_runner_9.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/selectable_item_list_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/code_block/code_block_language_selector.dart
Labels: v0.7.8

#6973 feat: support universal link / app link on mobile
  frontend/appflowy_flutter/android/app/src/main/AndroidManifest.xml
  frontend/appflowy_flutter/ios/Runner/Runner.entitlements
Labels: v0.7.8

#6976 fix(flutter_desktop): cannot copy ai response with ctrl c
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_markdown_text.dart
Labels: v0.7.8

#6978 chore: bump version 0.7.8
  frontend/Makefile.toml
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.7.8

#6983 fix: launch review issues 0.7.8
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_input_control_cubit.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/chat_mention_page_bottom_sheet.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/chat_mention_page_menu.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/desktop_ai_prompt_input.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/mobile_ai_prompt_input.dart
  frontend/appflowy_flutter/lib/workspace/application/view_title/view_title_bar_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/view_title_bar.dart
Labels: v0.7.8

#6982 fix: AI chat initial rag_ids
  frontend/rust-lib/flowy-core/src/deps_resolve/chat_deps.rs
  frontend/rust-lib/flowy-core/src/deps_resolve/folder_deps.rs
  frontend/rust-lib/flowy-folder-pub/src/query.rs
  frontend/rust-lib/flowy-folder/src/manager.rs
Labels: v0.7.8

#6992 fix: inline grid launch review
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/grid_page.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/header/grid_header.dart
Labels: v0.7.8

#6985 fix: simple table issues
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_image_block_test.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_inline_math_equation_test.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_inline_page_test.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_simple_table_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_option_cubit.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/draggable_option_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/util.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/visual_drag_area.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/option/option_actions.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/numbered_list/numbered_list_icon.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/shortcuts/command_shortcuts.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_cell_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_more_action.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_map_operation.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_node_extension.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_style_operation.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_row_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_shortcuts/simple_table_backspace_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_shortcuts/simple_table_command_extension.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_shortcuts/simple_table_enter_command.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.7.8

#6994 chore: filter out spaces from mention page
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_input_control_cubit.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/mobile_ai_prompt_input.dart
Labels: v0.7.8

#6997 feat: support readonly table
  frontend/appflowy_flutter/android/app/src/main/AndroidManifest.xml
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/paste_from_image.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/inline_math_equation/inline_math_equation.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_cell_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_border_builder.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/image_viewer/image_provider.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/image_viewer/interactive_image_toolbar.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.7.8

#7000 chore: bump version 0.7.8
  .github/workflows/android_ci.yaml.bak
  .github/workflows/ios_ci.yaml
  .github/workflows/release.yml
  .github/workflows/rust_coverage.yml
  .github/workflows/tauri_ci.yaml
  .github/workflows/tauri_release.yml
  CHANGELOG.md
  codemagic.yaml
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/scripts/docker-buildfiles/Dockerfile
  frontend/scripts/install_dev_env/install_ios.sh
  frontend/scripts/install_dev_env/install_linux.sh
  frontend/scripts/install_dev_env/install_macos.sh
  frontend/scripts/install_dev_env/install_windows.sh
  frontend/scripts/makefile/env.toml
Labels: v0.7.8

#6975 feat: select sources for ai prompt
  frontend/appflowy_flutter/lib/mobile/presentation/base/mobile_view_page.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_bloc.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_select_sources_cubit.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/desktop_ai_prompt_input.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/mobile_ai_prompt_input.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/select_sources_bottom_sheet.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/select_sources_menu.dart
  frontend/resources/flowy_icons/16x/ai_source_drop_down.svg
  frontend/resources/flowy_icons/16x/check_partial.svg
  frontend/resources/translations/en.json
  frontend/rust-lib/flowy-ai/src/ai_manager.rs
  frontend/rust-lib/flowy-ai/src/entities.rs
  frontend/rust-lib/flowy-ai/src/event_handler.rs
  frontend/rust-lib/flowy-ai/src/event_map.rs
Labels: v0.7.9

#7009 fix: the index error when deleting text and then using the up or down arrow key
  frontend/appflowy_flutter/integration_test/desktop/uncategorized/code_block_language_selector_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/selectable_item_list_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/code_block/code_block_language_selector.dart
Labels: v0.7.9

#6783 feat: use new api to get the workspace member role
  frontend/appflowy_flutter/lib/workspace/application/settings/ai/local_ai_on_boarding_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/settings/ai/settings_ai_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/settings/settings_dialog_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/user/user_workspace_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/footer/sidebar_toast.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/space_more_popup.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/setting_ai_view/settings_ai_view.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_workspace_view.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/sites/domain/domain_item.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/sites/domain/domain_more_action.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/settings_dialog.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_menu.dart
  frontend/rust-lib/flowy-ai-pub/Cargo.toml
  frontend/rust-lib/flowy-server/src/af_cloud/impls/user/cloud_service_impl.rs
  frontend/rust-lib/flowy-server/src/local_server/impls/user.rs
  frontend/rust-lib/flowy-sqlite/migrations/2024-12-12-102351_workspace_role/down.sql
  frontend/rust-lib/flowy-sqlite/migrations/2024-12-12-102351_workspace_role/up.sql
  frontend/rust-lib/flowy-sqlite/src/schema.rs
  frontend/rust-lib/flowy-user-pub/src/entities.rs
  frontend/rust-lib/flowy-user-pub/src/session.rs
  frontend/rust-lib/flowy-user/src/entities/user_profile.rs
  frontend/rust-lib/flowy-user/src/entities/workspace.rs
  frontend/rust-lib/flowy-user/src/services/sqlite_sql/workspace_sql.rs
  frontend/rust-lib/flowy-user/src/user_manager/manager_user_workspace.rs
Labels: v0.7.9

#7018 chore: regenerate response improvements
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_bloc.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/desktop_ai_prompt_input.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/mobile_ai_prompt_input.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_text_message.dart
Labels: v0.7.9

#7017 Update translations
  frontend/resources/translations/ar-SA.json
  frontend/resources/translations/fr-FR.json
Labels: v0.7.9

#7028 fix: update rag_ids not saving to local store
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/desktop_ai_prompt_input.dart
  frontend/rust-lib/flowy-ai/src/ai_manager.rs
Labels: v0.7.9

#7036 feat: reordering table columns and rows on mobile
  frontend/appflowy_flutter/integration_test/mobile/document/document_test_runner.dart
  frontend/appflowy_flutter/integration_test/mobile/document/simple_table_test.dart
  frontend/appflowy_flutter/integration_test/shared/common_operations.dart
  frontend/appflowy_flutter/lib/mobile/presentation/notifications/widgets/shared.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_cell_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_constants.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_more_action.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_action_sheet.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_border_builder.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_feedback.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_reorder_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
Labels: v0.7.9

#7034 feat: support table align on desktop
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_simple_table_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/option/align_option_action.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/option/option_actions.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_cell_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_node_extension.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_style_operation.dart
  frontend/appflowy_flutter/test/unit_test/simple_table/simple_table_style_operation_test.dart
Labels: v0.7.9

#7035 fix: do not wrap the inline math equation in a new line
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_inline_math_equation_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/inline_math_equation/inline_math_equation.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
Labels: v0.7.9

#6615 fix: calculation UI refresh
  frontend/appflowy_tauri/src-tauri/Cargo.lock
  frontend/appflowy_tauri/src-tauri/Cargo.toml
  frontend/appflowy_web_app/src-tauri/Cargo.lock
  frontend/appflowy_web_app/src-tauri/Cargo.toml
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
  frontend/rust-lib/event-integration-test/src/database_event.rs
  frontend/rust-lib/event-integration-test/tests/asset/project.csv
  frontend/rust-lib/event-integration-test/tests/database/local_test/calculate_test.rs
  frontend/rust-lib/event-integration-test/tests/document/af_cloud_test/edit_test.rs
  frontend/rust-lib/event-integration-test/tests/folder/local_test/import_test.rs
  frontend/rust-lib/event-integration-test/tests/folder/local_test/publish_database_test.rs
  frontend/rust-lib/event-integration-test/tests/user/af_cloud_test/anon_user_test.rs
  frontend/rust-lib/event-integration-test/tests/user/af_cloud_test/import_af_data_folder_test.rs
  frontend/rust-lib/event-integration-test/tests/user/local_test/import_af_data_local_test.rs
  frontend/rust-lib/event-integration-test/tests/user/migration_test/document_test.rs
  frontend/rust-lib/event-integration-test/tests/user/migration_test/version_test.rs
  frontend/rust-lib/event-integration-test/tests/util.rs
  frontend/rust-lib/flowy-core/src/deps_resolve/folder_deps.rs
  frontend/rust-lib/flowy-database2/src/event_handler.rs
  frontend/rust-lib/flowy-database2/src/manager.rs
  frontend/rust-lib/flowy-database2/src/services/calculations/controller.rs
  frontend/rust-lib/flowy-database2/src/services/calculations/service.rs
  frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
  frontend/rust-lib/flowy-database2/src/services/database_view/notifier.rs
  frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/number_type_option/number_type_option.rs
  frontend/rust-lib/flowy-database2/src/services/sort/entities.rs
  frontend/rust-lib/flowy-database2/tests/database/calculations_test/calculation_test.rs
  frontend/rust-lib/flowy-database2/tests/database/calculations_test/script.rs
  frontend/rust-lib/flowy-document/src/manager.rs
Labels: v0.7.5

#7038 feat: refactor slash menu items to support showing in table cell
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_simple_table_test.dart
  frontend/appflowy_flutter/integration_test/mobile/document/simple_table_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/file/file_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/custom_image_block_component/image_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/math_equation/math_equation_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_date_block.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_page_block.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/slash_menu_items.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/plugins.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/shortcuts/character_shortcuts.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_cell_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_node_extension.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_feedback.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items/ai_writer_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items/bulleted_list_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items/callout_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items/code_block_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items/database_items.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items/date_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items/divider_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items/emoji_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items/file_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items/heading_items.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items/image_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items/math_equation_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items/numbered_list_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items/outline_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items/paragraph_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items/photo_gallery_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items/quote_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items/simple_table_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items/slash_menu_item_builder.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items/slash_menu_items.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items/sub_page_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items/todo_list_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items/toggle_list_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items_builder.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toggle/toggle_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.7.9

#7015 feat: support recent section in icon picker
  frontend/appflowy_flutter/integration_test/desktop/database/database_row_page_test.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_cover_image_test.dart
  frontend/appflowy_flutter/integration_test/desktop/sidebar/sidebar_icon_test.dart
  frontend/appflowy_flutter/lib/core/config/kv_keys.dart
  frontend/appflowy_flutter/lib/plugins/base/emoji/emoji_picker.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/icon/icon_selector.dart
  frontend/appflowy_flutter/lib/shared/icon_emoji_picker/emoji_search_bar.dart
  frontend/appflowy_flutter/lib/shared/icon_emoji_picker/flowy_icon_emoji_picker.dart
  frontend/appflowy_flutter/lib/shared/icon_emoji_picker/icon.dart
  frontend/appflowy_flutter/lib/shared/icon_emoji_picker/icon_picker.dart
  frontend/appflowy_flutter/lib/shared/icon_emoji_picker/recent_icons.dart
  frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/appflowy_flutter/test/unit_test/util/recent_icons_test.dart
Labels: v0.7.9

#6991 feat: drag view into document to link to view
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_drop_handler.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/draggable_view_item.dart
Labels: v0.7.9

#7048 feat: support plus menu in table cell on mobile
  frontend/appflowy_flutter/integration_test/mobile/document/simple_table_test.dart
  frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_view_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/file/file_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/add_block_menu_item_builder.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/add_block_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_cell_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_action_sheet.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_feedback.dart
Labels: v0.7.9

#7055 fix(flutter_desktop): row detail checklist cell "create new" text field doesn't clear after clicking on create button
  frontend/appflowy_flutter/integration_test/desktop/database/database_row_page_test.dart
  frontend/appflowy_flutter/integration_test/shared/database_test_op.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_row_detail/desktop_row_detail_checklist_cell.dart
Labels: v0.7.9

#7041 feat: add ai message content to document page
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_edit_document_service.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_select_sources_cubit.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/desktop_ai_prompt_input.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/mobile_ai_prompt_input.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/select_sources_bottom_sheet.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/select_sources_menu.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_message_action_bar.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_message_bubble.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/message_util.dart
  frontend/appflowy_flutter/lib/plugins/document/application/document_bloc.dart
  frontend/appflowy_flutter/lib/plugins/document/application/editor_transaction_adapter.dart
  frontend/appflowy_flutter/test/unit_test/editor/transaction_adapter_test.dart
  frontend/resources/flowy_icons/16x/ai_add_to_page.svg
  frontend/resources/translations/en.json
Labels: v0.7.9

#7045 feat: add option to paste plain text
  frontend/appflowy_flutter/integration_test/desktop/document/document_copy_and_paste_test.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_find_menu_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/context_menu/custom_context_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_paste_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/paste_from_plain_text.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/shortcuts/command_shortcuts.dart
  frontend/resources/translations/en.json
Labels: v0.7.9

#7056 chore: bump version 0.7.9
  CHANGELOG.md
  frontend/Makefile.toml
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_image_block_test.dart
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.7.9

#7058 Fix build issue
  .github/workflows/release.yml
  .github/workflows/rust_coverage.yml
  .github/workflows/tauri_ci.yaml
  .github/workflows/tauri_release.yml
Labels: v0.7.9

#7084 fix: try to fix message regeneration being appended instead of replaced
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_bloc.dart
Labels: v0.7.9

#7083 chore(flutter_desktop): adjust toast style
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/error_text_message.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/dialogs.dart
  frontend/resources/flowy_icons/16x/toast_checked_filled.svg
  frontend/resources/flowy_icons/16x/toast_close.svg
  frontend/resources/flowy_icons/16x/toast_error_filled.svg
  frontend/resources/flowy_icons/16x/toast_warning_filled.svg
  frontend/resources/flowy_icons/16x/warning_filled.svg
Labels: v0.7.9

#7063 fix: issues related to the emoji icon picker
  frontend/appflowy_flutter/integration_test/desktop/database/database_calendar_test.dart
  frontend/appflowy_flutter/integration_test/desktop/database/database_field_test.dart
  frontend/appflowy_flutter/integration_test/desktop/sidebar/sidebar_view_item_test.dart
  frontend/appflowy_flutter/lib/plugins/base/emoji/emoji_picker.dart
  frontend/appflowy_flutter/lib/plugins/base/emoji/emoji_picker_screen.dart
  frontend/appflowy_flutter/lib/plugins/database_document/presentation/database_document_title.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/emoji_picker_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/cover/document_immersive_cover.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/document_cover_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/emoji_icon_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/page_style/_page_style_icon.dart
  frontend/appflowy_flutter/lib/shared/icon_emoji_picker/emoji_search_bar.dart
  frontend/appflowy_flutter/lib/shared/icon_emoji_picker/flowy_icon_emoji_picker.dart
  frontend/appflowy_flutter/lib/shared/icon_emoji_picker/icon_picker.dart
  frontend/appflowy_flutter/lib/shared/icon_emoji_picker/icon_search_bar.dart
  frontend/appflowy_flutter/lib/shared/icon_emoji_picker/tab.dart
  frontend/appflowy_flutter/lib/startup/tasks/generate_router.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_icon.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_more_action_button.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/sites/publish_info_view_item.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/emoji_picker/emoji_menu_item.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/rename_view_popover.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.7.9

#7060 fix: toolbar menu not showing beacase keyboard height is not updated in time
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/appflowy_mobile_toolbar.dart
Labels: v0.7.9

#7086 chore: add toast messages for ai chat interactions
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_message_action_bar.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_metadata.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/message_util.dart
  frontend/resources/translations/en.json
Labels: v0.7.9

#7091 fix(flutter_desktop): workspace menu ui issues
  frontend/appflowy_flutter/integration_test/desktop/cloud/workspace/collaborative_workspace_test.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_actions.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/sidebar_workspace.dart
Labels: v0.7.9

#6368 delete previous image on cover change
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_cover_image_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/document_cover_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/image_util.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/migration/editor_migration.dart
Labels: v0.8.0

#7097 chore: complete the test code for #7060
  frontend/appflowy_flutter/integration_test/mobile/document/document_test_runner.dart
  frontend/appflowy_flutter/integration_test/mobile/document/toolbar_test.dart
Labels: tests, v0.8.0

#7099 Update translations
  frontend/resources/translations/ar-SA.json
  frontend/resources/translations/ca-ES.json
  frontend/resources/translations/ckb-KU.json
  frontend/resources/translations/cs-CZ.json
  frontend/resources/translations/de-DE.json
  frontend/resources/translations/es-VE.json
  frontend/resources/translations/eu-ES.json
  frontend/resources/translations/fa.json
  frontend/resources/translations/fr-CA.json
  frontend/resources/translations/fr-FR.json
  frontend/resources/translations/he.json
  frontend/resources/translations/hu-HU.json
  frontend/resources/translations/id-ID.json
  frontend/resources/translations/it-IT.json
  frontend/resources/translations/ko-KR.json
  frontend/resources/translations/pl-PL.json
  frontend/resources/translations/pt-BR.json
  frontend/resources/translations/pt-PT.json
  frontend/resources/translations/ru-RU.json
  frontend/resources/translations/sv-SE.json
  frontend/resources/translations/tr-TR.json
  frontend/resources/translations/uk-UA.json
  frontend/resources/translations/vi-VN.json
  frontend/resources/translations/vi.json
  frontend/resources/translations/zh-CN.json
  frontend/resources/translations/zh-TW.json
Labels: translation, v0.8.0

#3645 Updated, fixed and filled most of the spanish chapter for the translation of AppFlowy
  frontend/resources/translations/es-VE.json
Labels: translation, v0.8.0

#6769 feat: i18n for duplicated field names
  frontend/appflowy_flutter/lib/workspace/application/view/view_bloc.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/resources/translations/en.json
Labels: v0.8.0

#7115 fix: simple table issues on mobile
  frontend/appflowy_flutter/integration_test/mobile/document/simple_table_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_constants.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_style_operation.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/_desktop_simple_table_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/_mobile_simple_table_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/_simple_table_bottom_sheet_actions.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/appflowy_flutter/test/unit_test/simple_table/simple_table_style_operation_test.dart
Labels: v0.8.0
