Repository AppFlowy-IO/AppFlowy, pull requests merged in 2024-04, with the labels that each got.

#5023 fix: duplicated selections from remote
  frontend/appflowy_flutter/lib/plugins/document/application/doc_collab_adapter.dart
  frontend/appflowy_flutter/lib/shared/list_extension.dart
  frontend/rust-lib/flowy-core/src/integrate/log.rs
Labels: v0.5.4

#5015 feat: support moving view across sections
  frontend/appflowy_flutter/lib/workspace/application/view/view_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/view/view_service.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/folder/_section_folder.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/draggable_view_item.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
  frontend/rust-lib/flowy-folder/src/entities/view.rs
  frontend/rust-lib/flowy-folder/src/event_handler.rs
  frontend/rust-lib/flowy-folder/src/event_map.rs
  frontend/rust-lib/flowy-folder/src/manager.rs
Labels: v0.5.4

#5029 chore: upgrade android min sdk version to 23 (android 6.0)
  frontend/appflowy_flutter/android/app/build.gradle
Labels: mobile, v0.5.4

#5014 feat: filter recent views not belong to current user
  frontend/appflowy_flutter/lib/workspace/application/user/user_workspace_bloc.dart
  frontend/rust-lib/flowy-folder/src/event_handler.rs
  frontend/rust-lib/flowy-folder/src/manager.rs
Labels: v0.5.4

#5033 chore: replace close_document with close_view
  frontend/appflowy_flutter/lib/plugins/document/application/doc_service.dart
Labels: v0.5.4

#5043 fix: disable collaborators in local mode
  frontend/appflowy_flutter/lib/plugins/document/application/doc_collaborators_bloc.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/document_collaborators.dart
Labels: v0.5.4

#5045 fix: workspaces empty error in local mode
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page_header.dart
  frontend/appflowy_flutter/lib/workspace/application/user/user_workspace_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar_workspace.dart
Labels: v0.5.4

#5051 chore: enable collaborator
  frontend/appflowy_flutter/lib/plugins/document/application/doc_collaborators_bloc.dart
Labels: v0.5.4

#5066 Update ckb-KU.json
  frontend/resources/translations/ckb-KU.json
  project.inlang.json
  project.inlang/settings.json
Labels: translation, v0.5.4

#5067 feat: add a loading indicator when creating, deleting, or switching workspaces.
  .github/workflows/ios_ci.yaml
  frontend/appflowy_flutter/integration_test/cloud/workspace/collaborative_workspace_test.dart
  frontend/appflowy_flutter/integration_test/shared/base.dart
  frontend/appflowy_flutter/integration_test/shared/common_operations.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_folders.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/workspaces/workspace_menu_bottom_sheet.dart
  frontend/appflowy_flutter/lib/plugins/database/application/sync/database_sync_bloc.dart
  frontend/appflowy_flutter/lib/plugins/document/application/doc_collaborators_bloc.dart
  frontend/appflowy_flutter/lib/plugins/document/application/doc_sync_bloc.dart
  frontend/appflowy_flutter/lib/plugins/document/document.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/collaborator_avater_stack.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/document_collaborators.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/loading.dart
  frontend/appflowy_flutter/lib/workspace/application/menu/sidebar_sections_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/user/user_workspace_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar_folder.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar_workspace.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_actions.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/settings_dialog.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_menu.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text.dart
  frontend/resources/translations/en.json
  frontend/rust-lib/flowy-folder/src/manager.rs
Labels: v0.5.4

#4721 fix: Twelve Hour parsing issue
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_date_block.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/appflowy_date_picker.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/widgets/time_text_field.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text_field.dart
Labels: v0.5.4

#4426 Fix: Enable more text to be translated
  frontend/appflowy_flutter/lib/plugins/document/document_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/align_toolbar_item/custom_text_align_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/code_block/code_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/code_block/code_block_shortcut_event.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/context_menu/custom_context_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_copy_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_cut_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_paste_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/database/inline_database_menu_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/database/referenced_database_menu_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/math_equation/math_equation_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/slash_menu_items.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/auto_completion_node_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/outline/outline_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toggle/toggle_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toggle/toggle_block_shortcut_event.dart
  frontend/appflowy_flutter/lib/workspace/application/settings/appearance/appearance_cubit.dart
  frontend/appflowy_flutter/lib/workspace/application/settings/shortcuts/settings_shortcuts_cubit.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/emoji_picker/emoji_menu_item.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_customize_shortcuts_view.dart
  frontend/resources/translations/en.json
  frontend/resources/translations/pt-BR.json
Labels: translation, v0.5.4

#5077 Update french translations
  frontend/resources/translations/ar-SA.json
  frontend/resources/translations/ca-ES.json
  frontend/resources/translations/ckb-KU.json
  frontend/resources/translations/de-DE.json
  frontend/resources/translations/es-VE.json
  frontend/resources/translations/eu-ES.json
  frontend/resources/translations/fa.json
  frontend/resources/translations/fr-CA.json
  frontend/resources/translations/fr-FR.json
  frontend/resources/translations/hu-HU.json
  frontend/resources/translations/id-ID.json
  frontend/resources/translations/it-IT.json
  frontend/resources/translations/ja-JP.json
  frontend/resources/translations/ko-KR.json
  frontend/resources/translations/pl-PL.json
  frontend/resources/translations/pt-BR.json
  frontend/resources/translations/pt-PT.json
  frontend/resources/translations/ru-RU.json
  frontend/resources/translations/sv-SE.json
  frontend/resources/translations/tr-TR.json
  frontend/resources/translations/vi-VN.json
  frontend/resources/translations/zh-CN.json
  frontend/resources/translations/zh-TW.json
Labels: translation, v0.5.4

#5083 fix: delta insert assert
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.5.4

#5094 chore: update editor version & update CHANGELOG
  CHANGELOG.md
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.5.4

#5095 Update tr-TR.json
  frontend/resources/translations/tr-TR.json
Labels: translation, v0.5.4

#5100 fix: do not fetch reminders on resize window
  frontend/appflowy_flutter/lib/workspace/presentation/home/desktop_home_screen.dart
Labels: v0.5.5

#5076 fix: hide menu resize when collapsed
  frontend/appflowy_flutter/lib/workspace/application/home/home_service.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/desktop_home_screen.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/navigation.dart
Labels: v0.5.5

#4798 fix: update last modified on icon change
  frontend/appflowy_flutter/integration_test/desktop/database/database_row_page_test.dart
  frontend/rust-lib/flowy-database2/src/event_handler.rs
  frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
  frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs
Labels: v0.5.5

#5101 Update translations
  frontend/resources/translations/de-DE.json
  frontend/resources/translations/en.json
  frontend/resources/translations/fr-CA.json
  frontend/resources/translations/fr-FR.json
  frontend/resources/translations/it-IT.json
  frontend/resources/translations/pt-BR.json
  frontend/resources/translations/ru-RU.json
  frontend/resources/translations/tr-TR.json
  frontend/resources/translations/zh-TW.json
Labels: v0.5.5

#5103 fix: windows size overflow
  frontend/appflowy_flutter/lib/startup/tasks/app_window_size_manager.dart
  frontend/appflowy_flutter/lib/startup/tasks/windows.dart
Labels: v0.5.5

#5020 chore: rename workspace view builder
  frontend/rust-lib/flowy-core/src/deps_resolve/folder_deps.rs
  frontend/rust-lib/flowy-folder-pub/src/folder_builder.rs
  frontend/rust-lib/flowy-folder/src/user_default.rs
  frontend/rust-lib/flowy-folder/src/view_operation.rs
Labels: v0.5.5

#5058 fix: regression selected options not scrolling automatically
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/select_option_cell_editor.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/select_option_text_field.dart
Labels: regression, v0.5.5

#5054 feat: code block improvements
  frontend/appflowy_flutter/lib/plugins/document/application/document_appearance_cubit.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/format_arrow_character.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/selectable_item_list_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/code_block/code_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/code_block/code_block_shortcut_event.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
  frontend/appflowy_flutter/lib/workspace/application/settings/appearance/base_appearance.dart
  frontend/appflowy_flutter/packages/appflowy_popover/lib/src/popover.dart
  frontend/resources/translations/en.json
Labels: improvements, v0.5.5

#5062 fix: import panel exits on esc key (#4259)
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/import/import_panel.dart
Labels: improvements, v0.5.5

#4950 feat: Add Ninja i18n lint action
  .github/workflows/ninja_i18n.yml
Labels: translation, v0.5.5

#5113 chore: remove single field listener
  frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/mobile_card_detail_screen.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_quick_field_editor.dart
  frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/relation_cell_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/application/cell/cell_controller.dart
  frontend/appflowy_flutter/lib/plugins/database/application/field/field_controller.dart
  frontend/appflowy_flutter/lib/plugins/database/application/field/field_editor_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/application/row/row_banner_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/domain/field_listener.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/field/field_editor.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/row/row_banner.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/row/row_detail.dart
  frontend/appflowy_flutter/test/bloc_test/board_test/create_or_edit_field_test.dart
  frontend/appflowy_flutter/test/bloc_test/board_test/group_by_unsupport_field_test.dart
  frontend/appflowy_flutter/test/bloc_test/board_test/util.dart
  frontend/appflowy_flutter/test/bloc_test/grid_test/field/edit_field_test.dart
  frontend/appflowy_flutter/test/bloc_test/grid_test/util.dart
Labels: v0.5.5

#5110 chore: machine translation
  frontend/appflowy_flutter/lib/mobile/presentation/database/board/widgets/mobile_hidden_groups_column.dart
  frontend/appflowy_flutter/lib/plugins/database/board/presentation/board_page.dart
  frontend/resources/translations/ar-SA.json
  frontend/resources/translations/ca-ES.json
  frontend/resources/translations/ckb-KU.json
  frontend/resources/translations/cs-CZ.json
  frontend/resources/translations/de-DE.json
  frontend/resources/translations/el-GR.json
  frontend/resources/translations/en.json
  frontend/resources/translations/es-VE.json
  frontend/resources/translations/eu-ES.json
  frontend/resources/translations/fa.json
  frontend/resources/translations/fr-CA.json
  frontend/resources/translations/fr-FR.json
  frontend/resources/translations/hu-HU.json
  frontend/resources/translations/id-ID.json
  frontend/resources/translations/it-IT.json
  frontend/resources/translations/ja-JP.json
  frontend/resources/translations/ko-KR.json
  frontend/resources/translations/pl-PL.json
  frontend/resources/translations/pt-BR.json
  frontend/resources/translations/pt-PT.json
  frontend/resources/translations/ru-RU.json
  frontend/resources/translations/sv-SE.json
  frontend/resources/translations/th-TH.json
  frontend/resources/translations/tr-TR.json
  frontend/resources/translations/vi-VN.json
  frontend/resources/translations/vi.json
  frontend/resources/translations/zh-CN.json
  frontend/resources/translations/zh-TW.json
Labels: translation, v0.5.5

#5000 feat: double tab edit side panel
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
Labels: improvements, v0.5.5

#4827 Workspace invite
  .github/workflows/rust_ci.yaml
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/event-integration/src/folder_event.rs
  frontend/rust-lib/event-integration/tests/user/af_cloud_test/member_test.rs
  frontend/rust-lib/flowy-database2/src/services/calculations/service.rs
  frontend/rust-lib/flowy-server/src/af_cloud/impls/user/cloud_service_impl.rs
  frontend/rust-lib/flowy-server/src/af_cloud/impls/user/dto.rs
  frontend/rust-lib/flowy-user-pub/src/cloud.rs
  frontend/rust-lib/flowy-user-pub/src/entities.rs
  frontend/rust-lib/flowy-user/src/entities/workspace.rs
  frontend/rust-lib/flowy-user/src/event_handler.rs
  frontend/rust-lib/flowy-user/src/event_map.rs
  frontend/rust-lib/flowy-user/src/user_manager/manager_user_workspace.rs
Labels: new feature, v0.5.5

#5039 refactor: cell data transform logic
  frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/select_option_cell_editor_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/domain/select_option_cell_service.dart
  frontend/appflowy_flutter/test/bloc_test/grid_test/cell/select_option_cell_test.dart
  frontend/rust-lib/flowy-database2/src/event_handler.rs
  frontend/rust-lib/flowy-database2/src/event_map.rs
  frontend/rust-lib/flowy-database2/src/services/calculations/service.rs
  frontend/rust-lib/flowy-database2/src/services/cell/cell_operation.rs
  frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
  frontend/rust-lib/flowy-database2/src/services/database_view/view_group.rs
  frontend/rust-lib/flowy-database2/src/services/database_view/view_operation.rs
  frontend/rust-lib/flowy-database2/src/services/field/field_operation.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/checkbox_type_option/checkbox_tests.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/checkbox_type_option/checkbox_type_option.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/checklist_type_option/checklist.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/date_type_option/date_tests.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/date_type_option/date_type_option.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/number_type_option/number_tests.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/number_type_option/number_type_option.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/relation_type_option/relation.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/selection_type_option/select_type_option.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/selection_type_option/type_option_transform.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/text_type_option/text_tests.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/text_type_option/text_type_option.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/timestamp_type_option/timestamp_type_option.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/type_option.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/type_option_cell.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/url_type_option/url_type_option.rs
  frontend/rust-lib/flowy-database2/src/services/filter/controller.rs
  frontend/rust-lib/flowy-database2/src/services/share/csv/export.rs
  frontend/rust-lib/flowy-database2/src/services/sort/controller.rs
  frontend/rust-lib/flowy-database2/tests/database/field_test/script.rs
  frontend/rust-lib/flowy-database2/tests/database/field_test/test.rs
  frontend/rust-lib/flowy-database2/tests/database/pre_fill_cell_test/pre_fill_row_according_to_filter_test.rs
  frontend/rust-lib/flowy-database2/tests/database/pre_fill_cell_test/pre_fill_row_with_payload_test.rs
  frontend/rust-lib/flowy-database2/tests/database/pre_fill_cell_test/script.rs
  frontend/rust-lib/flowy-database2/tests/database/share_test/export_test.rs
  frontend/rust-lib/flowy-database2/tests/database/sort_test/script.rs
Labels: v0.5.5

#5021 feat: expand share option
  frontend/appflowy_flutter/lib/plugins/document/application/document_share_bloc.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/share/share_button.dart
  frontend/appflowy_flutter/lib/workspace/application/export/document_exporter.dart
  frontend/resources/translations/en.json
  frontend/resources/translations/zh-CN.json
  frontend/rust-lib/flowy-document/src/entities.rs
Labels: new feature, v0.5.5

#4180 perf: Fixed And Prettier ZH_CN Translate
  frontend/resources/translations/zh-CN.json
Labels: translation, v0.5.5

#5115 fix: rust ci
  .github/workflows/rust_ci.yaml
  frontend/appflowy_flutter/integration_test/desktop/uncategorized/share_markdown_test.dart
  frontend/appflowy_flutter/integration_test/mobile/home_page/create_new_page_test.dart
  frontend/appflowy_flutter/integration_test/mobile/sign_in/anonymous_sign_in_test.dart
  frontend/appflowy_flutter/integration_test/shared/auth_operation.dart
  frontend/rust-lib/event-integration/src/folder_event.rs
  frontend/rust-lib/event-integration/tests/user/af_cloud_test/member_test.rs
Labels: v0.5.5

#5121 Update French translations
  frontend/resources/translations/fr-FR.json
Labels: i18n, v0.5.5

#5122 refactor: fetch all options from type option
  .github/workflows/rust_ci.yaml
  frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/select_option_cell_editor_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/application/cell/cell_controller.dart
  frontend/rust-lib/event-integration/src/folder_event.rs
  frontend/rust-lib/event-integration/src/lib.rs
  frontend/rust-lib/event-integration/tests/database/local_test/test.rs
  frontend/rust-lib/flowy-database2/src/entities/type_option_entities/select_option_entities.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/selection_type_option/select_option.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/selection_type_option/select_type_option.rs
  frontend/rust-lib/flowy-search/src/folder/indexer.rs
Labels: v0.5.5

#5128 feat: allow fields to not wrap cell content
  frontend/appflowy_flutter/lib/mobile/presentation/database/date_picker/mobile_date_picker_screen.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_edit_field_screen.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_quick_field_editor.dart
  frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/checkbox_cell_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/checklist_cell_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/date_cell_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/date_cell_editor_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/number_cell_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/relation_cell_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/select_option_cell_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/select_option_cell_editor_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/text_cell_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/timestamp_cell_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/url_cell_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/url_cell_editor_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/application/cell/cell_controller.dart
  frontend/appflowy_flutter/lib/plugins/database/application/cell/cell_data_loader.dart
  frontend/appflowy_flutter/lib/plugins/database/application/field/field_cell_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/application/field/field_editor_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/application/field/field_info.dart
  frontend/appflowy_flutter/lib/plugins/database/domain/field_settings_service.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/mobile_grid_page.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/card/card_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/card_cell_skeleton/date_card_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/card_cell_skeleton/number_card_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/card_cell_skeleton/select_option_card_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/card_cell_skeleton/text_card_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/card_cell_skeleton/timestamp_card_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/card_cell_skeleton/url_card_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_grid/desktop_grid_date_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_grid/desktop_grid_number_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_grid/desktop_grid_relation_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_grid/desktop_grid_select_option_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_grid/desktop_grid_text_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_grid/desktop_grid_timestamp_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_grid/desktop_grid_url_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/editable_cell_skeleton/date.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/editable_cell_skeleton/number.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/editable_cell_skeleton/select_option.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/editable_cell_skeleton/text.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/editable_cell_skeleton/timestamp.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/editable_cell_skeleton/url.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/date_editor.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/field/field_editor.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/row/cells/cell_container.dart
  frontend/resources/translations/en.json
  frontend/rust-lib/flowy-database2/src/entities/field_settings_entities.rs
  frontend/rust-lib/flowy-database2/src/event_handler.rs
  frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
  frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs
  frontend/rust-lib/flowy-database2/src/services/database_view/view_operation.rs
  frontend/rust-lib/flowy-database2/src/services/field_settings/entities.rs
  frontend/rust-lib/flowy-database2/src/services/field_settings/field_settings_builder.rs
  frontend/rust-lib/flowy-database2/tests/database/field_settings_test/script.rs
Labels: v0.5.5

#5138 docs: Update translations
  frontend/resources/translations/ar-SA.json
  frontend/resources/translations/ca-ES.json
  frontend/resources/translations/ckb-KU.json
  frontend/resources/translations/cs-CZ.json
  frontend/resources/translations/de-DE.json
  frontend/resources/translations/es-VE.json
  frontend/resources/translations/eu-ES.json
  frontend/resources/translations/fa.json
  frontend/resources/translations/fr-CA.json
  frontend/resources/translations/fr-FR.json
  frontend/resources/translations/hu-HU.json
  frontend/resources/translations/id-ID.json
  frontend/resources/translations/it-IT.json
  frontend/resources/translations/ja-JP.json
  frontend/resources/translations/ko-KR.json
  frontend/resources/translations/pl-PL.json
  frontend/resources/translations/pt-BR.json
  frontend/resources/translations/pt-PT.json
  frontend/resources/translations/ru-RU.json
  frontend/resources/translations/sv-SE.json
  frontend/resources/translations/tr-TR.json
  frontend/resources/translations/vi-VN.json
  frontend/resources/translations/vi.json
  frontend/resources/translations/zh-CN.json
  frontend/resources/translations/zh-TW.json
Labels: translation, v0.5.5

#5119 chore: remove field width and visibility
  frontend/appflowy_tauri/src-tauri/Cargo.lock
  frontend/appflowy_tauri/src-tauri/Cargo.toml
  frontend/appflowy_web/wasm-libs/Cargo.toml
  frontend/appflowy_web_app/src-tauri/Cargo.lock
  frontend/appflowy_web_app/src-tauri/Cargo.toml
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
  frontend/rust-lib/flowy-database2/src/entities/field_entities.rs
  frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
  frontend/rust-lib/flowy-database2/src/services/field/field_builder.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/type_option.rs
  frontend/rust-lib/flowy-database2/src/template.rs
  frontend/rust-lib/flowy-database2/tests/database/field_test/util.rs
  frontend/rust-lib/flowy-database2/tests/database/mock_data/board_mock_data.rs
  frontend/rust-lib/flowy-database2/tests/database/mock_data/calendar_mock_data.rs
  frontend/rust-lib/flowy-database2/tests/database/mock_data/grid_mock_data.rs
Labels: v0.5.5

#5149 Fink 🐦: update translations
  frontend/resources/translations/es-VE.json
Labels: translation, v0.5.5

#5024 chore: improve link between folder and database
  frontend/appflowy_tauri/src-tauri/Cargo.lock
  frontend/appflowy_tauri/src-tauri/Cargo.toml
  frontend/appflowy_web/wasm-libs/Cargo.toml
  frontend/appflowy_web_app/src-tauri/Cargo.lock
  frontend/appflowy_web_app/src-tauri/Cargo.toml
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
  frontend/rust-lib/flowy-database2/src/manager.rs
  frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs
  frontend/rust-lib/flowy-database2/src/services/share/csv/import.rs
  frontend/rust-lib/flowy-database2/src/template.rs
  frontend/rust-lib/flowy-database2/tests/database/database_editor.rs
  frontend/rust-lib/flowy-database2/tests/database/mock_data/board_mock_data.rs
  frontend/rust-lib/flowy-database2/tests/database/mock_data/calendar_mock_data.rs
  frontend/rust-lib/flowy-database2/tests/database/mock_data/grid_mock_data.rs
Labels: v0.5.6

#5172 chore: update translation text for wrap cell content
  frontend/appflowy_flutter/lib/plugins/database/widgets/field/field_editor.dart
  frontend/resources/translations/en.json
Labels: v0.5.5

#5164 chore: use inferred error instead
  frontend/rust-lib/flowy-user/src/user_manager/manager.rs
Labels: v0.5.5

#5177 chore: update client api
  frontend/appflowy_tauri/src-tauri/Cargo.lock
  frontend/appflowy_tauri/src-tauri/Cargo.toml
  frontend/appflowy_web/wasm-libs/Cargo.lock
  frontend/appflowy_web/wasm-libs/Cargo.toml
  frontend/appflowy_web_app/src-tauri/Cargo.lock
  frontend/appflowy_web_app/src-tauri/Cargo.toml
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
Labels: v0.5.5

#5178 fix: add an outline to accessory buttons
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_grid/desktop_grid_url_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/row/accessory/cell_accessory.dart
Labels: v0.5.5

#5174 Update translations
  frontend/resources/translations/ar-SA.json
  frontend/resources/translations/ca-ES.json
  frontend/resources/translations/ckb-KU.json
  frontend/resources/translations/cs-CZ.json
  frontend/resources/translations/de-DE.json
  frontend/resources/translations/es-VE.json
  frontend/resources/translations/eu-ES.json
  frontend/resources/translations/fa.json
  frontend/resources/translations/fr-CA.json
  frontend/resources/translations/fr-FR.json
  frontend/resources/translations/hu-HU.json
  frontend/resources/translations/id-ID.json
  frontend/resources/translations/it-IT.json
  frontend/resources/translations/ja-JP.json
  frontend/resources/translations/ko-KR.json
  frontend/resources/translations/pl-PL.json
  frontend/resources/translations/pt-BR.json
  frontend/resources/translations/pt-PT.json
  frontend/resources/translations/ru-RU.json
  frontend/resources/translations/sv-SE.json
  frontend/resources/translations/tr-TR.json
  frontend/resources/translations/vi-VN.json
  frontend/resources/translations/vi.json
  frontend/resources/translations/zh-CN.json
  frontend/resources/translations/zh-TW.json
Labels: translation, v0.5.5

#5162 fix: launch review issues 0.5.5
  frontend/appflowy_flutter/lib/core/config/kv_keys.dart
  frontend/appflowy_flutter/lib/mobile/presentation/setting/user_session_setting_group.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/resizeable_image.dart
  frontend/appflowy_flutter/lib/user/application/sign_in_bloc.dart
  frontend/appflowy_flutter/lib/user/presentation/helpers/handle_open_workspace_error.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/desktop_sign_in_screen.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/mobile_sign_in_screen.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/sign_in_screen.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/anou
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/magic_link_sign_in_buttons.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/switch_sign_in_sign_up_button.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/third_party_sign_in_buttons.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/widgets.dart
  frontend/appflowy_flutter/lib/user/presentation/widgets/auth_form_container.dart
  frontend/appflowy_flutter/lib/workspace/application/user/user_workspace_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/desktop_home_screen.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/toast.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/view_title_bar.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/snap_bar.dart
  frontend/resources/flowy_icons/40x/broken_image.svg
  frontend/resources/translations/en.json
Labels: v0.5.5

#5175 feat: code block launch review
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/mobile_sign_in_screen.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/resources/translations/en.json
Labels: v0.5.5

#5183 fix: use database sync bloc in database page
  frontend/appflowy_flutter/lib/mobile/presentation/base/mobile_view_page.dart
Labels: bug, v0.5.5

#5182 fix: support tr_TR language
  frontend/resources/translations/tr-TR.json
Labels: translation, v0.5.5

#5156 Update language.dart
  frontend/appflowy_flutter/packages/flowy_infra/lib/language.dart
Labels: v0.5.5

#5197 chore: check workspace id before write to disk
  .github/workflows/flutter_ci.yaml
  .github/workflows/rust_ci.yaml
  frontend/appflowy_tauri/src-tauri/Cargo.lock
  frontend/appflowy_tauri/src-tauri/Cargo.toml
  frontend/appflowy_web/wasm-libs/Cargo.lock
  frontend/appflowy_web/wasm-libs/Cargo.toml
  frontend/appflowy_web_app/src-tauri/Cargo.lock
  frontend/appflowy_web_app/src-tauri/Cargo.toml
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
  frontend/rust-lib/collab-integrate/src/collab_builder.rs
  frontend/rust-lib/dart-ffi/Cargo.toml
  frontend/rust-lib/event-integration/src/document/document_event.rs
  frontend/rust-lib/flowy-core/Cargo.toml
  frontend/rust-lib/flowy-document/src/event_handler.rs
  frontend/rust-lib/flowy-document/src/manager.rs
  frontend/rust-lib/flowy-error/src/code.rs
  frontend/rust-lib/flowy-error/src/errors.rs
  frontend/rust-lib/flowy-folder/src/manager.rs
  frontend/rust-lib/flowy-folder/src/manager_init.rs
  frontend/rust-lib/flowy-server/src/af_cloud/impls/database.rs
  frontend/rust-lib/flowy-server/src/af_cloud/impls/document.rs
  frontend/rust-lib/flowy-server/src/af_cloud/impls/folder.rs
  frontend/rust-lib/flowy-server/src/af_cloud/impls/user/cloud_service_impl.rs
  frontend/rust-lib/lib-log/src/lib.rs
Labels: v0.5.5

#5198 chore: release 0.5.5
  CHANGELOG.md
  frontend/appflowy_flutter/lib/shared/feature_flags.dart
Labels: v0.5.5

#5207 chore: update documentation for type option cell-related traits
  frontend/rust-lib/flowy-database2/src/services/cell/cell_operation.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/type_option_cell.rs
Labels: v0.5.6

#5181 fix: kanban row icon
  frontend/appflowy_flutter/lib/plugins/database/board/presentation/board_page.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/card_cell_skeleton/text_card_cell.dart
Labels: v0.5.6

#5170 feat: mobile floating toolbar animation
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_floating_toolbar/custom_mobile_floating_toolbar.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.5.6

#5215 fix: migrate OKRs issues
  frontend/Makefile.toml
  frontend/appflowy_flutter/integration_test/desktop/document/document_copy_and_paste_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/shared/feature_flags.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/desktop_home_screen.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/hotkeys.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/folder/_section_folder.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar_setting.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/view_title_bar.dart
  frontend/appflowy_flutter/packages/flowy_infra/pubspec.yaml
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/appflowy_flutter/test/bloc_test/home_test/view_bloc_test.dart
Labels: v0.5.6

#5163 feat: use font name instead of fontname_regular
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/aa_menu/_font_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_appearance/font_family_setting.dart
Labels: v0.5.6

#5210 fix: some database bugs
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/editable_cell_skeleton/url.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/toast.dart
  frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
Labels: bug, v0.5.6

#5118 feat: support inviting members
  frontend/appflowy_flutter/lib/user/application/user_service.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/members/workspace_member_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/members/workspace_member_page.dart
  frontend/resources/translations/en.json
Labels: v0.5.6
