Repository AppFlowy-IO/AppFlowy, pull requests merged in 2024-10, with the labels that each got.

#6435 feat: keep link format when converting preview block to text
  frontend/appflowy_flutter/integration_test/desktop/document/document_copy_and_paste_test.dart
  frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_block_action_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_paste_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/link_preview/custom_link_preview.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/link_preview/link_preview_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/link_preview/shared.dart
Labels: v0.7.1

#6441 fix: insert the pasted nodes after current selection if they start with a non-delta node
  frontend/appflowy_flutter/integration_test/desktop/document/document_copy_and_paste_test.dart
  frontend/appflowy_flutter/integration_test/shared/document_test_operations.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.7.1

#6446 fix(flutter_desktop): fix calendar event bugs
  frontend/appflowy_flutter/lib/plugins/database/calendar/presentation/calendar_event_card.dart
  frontend/appflowy_flutter/lib/plugins/database/calendar/presentation/calendar_event_editor.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/card/container/accessory.dart
Labels: v0.7.1

#6442 test: add grid bloc and integration tests
  frontend/appflowy_flutter/integration_test/desktop/database/database_field_settings_test.dart
  frontend/appflowy_flutter/integration_test/desktop/grid/grid_edit_row_test.dart
  frontend/appflowy_flutter/integration_test/desktop_runner_3.dart
  frontend/appflowy_flutter/integration_test/shared/database_test_op.dart
  frontend/appflowy_flutter/test/bloc_test/grid_test/filter/filter_menu_test.dart
Labels: v0.7.1

#6449 feat: support workspace ops on mobile
  .github/workflows/flutter_ci.yaml
  frontend/appflowy_flutter/integration_test/cloud/supabase_auth_test.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/cloud_runner.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/document/document_delete_block_test.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/document/document_drag_block_test.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/sidebar/sidebar_move_page_test.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/uncategorized/anon_user_continue_test.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/uncategorized/appflowy_cloud_auth_test.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/uncategorized/document_sync_test.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/uncategorized/empty_test.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/uncategorized/user_setting_sync_test.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/workspace/change_name_and_icon_test.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/workspace/collaborative_workspace_test.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/workspace/workspace_settings_test.dart
  frontend/appflowy_flutter/integration_test/mobile/cloud/cloud_runner.dart
  frontend/appflowy_flutter/integration_test/mobile/cloud/workspace/workspace_operations_test.dart
  frontend/appflowy_flutter/integration_test/mobile/document/page_style_test.dart
  frontend/appflowy_flutter/integration_test/mobile_runner.dart
  frontend/appflowy_flutter/integration_test/shared/constants.dart
  frontend/appflowy_flutter/integration_test/shared/expectation.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page_header.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/workspaces/create_workspace_menu.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/workspaces/workspace_menu_bottom_sheet.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/workspaces/workspace_more_options.dart
  frontend/appflowy_flutter/lib/mobile/presentation/widgets/show_flowy_mobile_confirm_dialog.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/third_party_sign_in_buttons.dart
  frontend/appflowy_flutter/lib/util/color_generator/color_generator.dart
  frontend/appflowy_flutter/lib/util/navigator_context_exntesion.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_icon.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/account/account_deletion.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/account/account_sign_in_out.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/files/settings_file_exporter_widget.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/resources/flowy_icons/16x/leave_workspace.svg
  frontend/resources/flowy_icons/16x/workspace_add_member.svg
  frontend/resources/translations/en.json
Labels: v0.7.1

#6378 Update translations
  frontend/resources/translations/ko-KR.json
Labels: translation, v0.7.1

#6451 fix: field type option transform
  frontend/appflowy_flutter/integration_test/desktop/database/database_cell_test.dart
  frontend/appflowy_flutter/integration_test/desktop/database/database_field_test.dart
  frontend/appflowy_flutter/integration_test/desktop/database/database_share_test.dart
  frontend/appflowy_flutter/integration_test/shared/database_test_op.dart
  frontend/rust-lib/flowy-database2/src/event_handler.rs
  frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
  frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/selection_type_option/type_option_transform.rs
Labels: v0.7.1

#6454 fix: hide border on icon in callout
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_component.dart
Labels: v0.7.1

#6453 feat: show file popover automatically
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_file_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/file/file_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/file/file_selection_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/image_selection_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/add_block_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items.dart
Labels: v0.7.1

#6452 feat: update workspace icon style on desktop
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_database_test.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page_header.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/workspaces/workspace_menu_bottom_sheet.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/link_to_page_widget.dart
  frontend/appflowy_flutter/lib/plugins/inline_actions/inline_actions_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_icon.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/sidebar_workspace.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_workspace_view.dart
Labels: v0.7.1

#6409 fix: hide editing rows from groups when filters are applied
  frontend/appflowy_flutter/lib/plugins/database/grid/application/filter/filter_editor_bloc.dart
  frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs
Labels: v0.7.1

#6384 Update translations for ru_RU
  frontend/resources/translations/ru-RU.json
Labels: i18n, v0.7.1

#6456 fix: new dialog style in trash actions
  frontend/appflowy_flutter/lib/plugins/trash/trash_page.dart
  frontend/resources/translations/en.json
Labels: v0.7.1

#6459 chore: update client api
  frontend/appflowy_tauri/src-tauri/Cargo.lock
  frontend/appflowy_tauri/src-tauri/Cargo.toml
  frontend/appflowy_web_app/src-tauri/Cargo.lock
  frontend/appflowy_web_app/src-tauri/Cargo.toml
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
Labels: v0.7.1

#6468 fix: ingore keyup event in cover title
  frontend/appflowy_flutter/integration_test/desktop/cloud/cloud_runner.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/document/document_delete_block_test.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/document/document_drag_block_test.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/document/document_option_actions_test.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/document/document_test_runner.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/uncategorized/uncategorized_test_runner.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/workspace/workspace_test_runner.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_title_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/cover_title.dart
  frontend/appflowy_flutter/lib/shared/text_field/text_filed_with_metric_lines.dart
Labels: v0.7.1

#6472 chore: disable copy link to block feature
  frontend/appflowy_flutter/integration_test/desktop/cloud/document/document_option_actions_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
Labels: v0.7.1

#6469 feat: add more bottom padding in workspace menu
  frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/show_mobile_bottom_sheet.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page_header.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/workspaces/workspace_menu_bottom_sheet.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/sidebar_workspace.dart
  frontend/appflowy_flutter/packages/appflowy_popover/lib/src/popover.dart
Labels: v0.7.1

#6479 fix: launch review issues
  frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_filter_bottom_sheet.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_filter_bottom_sheet_cubit.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/field/field_editor.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/space_icon_popup.dart
  frontend/resources/translations/en.json
Labels: v0.7.1

#6481 fix: title flash when resizing
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/cover_title.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/document_cover_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
Labels: v0.7.1

#6487 fix: share button doesn't response under macOS 15
  frontend/appflowy_flutter/lib/core/frameless_window.dart
  frontend/appflowy_flutter/lib/startup/tasks/device_info_task.dart
  frontend/appflowy_flutter/macos/Runner/MainFlutterWindow.swift
Labels: v0.7.1

#6495 fix: potential text empty when editing doc
  frontend/appflowy_flutter/lib/plugins/document/application/document_bloc.dart
  frontend/appflowy_flutter/lib/plugins/document/application/editor_transaction_adapter.dart
  frontend/appflowy_flutter/test/unit_test/editor/transaction_adapter_test.dart
Labels: v0.7.1

#6502 chore: update CHANGELOG.md
  CHANGELOG.md
Labels: v0.7.1

#6496 fix: ignore same workspace icon update
  frontend/appflowy_flutter/integration_test/desktop/cloud/workspace/workspace_icon_test.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/workspace/workspace_test_runner.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_title_test.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_cover_image_test.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_image_block_test.dart
  frontend/appflowy_flutter/integration_test/shared/document_test_operations.dart
  frontend/appflowy_flutter/lib/mobile/application/page_style/document_page_style_bloc.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/cover_title.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/document_cover_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/shortcuts/command_shortcuts.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/shortcuts/exit_edit_mode_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/undo_redo/custom_undo_redo_commands.dart
  frontend/appflowy_flutter/lib/workspace/application/user/user_workspace_bloc.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_tauri/src-tauri/Cargo.lock
  frontend/appflowy_tauri/src-tauri/Cargo.toml
  frontend/appflowy_web_app/src-tauri/Cargo.lock
  frontend/appflowy_web_app/src-tauri/Cargo.toml
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
  frontend/rust-lib/flowy-user/src/services/data_import/appflowy_data_import.rs
Labels: v0.7.1

#6501 feat: support editing name when creating a new page on mobile
  .github/actions/flutter_integration_test/action.yml
  .github/workflows/flutter_ci.yaml
  .github/workflows/release.yml
  frontend/appflowy_flutter/integration_test/desktop/document/document_test_runner_1.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_test_runner_2.dart
  frontend/appflowy_flutter/integration_test/desktop_runner_1.dart
  frontend/appflowy_flutter/integration_test/desktop_runner_3.dart
  frontend/appflowy_flutter/integration_test/desktop_runner_4.dart
  frontend/appflowy_flutter/integration_test/mobile/document/document_test_runner.dart
  frontend/appflowy_flutter/integration_test/mobile/document/title_test.dart
  frontend/appflowy_flutter/integration_test/runner.dart
  frontend/appflowy_flutter/integration_test/shared/common_operations.dart
  frontend/appflowy_flutter/integration_test/shared/document_test_operations.dart
  frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/default_mobile_action_pane.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/space/mobile_space.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/tab/mobile_space_tab.dart
  frontend/appflowy_flutter/lib/mobile/presentation/mobile_bottom_navigation_bar.dart
  frontend/appflowy_flutter/lib/mobile/presentation/page_item/mobile_view_item.dart
  frontend/appflowy_flutter/lib/plugins/document/document_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/cover/document_immersive_cover.dart
  frontend/appflowy_flutter/lib/workspace/application/view/view_ext.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
  frontend/resources/translations/en.json
  frontend/resources/translations/ja-JP.json
  frontend/resources/translations/tr-TR.json
  frontend/resources/translations/uk-UA.json
  frontend/resources/translations/vi-VN.json
Labels: v0.7.1

#6505 fix: show AI limit error toast if exceeding the AI response
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/smart_edit_bloc.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/smart_edit_node_widget.dart
  frontend/appflowy_flutter/test/bloc_test/smart_edit_test/smart_editor_bloc_test.dart
Labels: v0.7.1

#6508 fix: fetch all calendar events
  frontend/appflowy_flutter/lib/plugins/database/calendar/application/unschedule_event_bloc.dart
  frontend/rust-lib/flowy-database2/src/entities/calendar_entities.rs
  frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs
  frontend/rust-lib/flowy-database2/tests/database/layout_test/script.rs
  frontend/rust-lib/flowy-database2/tests/database/layout_test/test.rs
Labels: v0.7.2

#6506 fix: don't process on every view while only handling one view
  frontend/appflowy_flutter/integration_test/desktop/grid/grid_row_test.dart
  frontend/appflowy_flutter/test/bloc_test/grid_test/field/field_editor_bloc_test.dart
  frontend/rust-lib/flowy-database2/src/services/database/database_observe.rs
Labels: v0.7.2

#6507 feat: customize animation for popover
  frontend/appflowy_flutter/integration_test/desktop/sidebar/sidebar_icon_test.dart
  frontend/appflowy_flutter/lib/main.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/field/field_editor.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/field/type_option_editor/select/select_option.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_option_button.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/widgets/time_text_field.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/pop_up_action.dart
  frontend/appflowy_flutter/packages/appflowy_popover/analysis_options.yaml
  frontend/appflowy_flutter/packages/appflowy_popover/example/analysis_options.yaml
  frontend/appflowy_flutter/packages/appflowy_popover/example/ios/Flutter/AppFrameworkInfo.plist
  frontend/appflowy_flutter/packages/appflowy_popover/example/ios/Runner.xcodeproj/project.pbxproj
  frontend/appflowy_flutter/packages/appflowy_popover/example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  frontend/appflowy_flutter/packages/appflowy_popover/example/ios/Runner/Info.plist
  frontend/appflowy_flutter/packages/appflowy_popover/example/lib/example_button.dart
  frontend/appflowy_flutter/packages/appflowy_popover/example/lib/main.dart
  frontend/appflowy_flutter/packages/appflowy_popover/example/macos/Runner.xcodeproj/project.pbxproj
  frontend/appflowy_flutter/packages/appflowy_popover/example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  frontend/appflowy_flutter/packages/appflowy_popover/example/pubspec.yaml
  frontend/appflowy_flutter/packages/appflowy_popover/lib/src/follower.dart
  frontend/appflowy_flutter/packages/appflowy_popover/lib/src/layout.dart
  frontend/appflowy_flutter/packages/appflowy_popover/lib/src/mask.dart
  frontend/appflowy_flutter/packages/appflowy_popover/lib/src/mutex.dart
  frontend/appflowy_flutter/packages/appflowy_popover/lib/src/popover.dart
  frontend/appflowy_flutter/packages/appflowy_popover/pubspec.yaml
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/src/flowy_overlay/appflowy_popover.dart
  frontend/appflowy_flutter/pubspec.lock
Labels: v0.7.2

#6520 test: fix flaky sort editor bloc test
  frontend/appflowy_flutter/test/bloc_test/grid_test/sort/sort_editor_bloc_test.dart
Labels: v0.7.2

#6519 feat: calendar filters
  frontend/appflowy_flutter/integration_test/desktop/database/database_calendar_test.dart
  frontend/appflowy_flutter/integration_test/desktop/database/database_filter_test.dart
  frontend/appflowy_flutter/integration_test/shared/database_test_op.dart
  frontend/appflowy_flutter/lib/plugins/database/application/defines.dart
  frontend/appflowy_flutter/lib/plugins/database/application/row/row_cache.dart
  frontend/appflowy_flutter/lib/plugins/database/calendar/application/calendar_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/calendar/presentation/calendar_page.dart
  frontend/appflowy_flutter/lib/plugins/database/calendar/presentation/toolbar/calendar_setting_bar.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/grid_page.dart
  frontend/appflowy_flutter/lib/plugins/database/tab_bar/mobile/mobile_tab_bar_header.dart
Labels: v0.7.2

#6515 feat: checklist cell improvements
  frontend/appflowy_flutter/integration_test/desktop/database/database_row_page_test.dart
  frontend/appflowy_flutter/integration_test/shared/database_test_op.dart
  frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/checklist_cell_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/domain/checklist_cell_service.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_grid/desktop_grid_checklist_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_row_detail/desktop_row_detail_checklist_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/editable_cell_skeleton/checklist.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/mobile_grid/mobile_grid_checklist_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/mobile_row_detail/mobile_row_detail_checklist_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/checklist_cell_editor.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/checklist_cell_textfield.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/mobile_checklist_cell_editor.dart
  frontend/appflowy_flutter/test/bloc_test/grid_test/cell/checklist_cell_bloc_test.dart
  frontend/appflowy_flutter/test/bloc_test/grid_test/cell/select_option_cell_test.dart
  frontend/appflowy_flutter/test/bloc_test/grid_test/cell/text_cell_bloc_test.dart
  frontend/appflowy_flutter/test/bloc_test/grid_test/field/field_cell_bloc_test.dart
  frontend/appflowy_flutter/test/bloc_test/grid_test/field/field_editor_bloc_test.dart
  frontend/appflowy_flutter/test/bloc_test/grid_test/filter/filter_editor_bloc_test.dart
  frontend/appflowy_flutter/test/bloc_test/grid_test/sort/sort_editor_bloc_test.dart
  frontend/appflowy_flutter/test/bloc_test/grid_test/util.dart
  frontend/rust-lib/event-integration-test/src/database_event.rs
  frontend/rust-lib/event-integration-test/tests/database/local_test/test.rs
  frontend/rust-lib/flowy-database2/src/entities/cell_entities.rs
  frontend/rust-lib/flowy-database2/src/entities/type_option_entities/checklist_entities.rs
  frontend/rust-lib/flowy-database2/src/event_handler.rs
  frontend/rust-lib/flowy-database2/src/services/cell/cell_operation.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/checklist_type_option/checklist_entities.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/checklist_type_option/checklist_type_option.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/checklist_type_option/mod.rs
  frontend/rust-lib/flowy-database2/tests/database/cell_test/test.rs
  frontend/rust-lib/flowy-database2/tests/database/database_editor.rs
  frontend/rust-lib/flowy-database2/tests/database/mock_data/grid_mock_data.rs
Labels: v0.7.2

#6516 feat: support 'turn into' in doc
  frontend/appflowy_flutter/integration_test/desktop/document/document_option_action_test.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_outline_block_test.dart
  frontend/appflowy_flutter/integration_test/shared/document_test_operations.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_list.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_option_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_option_cubit.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/option/align_option_action.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/option/color_option_action.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/option/depth_option_action.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/option/divider_option_action.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/option/option_actions.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/option/turn_into_option_action.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/option_action.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/plugins.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items.dart
  frontend/appflowy_flutter/lib/workspace/application/settings/shortcuts/settings_shortcuts_cubit.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/space_more_popup.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_actions.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_more_action_button.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/float_bubble/social_media_section.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/float_bubble/version_section.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/more_view_actions/widgets/common_view_action.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/pop_up_action.dart
  frontend/appflowy_flutter/packages/appflowy_backend/lib/log.dart
  frontend/appflowy_flutter/packages/appflowy_popover/example/lib/example_button.dart
  frontend/appflowy_flutter/packages/appflowy_popover/lib/src/mask.dart
  frontend/appflowy_flutter/packages/appflowy_popover/lib/src/popover.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/src/flowy_overlay/appflowy_popover.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/appflowy_flutter/test/unit_test/document/turn_into/turn_into_test.dart
  frontend/resources/flowy_icons/16x/turninto.svg
Labels: needs design, v0.7.2

#6475 fix: Grid new row getting cut
  frontend/appflowy_flutter/integration_test/desktop/database/database_field_test.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/grid_page.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/footer/grid_footer.dart
Labels: v0.7.2

#6522 feat: open created filtered rows
  frontend/appflowy_flutter/integration_test/desktop/database/database_calendar_test.dart
  frontend/appflowy_flutter/integration_test/desktop/database/database_filter_test.dart
  frontend/appflowy_flutter/integration_test/shared/database_test_op.dart
  frontend/appflowy_flutter/lib/plugins/database/application/defines.dart
  frontend/appflowy_flutter/lib/plugins/database/application/row/row_cache.dart
  frontend/appflowy_flutter/lib/plugins/database/application/view/view_cache.dart
  frontend/appflowy_flutter/lib/plugins/database/board/application/board_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/board/presentation/board_page.dart
  frontend/appflowy_flutter/lib/plugins/database/calendar/application/calendar_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/calendar/application/unschedule_event_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/calendar/presentation/calendar_page.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/application/grid_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/grid_page.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/rust-lib/flowy-database2/src/entities/filter_entities/relation_filter.rs
  frontend/rust-lib/flowy-database2/src/entities/row_entities.rs
  frontend/rust-lib/flowy-database2/src/services/database_view/view_editor.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/checkbox_type_option/checkbox_filter.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/checklist_type_option/checklist_filter.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/date_type_option/date_filter.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/media_type_option/media_filter.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/number_type_option/number_filter.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/selection_type_option/select_filter.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/text_type_option/text_filter.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/time_type_option/time_filter.rs
  frontend/rust-lib/flowy-database2/src/services/filter/controller.rs
  frontend/rust-lib/flowy-database2/src/services/group/controller.rs
  frontend/rust-lib/flowy-database2/src/services/group/controller_impls/default_controller.rs
Labels: v0.7.2

#6447 fix: date issue when enbling time feild
  frontend/appflowy_flutter/integration_test/desktop/document/document_test_runner_1.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_test_runner_2.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_date_reminder_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_date_block.dart
Labels: v0.7.2

#6558 feat: turn into multiple lines
  frontend/appflowy_flutter/integration_test/desktop/document/document_option_action_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_option_cubit.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/draggable_option_button.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/appflowy_flutter/test/unit_test/document/turn_into/turn_into_test.dart
Labels: v0.7.2

#6529 feat: right click to open view more actions
  frontend/appflowy_flutter/integration_test/desktop/cloud/sidebar/sidebar_move_page_test.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_deletion_test.dart
  frontend/appflowy_flutter/integration_test/desktop/sidebar/sidebar_test.dart
  frontend/appflowy_flutter/integration_test/desktop/sidebar/sidebar_test_runner.dart
  frontend/appflowy_flutter/integration_test/desktop/sidebar/sidebar_view_item_test.dart
  frontend/appflowy_flutter/integration_test/shared/base.dart
  frontend/appflowy_flutter/integration_test/shared/common_operations.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/favorites/favorite_folder.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/favorites/favorite_more_actions.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/folder/_section_folder.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/move_to/move_page_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/shared_widget.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/draggable_view_item.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_more_action_button.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/pop_up_action.dart
  frontend/appflowy_flutter/packages/appflowy_popover/lib/src/layout.dart
  frontend/appflowy_flutter/packages/appflowy_popover/lib/src/popover.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/src/flowy_overlay/appflowy_popover.dart
Labels: v0.7.2

#6568 feat: observe mention block change and support block navigation
  frontend/appflowy_flutter/integration_test/desktop/cloud/document/document_copy_link_to_block_test.dart
  frontend/appflowy_flutter/lib/plugins/document/document.dart
  frontend/appflowy_flutter/lib/plugins/document/document_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/draggable_option_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_page_block.dart
  frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart
  frontend/appflowy_flutter/lib/workspace/application/action_navigation/navigation_action.dart
  frontend/appflowy_flutter/lib/workspace/application/view/view_ext.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/account/account_deletion.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.7.2

#6570 fix: space icon color assertion
  frontend/Makefile.toml
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/space_icon.dart
  frontend/appflowy_flutter/pubspec.yaml
  frontend/appflowy_flutter/test/widget_test/spae_cion_test.dart
Labels: v0.7.2

#6577 fix(flutter-desktop): launch review issues for 0.7.2
  frontend/appflowy_flutter/integration_test/desktop/database/database_calendar_test.dart
  frontend/appflowy_flutter/integration_test/desktop/database/database_filter_test.dart
  frontend/appflowy_flutter/integration_test/shared/database_test_op.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_filter_bottom_sheet.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_filter_condition_list.dart
  frontend/appflowy_flutter/lib/plugins/database/application/field/filter_entities.dart
  frontend/appflowy_flutter/lib/plugins/database/calendar/application/calendar_bloc.dart
  frontend/appflowy_flutter/lib/plugins/database/calendar/presentation/calendar_page.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/application/filter/select_option_loader.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/select_option/condition_list.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/select_option/option_list.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/filter/choicechip/select_option/select_option.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_row_detail/desktop_row_detail_checklist_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/checklist_cell_editor.dart
  frontend/appflowy_flutter/test/bloc_test/grid_test/filter/filter_entities_test.dart
  frontend/rust-lib/flowy-database2/src/entities/filter_entities/select_option_filter.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/selection_type_option/select_filter.rs
  frontend/rust-lib/flowy-database2/src/services/filter/entities.rs
  frontend/rust-lib/flowy-database2/tests/database/filter_test/select_option_filter_test.rs
  frontend/rust-lib/flowy-database2/tests/database/pre_fill_cell_test/pre_fill_row_according_to_filter_test.rs
Labels: v0.7.2

#6580 fix: bring back the board scrollbar
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.7.2

#6576 fix: turn into issues
  frontend/appflowy_flutter/integration_test/desktop/document/document_option_action_test.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_test_runner_1.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_option_cubit.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/draggable_option_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/draggable_option_button_feedback.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/option_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/cover_title_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_page_block.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/smart_edit_toolbar_item.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/test/unit_test/document/turn_into/turn_into_test.dart
  frontend/resources/translations/en.json
Labels: v0.7.2

#6586 fix: notifier disposed but in use
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/command_palette.dart
Labels: v0.7.2

#6589 fix: drag and drop row document full page
  frontend/appflowy_flutter/lib/plugins/database_document/database_document_page.dart
Labels: v0.7.2

#6588 fix: trash breadcrumb line height
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/view_title_bar.dart
Labels: v0.7.2

#6565 Update translations
  frontend/resources/translations/cs-CZ.json
  frontend/resources/translations/fa.json
  frontend/resources/translations/ja-JP.json
  frontend/resources/translations/tr-TR.json
  frontend/resources/translations/uk-UA.json
  frontend/resources/translations/vi-VN.json
  frontend/resources/translations/vi.json
Labels: translation, v0.7.2

#6567 feat: inline sub page mention
  frontend/appflowy_flutter/integration_test/desktop/document/document_inline_sub_page_test.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_test_runner_2.dart
  frontend/appflowy_flutter/integration_test/shared/common_operations.dart
  frontend/appflowy_flutter/integration_test/shared/document_test_operations.dart
  frontend/appflowy_flutter/lib/plugins/document/document_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_option_cubit.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/page_reference_commands.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_cut_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_paste_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/cover_title.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/child_page_transaction_handler.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_block.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_page_bloc.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_page_block.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/shared_context/shared_context.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/sub_page/sub_page_transaction_handler.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/transaction_handler/block_transaction_handler.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/transaction_handler/editor_transaction_handler.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/transaction_handler/editor_transaction_service.dart
  frontend/appflowy_flutter/lib/plugins/inline_actions/handlers/child_page.dart
  frontend/appflowy_flutter/lib/plugins/inline_actions/inline_actions_result.dart
  frontend/appflowy_flutter/lib/plugins/inline_actions/widgets/inline_actions_menu_group.dart
  frontend/appflowy_flutter/lib/shared/clipboard_state.dart
  frontend/appflowy_flutter/lib/shared/feature_flags.dart
  frontend/appflowy_flutter/lib/shared/text_field/text_filed_with_metric_lines.dart
  frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart
  frontend/appflowy_flutter/lib/workspace/application/view/view_ext.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/resources/flowy_icons/16x/child_page.svg
  frontend/resources/flowy_icons/16x/link_to_page.svg
  frontend/resources/translations/en.json
Labels: v0.7.2

#6590 fix: callout emoji size should follow the document font size
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/emoji_picker_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_component.dart
Labels: v0.7.2

#6594 fix: display paragraph mark only if the block content is empty
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_page_block.dart
Labels: v0.7.2

#6571 fix: show default view name
  frontend/appflowy_flutter/lib/mobile/application/notification/notification_reminder_bloc.dart
  frontend/appflowy_flutter/lib/mobile/presentation/page_item/mobile_view_item.dart
  frontend/appflowy_flutter/lib/plugins/document/document_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/insert_page_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/sub_page/sub_page_block_component.dart
  frontend/appflowy_flutter/lib/plugins/inline_actions/handlers/inline_page_reference.dart
  frontend/appflowy_flutter/lib/workspace/application/view/view_ext.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/recent_view_tile.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/more_view_actions/widgets/common_view_action.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/tab_bar_item.dart
Labels: v0.7.2

#6596 chore: update changelog
  CHANGELOG.md
Labels: v0.7.2

#6591 fix(flutter-mobile): edit primary field from database controls
  frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/widgets/option_text_field.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_full_field_editor.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/field/mobile_quick_field_editor.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_field_list.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/row/cells/mobile_cell_container.dart
Labels: v0.7.3

#6629 fix: crash on delete button press caused by GoRouter
  frontend/appflowy_flutter/lib/mobile/presentation/base/view_page/more_bottom_sheet.dart
  frontend/appflowy_flutter/lib/workspace/application/view/view_bloc.dart
Labels: v0.7.3

#6650 fix: macos arm64 build
  frontend/appflowy_flutter/macos/Runner.xcodeproj/project.pbxproj
Labels: v0.7.3

#6655 chore: update appflowy_editor version
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_date_reminder_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_page_block.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.7.3

#6658 chore(flutter_desktop): improve title and heading appearance
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/cover_title.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
Labels: v0.7.3

#6656 Added some missing GER (de-DE) translations.
  frontend/resources/translations/ar-SA.json
  frontend/resources/translations/ca-ES.json
  frontend/resources/translations/ckb-KU.json
  frontend/resources/translations/cs-CZ.json
  frontend/resources/translations/de-DE.json
  frontend/resources/translations/es-VE.json
  frontend/resources/translations/eu-ES.json
  frontend/resources/translations/fa.json
  frontend/resources/translations/fr-CA.json
  frontend/resources/translations/fr-FR.json
  frontend/resources/translations/he.json
  frontend/resources/translations/hu-HU.json
  frontend/resources/translations/id-ID.json
  frontend/resources/translations/it-IT.json
  frontend/resources/translations/ja-JP.json
  frontend/resources/translations/ko-KR.json
  frontend/resources/translations/pl-PL.json
  frontend/resources/translations/pt-BR.json
  frontend/resources/translations/pt-PT.json
  frontend/resources/translations/ru-RU.json
  frontend/resources/translations/sv-SE.json
  frontend/resources/translations/tr-TR.json
  frontend/resources/translations/uk-UA.json
  frontend/resources/translations/vi-VN.json
  frontend/resources/translations/vi.json
  frontend/resources/translations/zh-CN.json
  frontend/resources/translations/zh-TW.json
Labels: translation, v0.7.3

#6674 chore: drop down menu conforms to design
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_workspace_view.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/shared/af_dropdown_menu_entry.dart
Labels: v0.7.3

#6676 chore: capitalization for field editor insert left/right
  frontend/resources/translations/en.json
Labels: i18n, v0.7.3

#6667 feat: scroll to block after selecting notification item
  frontend/appflowy_flutter/lib/mobile/application/mobile_router.dart
  frontend/appflowy_flutter/lib/mobile/application/notification/notification_reminder_bloc.dart
  frontend/appflowy_flutter/lib/mobile/presentation/base/mobile_view_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/show_mobile_bottom_sheet.dart
  frontend/appflowy_flutter/lib/mobile/presentation/editor/mobile_editor_screen.dart
  frontend/appflowy_flutter/lib/mobile/presentation/notifications/widgets/notification_item.dart
  frontend/appflowy_flutter/lib/plugins/document/document.dart
  frontend/appflowy_flutter/lib/plugins/document/document_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_page_block.dart
  frontend/appflowy_flutter/lib/startup/tasks/generate_router.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.7.3

#6673 feat: enable link to database in slash menu
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/link_to_page_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/database/referenced_database_menu_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items.dart
Labels: v0.7.3
