Repository AppFlowy-IO/AppFlowy, pull requests merged in 2024-07, with the labels that each got.

#5664 chore: fix rustfmt ci test
  frontend/rust-lib/flowy-chat/src/local_ai/chat_plugin.rs
  frontend/rust-lib/flowy-chat/tests/util.rs
Labels: v0.6.2

#5644 feat: sync the documents and databases after batch importing documents and databases
  frontend/appflowy_flutter/lib/workspace/application/settings/share/import_service.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/import/import_panel.dart
  frontend/rust-lib/event-integration-test/src/folder_event.rs
  frontend/rust-lib/event-integration-test/tests/folder/local_test/import_test.rs
  frontend/rust-lib/flowy-core/src/deps_resolve/folder_deps.rs
  frontend/rust-lib/flowy-database2/src/manager.rs
  frontend/rust-lib/flowy-database2/src/services/share/csv/import.rs
  frontend/rust-lib/flowy-document/src/manager.rs
  frontend/rust-lib/flowy-folder/src/entities/import.rs
  frontend/rust-lib/flowy-folder/src/event_handler.rs
  frontend/rust-lib/flowy-folder/src/event_map.rs
  frontend/rust-lib/flowy-folder/src/manager.rs
  frontend/rust-lib/flowy-folder/src/share/import.rs
  frontend/rust-lib/flowy-folder/src/view_operation.rs
Labels: v0.6.2

#5665 feat: support moving page to a space
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/move_to/move_page_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/shared_widget.dart
  frontend/appflowy_tauri/src-tauri/Cargo.lock
  frontend/appflowy_tauri/src-tauri/Cargo.toml
  frontend/appflowy_web_app/src-tauri/Cargo.lock
  frontend/appflowy_web_app/src-tauri/Cargo.toml
  frontend/resources/translations/en.json
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
Labels: v0.6.2

#5663 chore: disable cloud search
  frontend/rust-lib/flowy-core/src/deps_resolve/search_deps.rs
Labels: v0.6.2

#5674 feat: sync the created view after duplicating
  frontend/appflowy_flutter/lib/workspace/application/sidebar/space/space_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/view/view_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/view/view_service.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_more_action_button.dart
  frontend/rust-lib/event-integration-test/src/folder_event.rs
  frontend/rust-lib/flowy-core/src/deps_resolve/folder_deps.rs
  frontend/rust-lib/flowy-database2/src/manager.rs
  frontend/rust-lib/flowy-folder/src/entities/view.rs
  frontend/rust-lib/flowy-folder/src/event_handler.rs
  frontend/rust-lib/flowy-folder/src/manager.rs
  frontend/rust-lib/flowy-folder/src/test_helper.rs
  frontend/rust-lib/flowy-folder/src/view_operation.rs
Labels: v0.6.2

#5676 fix: filter chat page when duplicating
  CHANGELOG.md
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/rust-lib/flowy-folder/src/manager.rs
Labels: bug, v0.6.2

#5686 chore: use latest macos runner to build the release package
  .github/workflows/release.yml
Labels: v0.6.3

#5700 fix: take the max value of the keyboard height and the view insets bottom to make the toolbar visible
  frontend/appflowy_flutter/integration_test/desktop/uncategorized/empty_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/appflowy_mobile_toolbar.dart
  frontend/appflowy_flutter/lib/workspace/application/home/home_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/menu/sidebar_sections_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/sidebar/space/space_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart
Labels: v0.6.3

#5701 chore: bump version 0.6.3
  CHANGELOG.md
  frontend/Makefile.toml
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.6.3

#5713 feat: enable debug logs in internal build
  frontend/appflowy_flutter/lib/env/env.dart
  frontend/appflowy_flutter/lib/plugins/document/application/document_bloc.dart
  frontend/appflowy_flutter/lib/plugins/document/application/document_data_pb_extension.dart
  frontend/appflowy_flutter/lib/plugins/document/application/editor_transaction_adapter.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/float_bubble/question_bubble.dart
Labels: v0.6.4

#5682 feat: render ai text message with appflowy_editor
  frontend/appflowy_flutter/integration_test/desktop/uncategorized/import_files_test.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/ai_message_bubble.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_welcome_page.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_markdown_text.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_text_message.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/user_text_message.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/markdown_code_parser.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/markdown_parsers.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/import/import_panel.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.6.4

#5677 FR: Users choose color from palette or picker #5041
  frontend/appflowy_flutter/lib/workspace/presentation/settings/shared/document_color_setting_button.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/resources/translations/en.json
Labels: v0.6.4

#5718 fix: syntax error when generating translation files
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_plan_comparison_dialog.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_plan_view.dart
  frontend/resources/translations/de-DE.json
  frontend/resources/translations/en.json
Labels: v0.6.4

#5712 feat: support sign-in and sign-up on Web
  frontend/appflowy_flutter/ios/Podfile.lock
  frontend/appflowy_flutter/lib/mobile/presentation/setting/about/about_setting_group.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/desktop_sign_in_screen.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/mobile_sign_in_screen.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/magic_link_sign_in_buttons.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/sign_in_agreement.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/widgets.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/shared_widget.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/dialogs.dart
  frontend/appflowy_web_app/package.json
  frontend/appflowy_web_app/pnpm-lock.yaml
  frontend/appflowy_web_app/src/application/database-yjs/selector.ts
  frontend/appflowy_web_app/src/application/db/tables/view_metas.ts
  frontend/appflowy_web_app/src/application/services/js-services/cache/__tests__/cache.test.ts
  frontend/appflowy_web_app/src/application/services/js-services/cache/index.ts
  frontend/appflowy_web_app/src/application/services/js-services/index.ts
  frontend/appflowy_web_app/src/application/services/js-services/wasm/client_api.ts
  frontend/appflowy_web_app/src/application/services/services.type.ts
  frontend/appflowy_web_app/src/application/services/tauri-services/index.ts
  frontend/appflowy_web_app/src/application/session/event.ts
  frontend/appflowy_web_app/src/application/session/index.ts
  frontend/appflowy_web_app/src/application/session/sign_in.ts
  frontend/appflowy_web_app/src/application/session/token.ts
  frontend/appflowy_web_app/src/assets/login.svg
  frontend/appflowy_web_app/src/assets/login/discord.svg
  frontend/appflowy_web_app/src/assets/login/github.svg
  frontend/appflowy_web_app/src/assets/login/google.svg
  frontend/appflowy_web_app/src/components/app/App.tsx
  frontend/appflowy_web_app/src/components/app/AppConfig.tsx
  frontend/appflowy_web_app/src/components/database/Database.tsx
  frontend/appflowy_web_app/src/components/database/DatabaseViews.tsx
  frontend/appflowy_web_app/src/components/database/components/board/card/Card.tsx
  frontend/appflowy_web_app/src/components/database/components/calendar/event/Event.tsx
  frontend/appflowy_web_app/src/components/database/components/calendar/event/EventPaper.tsx
  frontend/appflowy_web_app/src/components/database/components/cell/primary/PrimaryCell.tsx
  frontend/appflowy_web_app/src/components/database/components/grid/grid-table/GridTable.tsx
  frontend/appflowy_web_app/src/components/database/components/header/DatabaseHeader.tsx
  frontend/appflowy_web_app/src/components/database/components/tabs/DatabaseTabs.tsx
  frontend/appflowy_web_app/src/components/error/NotFound.tsx
  frontend/appflowy_web_app/src/components/login/Login.tsx
  frontend/appflowy_web_app/src/components/login/LoginAuth.tsx
  frontend/appflowy_web_app/src/components/login/LoginProvider.tsx
  frontend/appflowy_web_app/src/components/login/MagicLink.tsx
  frontend/appflowy_web_app/src/components/login/index.ts
  frontend/appflowy_web_app/src/components/publish/CollabView.tsx
  frontend/appflowy_web_app/src/components/publish/header/MoreActions.tsx
  frontend/appflowy_web_app/src/components/view-meta/ViewMetaPreview.tsx
  frontend/appflowy_web_app/src/pages/LoginPage.tsx
  frontend/resources/translations/en.json
Labels: v0.6.4

#5719 chore: bump version 0.6.4
  .github/workflows/release.yml
  CHANGELOG.md
  frontend/Makefile.toml
  frontend/appflowy_flutter/android/app/build.gradle
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.6.4

#5721 fix: ai chat result contains html escape text
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/ai_message_bubble.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_markdown_text.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/code_block/code_block_copy_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_paste_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/markdown_code_parser.dart
  frontend/appflowy_flutter/lib/shared/markdown_to_document.dart
  frontend/appflowy_flutter/lib/startup/tasks/app_window_size_manager.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/import/import_panel.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/shared/document_color_setting_button.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.6.4

#5725 chore: improve popup menu color
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/checklist_progress_bar.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/shared_widget.dart
Labels: bug, v0.6.4

#5726 feat: optimize the read recent views speed
  frontend/appflowy_flutter/ios/Podfile.lock
  frontend/appflowy_flutter/lib/mobile/presentation/home/recent_folder/mobile_home_recent_views.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/recent_folder/recent_space.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_grid/desktop_grid_text_cell.dart
  frontend/appflowy_flutter/lib/plugins/inline_actions/handlers/inline_page_reference.dart
  frontend/appflowy_flutter/lib/workspace/application/recent/cached_recent_service.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/recent_views_list.dart
  frontend/rust-lib/flowy-folder/src/entities/view.rs
  frontend/rust-lib/flowy-folder/src/event_handler.rs
  frontend/rust-lib/flowy-folder/src/event_map.rs
  frontend/rust-lib/flowy-folder/src/manager.rs
Labels: improvements, v0.6.4

#5737 fix: reset space relationship when clearing cache
  frontend/.vscode/launch.json
  frontend/appflowy_flutter/lib/plugins/database/application/tab_bar_bloc.dart
  frontend/appflowy_flutter/lib/shared/feature_flags.dart
  frontend/appflowy_flutter/lib/workspace/application/sidebar/space/space_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/view/view_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/view/view_service.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/shared_widget.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/fix_data_widget.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_manage_data_view.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/dialogs.dart
  frontend/appflowy_flutter/packages/appflowy_backend/lib/appflowy_backend.dart
  frontend/appflowy_flutter/packages/appflowy_backend/lib/log.dart
  frontend/appflowy_flutter/packages/appflowy_backend/pubspec.yaml
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/resources/translations/en.json
  frontend/rust-lib/flowy-folder/src/manager_observer.rs
Labels: v0.6.4

#5743 fix: improve color selector
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/shared_widget.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_workspace_view.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/shared/document_color_setting_button.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/dialogs.dart
  frontend/resources/translations/en.json
Labels: v0.6.4

#5744 chore: bump version 0.6.4
  CHANGELOG.md
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/cover/document_immersive_cover.dart
Labels: v0.6.4

#5722 chore: Update German translations for 0.6.4
  frontend/resources/translations/de-DE.json
  frontend/resources/translations/en.json
Labels: translation, v0.6.5

#5738 feat: Hebrew translation
  frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart
  frontend/appflowy_flutter/packages/flowy_infra/lib/language.dart
  frontend/resources/translations/he.json
  project.inlang/settings.json
Labels: translation, v0.6.5

#5727 Update translations
  frontend/resources/translations/zh-CN.json
Labels: translation, v0.6.5

#5742 Update translations - Es
  frontend/resources/translations/ar-SA.json
  frontend/resources/translations/ca-ES.json
  frontend/resources/translations/ckb-KU.json
  frontend/resources/translations/cs-CZ.json
  frontend/resources/translations/de-DE.json
  frontend/resources/translations/es-VE.json
  frontend/resources/translations/eu-ES.json
  frontend/resources/translations/fa.json
  frontend/resources/translations/fr-CA.json
  frontend/resources/translations/fr-FR.json
  frontend/resources/translations/hu-HU.json
  frontend/resources/translations/id-ID.json
  frontend/resources/translations/it-IT.json
  frontend/resources/translations/ja-JP.json
  frontend/resources/translations/ko-KR.json
  frontend/resources/translations/pl-PL.json
  frontend/resources/translations/pt-BR.json
  frontend/resources/translations/pt-PT.json
  frontend/resources/translations/sv-SE.json
  frontend/resources/translations/tr-TR.json
  frontend/resources/translations/uk-UA.json
  frontend/resources/translations/vi-VN.json
  frontend/resources/translations/vi.json
  frontend/resources/translations/zh-CN.json
  frontend/resources/translations/zh-TW.json
Labels: translation, v0.6.5

#5782 fix: delete reference databases in toggle list
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.6.5

#5800 chore: bump version 0.6.5
  CHANGELOG.md
  frontend/Makefile.toml
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.6.5

#5804 fix: integration test (reset to default location)
  frontend/appflowy_flutter/integration_test/shared/auth_operation.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_manage_data_view.dart
Labels: v0.6.6

#5806 fix: the action menu is blocked by the navigation bar on Android
  frontend/appflowy_flutter/lib/mobile/presentation/base/mobile_view_page.dart
Labels: v0.6.6

#5796 fix: defaultWindowSize is out of scope (#5795)
  frontend/appflowy_flutter/lib/startup/tasks/app_window_size_manager.dart
Labels: v0.6.6

#5792 chore: improve UI design on Desktop
  frontend/Makefile.toml
  frontend/appflowy_flutter/lib/core/frameless_window.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/calculations/calculate_cell.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/align_toolbar_item/align_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/smart_edit_node_widget.dart
  frontend/appflowy_flutter/lib/workspace/application/settings/appearance/desktop_appearance.dart
  frontend/appflowy_flutter/lib/workspace/application/settings/appearance/mobile_appearance.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/desktop_home_screen.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/home_layout.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/home_sizes.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/hotkeys.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/favorites/favorite_folder.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/favorites/favorite_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/favorites/favorite_pin_action.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/header/sidebar_top_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/move_to/move_page_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/shared/sidebar_new_page_button.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/_extension.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/create_space_popup.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/shared_widget.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space_header.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/space_action_type.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/space_icon_popup.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/space_more_popup.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_action_type.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_more_action_button.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/navigation.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_workspace_view.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/pop_up_action.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/sidebar_resizer.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/view_title_bar.dart
  frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/colorscheme.dart
  frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/dandelion.dart
  frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/default_colorscheme.dart
  frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/lavender.dart
  frontend/appflowy_flutter/packages/flowy_infra/lib/colorscheme/lemonade.dart
  frontend/appflowy_flutter/packages/flowy_infra/lib/theme_extension.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/flowy_infra_ui.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/src/flowy_overlay/appflowy_popover.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/button.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/decoration.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/divider.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/scrollbar.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/scrolling/styled_scroll_bar.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/widget/flowy_tooltip.dart
  frontend/appflowy_flutter/pubspec.yaml
  frontend/resources/flowy_icons/16x/favorite_section_pin.svg
  frontend/resources/flowy_icons/16x/favorite_section_unpin.svg
  frontend/resources/flowy_icons/16x/space_lock.svg
  frontend/resources/translations/en.json
Labels: v0.6.6

#5815 fix: chat messaage color doesn't update when switching theme
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_markdown_text.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/image_viewer/interactive_image_toolbar.dart
Labels: v0.6.6

#5824 fix: 0.6.6 launch review issues
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/auto_completion_node_widget.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/favorites/favorite_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/favorites/favorite_more_actions.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/sidebar_workspace.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_more_action_button.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/button.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text.dart
  frontend/appflowy_tauri/src-tauri/Cargo.lock
  frontend/appflowy_tauri/src-tauri/Cargo.toml
  frontend/appflowy_web_app/src-tauri/Cargo.lock
  frontend/appflowy_web_app/src-tauri/Cargo.toml
  frontend/resources/flowy_icons/16x/favorite_pin.svg
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
Labels: v0.6.6

#5822 Update tr-TR.json
  frontend/resources/translations/tr-TR.json
Labels: translation, v0.6.6

#5798 chore: update simplified Chinese translate
  frontend/resources/translations/zh-CN.json
Labels: translation, v0.6.6

#5825 fix: missing system font display
  frontend/appflowy_flutter/integration_test/shared/editor_test_operations.dart
  frontend/appflowy_flutter/integration_test/shared/settings.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/aa_menu/_font_item.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_account_view.dart
Labels: v0.6.6

#5832 chore: update collab
  frontend/appflowy_tauri/src-tauri/Cargo.lock
  frontend/appflowy_tauri/src-tauri/Cargo.toml
  frontend/appflowy_web_app/src-tauri/Cargo.lock
  frontend/appflowy_web_app/src-tauri/Cargo.toml
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
Labels: v0.6.6

#5830 fix: photo gallery improvements + launch review fixes
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_multi_image_block_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/multi_image_block_component/image_render.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/multi_image_block_component/layouts/image_browser_layout.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/multi_image_block_component/layouts/image_grid_layout.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/multi_image_block_component/layouts/multi_image_layouts.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/multi_image_block_component/multi_image_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/multi_image_block_component/multi_image_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/multi_image_block_component/multi_image_placeholder.dart
  frontend/appflowy_flutter/lib/plugins/inline_actions/widgets/inline_actions_handler.dart
  frontend/appflowy_flutter/lib/startup/deps_resolver.dart
  frontend/appflowy_flutter/lib/workspace/application/settings/ai/settings_ai_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/settings/settings_dialog_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/setting_ai_view/local_ai_setting.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/settings_dialog.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/setting_appflowy_cloud.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/image_viewer/interactive_image_toolbar.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/image_viewer/interactive_image_viewer.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/resources/flowy_icons/16x/close_viewer.svg
  frontend/resources/flowy_icons/16x/edit_layout.svg
  frontend/resources/flowy_icons/16x/photo_layout_browser.svg
  frontend/resources/flowy_icons/16x/photo_layout_grid.svg
  frontend/resources/translations/en.json
Labels: v0.6.6

#5835 feat: Chat app download
  frontend/appflowy_flutter/lib/workspace/application/settings/ai/download_offline_ai_app_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/settings/ai/local_ai_chat_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/settings/ai/plugin_state_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/shared_widget.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/setting_ai_view/init_local_ai.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/setting_ai_view/local_ai_chat_setting.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/setting_ai_view/plugin_state.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/setting_ai_view/settings_ai_view.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_billing_view.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_plan_view.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/dialogs.dart
  frontend/appflowy_tauri/src-tauri/Cargo.lock
  frontend/appflowy_tauri/src-tauri/Cargo.toml
  frontend/appflowy_web_app/src-tauri/Cargo.lock
  frontend/appflowy_web_app/src-tauri/Cargo.toml
  frontend/resources/translations/en.json
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
  frontend/rust-lib/flowy-chat-pub/src/cloud.rs
  frontend/rust-lib/flowy-chat/Cargo.toml
  frontend/rust-lib/flowy-chat/src/chat_manager.rs
  frontend/rust-lib/flowy-chat/src/entities.rs
  frontend/rust-lib/flowy-chat/src/event_handler.rs
  frontend/rust-lib/flowy-chat/src/event_map.rs
  frontend/rust-lib/flowy-chat/src/local_ai/local_llm_chat.rs
  frontend/rust-lib/flowy-chat/src/local_ai/local_llm_resource.rs
  frontend/rust-lib/flowy-chat/src/local_ai/mod.rs
  frontend/rust-lib/flowy-chat/src/local_ai/watch.rs
  frontend/rust-lib/flowy-core/src/deps_resolve/chat_deps.rs
  frontend/rust-lib/flowy-error/src/code.rs
  frontend/rust-lib/flowy-server/src/af_cloud/impls/user/cloud_service_impl.rs
Labels: v0.6.6

#5833 chore: bump version 0.6.6
  CHANGELOG.md
Labels: v0.6.6

#5837 chore: remove local ai
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/setting_ai_view/settings_ai_view.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_billing_view.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_plan_view.dart
Labels: v0.6.6

#5838 chore: use light haptic feedback
  frontend/appflowy_flutter/lib/mobile/presentation/base/gesture.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/space/mobile_space.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/tab/_tab_bar.dart
Labels: v0.6.6

#5844 fix: try to reopen the first workspace if the workspace deletion failed
  frontend/appflowy_flutter/lib/workspace/application/user/user_workspace_bloc.dart
  frontend/rust-lib/flowy-core/src/deps_resolve/user_deps.rs
Labels: v0.6.7
