Repository AppFlowy-IO/AppFlowy, pull requests merged in 2025-05, with the labels that each got.

#7891 refactor: view selector
  frontend/appflowy_flutter/lib/ai/ai.dart
  frontend/appflowy_flutter/lib/ai/service/view_selector_cubit.dart
  frontend/appflowy_flutter/lib/ai/widgets/prompt_input/select_sources_bottom_sheet.dart
  frontend/appflowy_flutter/lib/ai/widgets/prompt_input/select_sources_menu.dart
  frontend/appflowy_flutter/lib/ai/widgets/view_selector.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/ai_chat_prelude.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_message_selector_banner.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_message_action_bar.dart
Labels: v0.9.1

#7893 fix: select option logic
  frontend/rust-lib/flowy-database2/src/services/field/type_options/selection_type_option/mod.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/selection_type_option/multi_select_type_option.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/selection_type_option/select_option_tests.rs
  frontend/rust-lib/flowy-database2/src/services/field/type_options/selection_type_option/single_select_type_option.rs
  frontend/rust-lib/flowy-database2/tests/database/database_editor.rs
Labels: v0.9.2

#7894 feat: load custom prompts from a database
  frontend/appflowy_flutter/lib/ai/ai.dart
  frontend/appflowy_flutter/lib/ai/service/ai_entities.dart
  frontend/appflowy_flutter/lib/ai/service/ai_prompt_selector_cubit.dart
  frontend/appflowy_flutter/lib/ai/service/appflowy_ai_service.dart
  frontend/appflowy_flutter/lib/ai/widgets/ai_prompt_modal/ai_prompt_category_list.dart
  frontend/appflowy_flutter/lib/ai/widgets/ai_prompt_modal/ai_prompt_database_selector.dart
  frontend/appflowy_flutter/lib/ai/widgets/ai_prompt_modal/ai_prompt_modal.dart
  frontend/appflowy_flutter/lib/ai/widgets/ai_prompt_modal/ai_prompt_preview.dart
  frontend/appflowy_flutter/lib/ai/widgets/ai_prompt_modal/ai_prompt_visible_list.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_message_selector_banner.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_message_action_bar.dart
  frontend/resources/translations/en.json
  frontend/rust-lib/flowy-ai-pub/src/cloud.rs
  frontend/rust-lib/flowy-ai/Cargo.toml
  frontend/rust-lib/flowy-ai/src/ai_manager.rs
  frontend/rust-lib/flowy-ai/src/entities.rs
  frontend/rust-lib/flowy-ai/src/event_handler.rs
  frontend/rust-lib/flowy-ai/src/event_map.rs
  frontend/rust-lib/flowy-database-pub/Cargo.toml
  frontend/rust-lib/flowy-database2/Cargo.toml
  frontend/rust-lib/flowy-database2/src/entities/database_entities.rs
  frontend/rust-lib/flowy-database2/src/event_handler.rs
  frontend/rust-lib/flowy-database2/src/event_map.rs
  frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
Labels: v0.9.2

#7897 fix: selected sources changes not being reflected correctly
  frontend/appflowy_flutter/lib/ai/service/view_selector_cubit.dart
Labels: v0.9.2

#7902 chore: adjust database custom prompt ui
  frontend/appflowy_flutter/lib/ai/service/ai_prompt_selector_cubit.dart
  frontend/appflowy_flutter/lib/ai/widgets/ai_prompt_modal/ai_prompt_category_list.dart
  frontend/appflowy_flutter/lib/ai/widgets/ai_prompt_modal/ai_prompt_database_selector.dart
  frontend/appflowy_flutter/lib/ai/widgets/ai_prompt_modal/ai_prompt_modal.dart
  frontend/appflowy_flutter/lib/ai/widgets/ai_prompt_modal/ai_prompt_onboarding.dart
  frontend/appflowy_flutter/lib/ai/widgets/ai_prompt_modal/ai_prompt_visible_list.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/dialog_v2.dart
  frontend/resources/translations/en.json
  frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
Labels: v0.9.2

#7895 feat: desktop Search UI revamp
  frontend/appflowy_flutter/lib/ai/widgets/prompt_input/desktop_prompt_input.dart
  frontend/appflowy_flutter/lib/mobile/presentation/search/mobile_search_ask_ai_entrance.dart
  frontend/appflowy_flutter/lib/mobile/presentation/search/mobile_search_textfield.dart
  frontend/appflowy_flutter/lib/mobile/presentation/search/mobile_view_ancestors.dart
  frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/date_cell_editor_bloc.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/date_transaction_handler.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_date_block.dart
  frontend/appflowy_flutter/lib/plugins/trash/src/trash_cell.dart
  frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart
  frontend/appflowy_flutter/lib/workspace/application/command_palette/command_palette_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/command_palette/search_result_ext.dart
  frontend/appflowy_flutter/lib/workspace/application/recent/recent_views_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/command_palette.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/page_preview.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/recent_views_list.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/search_ask_ai_entrance.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/search_field.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/search_recent_view_cell.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/search_result_cell.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/search_results_list.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/search_summary_cell.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/scrollbar.dart
  frontend/resources/flowy_icons/20x/ai_searching_icon.svg
  frontend/resources/flowy_icons/20x/search_arrow_right.svg
  frontend/resources/flowy_icons/20x/search_clear.svg
  frontend/resources/flowy_icons/20x/search_icon.svg
  frontend/resources/translations/en.json
Labels: v0.9.2

#7913 chore: adjust view selector logic
  frontend/appflowy_flutter/lib/ai/service/view_selector_cubit.dart
  frontend/appflowy_flutter/lib/ai/widgets/ai_prompt_modal/ai_prompt_database_selector.dart
  frontend/appflowy_flutter/lib/ai/widgets/prompt_input/select_sources_bottom_sheet.dart
  frontend/appflowy_flutter/lib/ai/widgets/prompt_input/select_sources_menu.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_message_selector_banner.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_message_action_bar.dart
  frontend/appflowy_flutter/macos/Podfile.lock
Labels: v0.9.2

#7620 fix: drop files duplicates
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_drop_handler.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_drop_manager.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/file/file_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/image_placeholder.dart
Labels: v0.9.0

#7915 fix: the link name should be a required field
  frontend/appflowy_flutter/integration_test/desktop/document/document_toolbar_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/desktop_toolbar/link/link_extension.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/desktop_toolbar/link/link_hover_menu.dart
Labels: v0.9.2

#7914 fix: LR issues of desktop search
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/command_palette.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/page_preview.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/recent_views_list.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/search_result_cell.dart
  frontend/resources/flowy_icons/24x/something_wrong_warning.svg
  frontend/resources/translations/en-US.json
Labels: v0.9.2

#7916 fix: using the shortcut to show the search panel will hide the 'Ask AI anything' button
  frontend/appflowy_flutter/integration_test/desktop/cloud/cloud_runner.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/sidebar/sidebar_search_test.dart
  frontend/appflowy_flutter/integration_test/desktop/command_palette/command_palette_test.dart
  frontend/appflowy_flutter/lib/mobile/presentation/search/mobile_view_ancestors.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/command_palette.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/page_preview.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/recent_views_list.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/search_result_cell.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/search_results_list.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/desktop_home_screen.dart
Labels: v0.9.2

#7905 fix: allow ':keyword' make mistakes
  frontend/appflowy_flutter/lib/plugins/emoji/emoji_handler.dart
Labels: v0.9.2

#7926 chore: bump version 0.9.2
  frontend/Makefile.toml
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.9.2

#7930 chore: update CHANGELOG.md
  CHANGELOG.md
Labels: v0.9.2

#7939 fix: don't switch to space if on same space
  frontend/appflowy_flutter/lib/workspace/presentation/home/desktop_home_screen.dart
Labels: v0.9.3

#7938 feat: allow users to map fields while importing prompts from database
  frontend/appflowy_flutter/lib/ai/service/ai_entities.dart
  frontend/appflowy_flutter/lib/ai/service/ai_prompt_database_selector_cubit.dart
  frontend/appflowy_flutter/lib/ai/service/ai_prompt_selector_cubit.dart
  frontend/appflowy_flutter/lib/ai/service/appflowy_ai_service.dart
  frontend/appflowy_flutter/lib/ai/widgets/ai_prompt_modal/ai_prompt_database_modal.dart
  frontend/appflowy_flutter/lib/ai/widgets/ai_prompt_modal/ai_prompt_database_selector.dart
  frontend/appflowy_flutter/lib/ai/widgets/ai_prompt_modal/ai_prompt_modal.dart
  frontend/appflowy_flutter/lib/ai/widgets/ai_prompt_modal/ai_prompt_onboarding.dart
  frontend/appflowy_flutter/lib/ai/widgets/ai_prompt_modal/ai_prompt_preview.dart
  frontend/appflowy_flutter/lib/ai/widgets/ai_prompt_modal/ai_prompt_visible_list.dart
  frontend/appflowy_flutter/lib/ai/widgets/prompt_input/select_sources_menu.dart
  frontend/appflowy_flutter/lib/plugins/database/domain/field_service.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/component/popover/popover.dart
  frontend/resources/translations/en-US.json
  frontend/rust-lib/flowy-ai/src/ai_manager.rs
  frontend/rust-lib/flowy-ai/src/entities.rs
  frontend/rust-lib/flowy-ai/src/event_handler.rs
  frontend/rust-lib/flowy-ai/src/event_map.rs
  frontend/rust-lib/flowy-database2/src/entities/database_entities.rs
  frontend/rust-lib/flowy-database2/src/event_handler.rs
  frontend/rust-lib/flowy-database2/src/event_map.rs
  frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
Labels: v0.9.3

#7923 chore: implement custom prompt usage metrics
  frontend/appflowy_flutter/integration_test/shared/mock/mock_ai.dart
  frontend/appflowy_flutter/lib/ai/service/ai_prompt_input_bloc.dart
  frontend/appflowy_flutter/lib/ai/service/appflowy_ai_service.dart
  frontend/appflowy_flutter/lib/ai/widgets/prompt_input/desktop_prompt_input.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_bloc.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_stream_manager.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_page/chat_footer.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/ai_writer_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/operations/ai_writer_cubit.dart
  frontend/appflowy_flutter/test/bloc_test/ai_writer_test/ai_writer_bloc_test.dart
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
  frontend/rust-lib/event-integration-test/src/chat_event.rs
  frontend/rust-lib/event-integration-test/tests/chat/chat_message_test.rs
  frontend/rust-lib/flowy-ai-pub/src/cloud.rs
  frontend/rust-lib/flowy-ai/src/chat.rs
  frontend/rust-lib/flowy-ai/src/completion.rs
  frontend/rust-lib/flowy-ai/src/entities.rs
  frontend/rust-lib/flowy-ai/src/event_handler.rs
  frontend/rust-lib/flowy-ai/src/middleware/chat_service_mw.rs
  frontend/rust-lib/flowy-ai/src/offline/offline_message_sync.rs
  frontend/rust-lib/flowy-core/src/deps_resolve/cloud_service_impl.rs
  frontend/rust-lib/flowy-server/src/af_cloud/impls/chat.rs
  frontend/rust-lib/flowy-server/src/local_server/impls/chat.rs
Labels: v0.9.3

#7948 feat: shared folder refactor
  frontend/appflowy_flutter/lib/features/share_tab/data/repositories/local_share_with_user_repository.dart
  frontend/appflowy_flutter/lib/features/share_tab/data/repositories/rust_share_with_user_repository.dart
  frontend/appflowy_flutter/lib/features/share_tab/data/repositories/share_with_user_repository.dart
  frontend/appflowy_flutter/lib/features/share_tab/logic/share_with_user_bloc.dart
  frontend/appflowy_flutter/lib/features/shared_section/data/local_share_pages_repository.dart
  frontend/appflowy_flutter/lib/features/shared_section/data/rust_share_pagers_repository.dart
  frontend/appflowy_flutter/lib/features/shared_section/data/share_pages_repository.dart
  frontend/appflowy_flutter/lib/features/shared_section/logic/shared_section_bloc.dart
  frontend/appflowy_flutter/lib/features/shared_section/models/shared_page.dart
  frontend/appflowy_flutter/lib/features/shared_section/presentation/shared_section.dart
  frontend/appflowy_flutter/lib/features/shared_section/presentation/widgets/refresh_button.dart
  frontend/appflowy_flutter/lib/features/shared_section/presentation/widgets/shared_pages_list.dart
  frontend/appflowy_flutter/lib/features/shared_section/presentation/widgets/shared_section_error.dart
  frontend/appflowy_flutter/lib/features/shared_section/presentation/widgets/shared_section_header.dart
  frontend/appflowy_flutter/lib/features/shared_section/presentation/widgets/shared_section_loading.dart
  frontend/appflowy_flutter/lib/features/shared_section/util/extensions.dart
  frontend/appflowy_flutter/lib/plugins/shared/share/share_button.dart
  frontend/appflowy_flutter/lib/plugins/shared/share/share_menu.dart
  frontend/appflowy_flutter/lib/shared/feature_flags.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space.dart
  frontend/appflowy_flutter/test/bloc_test/lib/features/share_section/shared_section_bloc_test.dart
  frontend/appflowy_flutter/test/bloc_test/lib/features/share_tab/share_with_user_bloc_test.dart
  frontend/appflowy_flutter/test/widget_test/lib/features/share_section/refresh_button_test.dart
  frontend/appflowy_flutter/test/widget_test/lib/features/share_section/shared_pages_list_test.dart
  frontend/appflowy_flutter/test/widget_test/lib/features/share_section/shared_section_error_test.dart
  frontend/appflowy_flutter/test/widget_test/lib/features/share_section/shared_section_header_test.dart
  frontend/appflowy_flutter/test/widget_test/lib/features/share_section/shared_section_loading_test.dart
  frontend/appflowy_flutter/test/widget_test/lib/features/share_tab/copy_link_widget_test.dart
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/flowy-core/src/deps_resolve/cloud_service_impl.rs
  frontend/rust-lib/flowy-core/src/deps_resolve/folder_deps/mod.rs
  frontend/rust-lib/flowy-folder-pub/Cargo.toml
  frontend/rust-lib/flowy-folder-pub/src/cloud.rs
  frontend/rust-lib/flowy-folder-pub/src/lib.rs
  frontend/rust-lib/flowy-folder-pub/src/sql/mod.rs
  frontend/rust-lib/flowy-folder-pub/src/sql/workspace_shared_view_sql.rs
  frontend/rust-lib/flowy-folder-pub/src/workspace_shared_view_sql.rs
  frontend/rust-lib/flowy-folder/src/entities/view.rs
  frontend/rust-lib/flowy-folder/src/event_handler.rs
  frontend/rust-lib/flowy-folder/src/event_map.rs
  frontend/rust-lib/flowy-folder/src/manager.rs
  frontend/rust-lib/flowy-folder/src/notification.rs
  frontend/rust-lib/flowy-server/src/af_cloud/impls/folder.rs
  frontend/rust-lib/flowy-server/src/local_server/impls/folder.rs
  frontend/rust-lib/flowy-sqlite/migrations/2025-05-19-074647_create_shared_views_table/down.sql
  frontend/rust-lib/flowy-sqlite/migrations/2025-05-19-074647_create_shared_views_table/up.sql
  frontend/rust-lib/flowy-sqlite/src/schema.rs
Labels: v0.9.3

#7950 fix: desktop Search UI improvement
  frontend/appflowy_flutter/integration_test/desktop/document/document_toolbar_test.dart
  frontend/appflowy_flutter/lib/mobile/presentation/search/mobile_view_ancestors.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/cover/document_immersive_cover_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/command_palette/search_result_ext.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/command_palette.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/page_preview.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/recent_views_list.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/search_ask_ai_entrance.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/search_field.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/search_recent_view_cell.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/search_result_cell.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/search_results_list.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/search_special_styles.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/search_summary_cell.dart
  frontend/resources/flowy_icons/20x/search_open_tab.svg
Labels: v0.9.3

#7955 fix: make the link align center while sitename is empty
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/link_embed/link_embed_block_component.dart
Labels: v0.9.3

#7956 fix: clear cells not working
  frontend/appflowy_flutter/integration_test/desktop/database/database_field_test.dart
  frontend/appflowy_flutter/integration_test/shared/database_test_op.dart
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
  frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
Labels: v0.9.3

#7958 feat: turn guest into member
  frontend/appflowy_flutter/lib/features/share_tab/data/models/shared_user.dart
  frontend/appflowy_flutter/lib/features/share_tab/data/repositories/local_share_with_user_repository.dart
  frontend/appflowy_flutter/lib/features/share_tab/data/repositories/rust_share_with_user_repository.dart
  frontend/appflowy_flutter/lib/features/share_tab/data/repositories/share_with_user_repository.dart
  frontend/appflowy_flutter/lib/features/share_tab/logic/share_with_user_bloc.dart
  frontend/appflowy_flutter/lib/features/share_tab/presentation/share_tab.dart
  frontend/appflowy_flutter/lib/features/share_tab/presentation/widgets/people_with_access_section.dart
  frontend/appflowy_flutter/lib/features/share_tab/presentation/widgets/share_with_user_widget.dart
  frontend/appflowy_flutter/lib/features/shared_section/presentation/shared_section.dart
  frontend/appflowy_flutter/lib/features/util/extensions.dart
  frontend/appflowy_flutter/test/bloc_test/lib/features/share_tab/share_with_user_bloc_test.dart
Labels: v0.9.4

#7964 fix: LR issues
  frontend/appflowy_flutter/lib/mobile/presentation/search/mobile_search_ask_ai_entrance.dart
  frontend/appflowy_flutter/lib/mobile/presentation/search/mobile_search_cell.dart
  frontend/appflowy_flutter/lib/mobile/presentation/search/mobile_search_icon.dart
  frontend/appflowy_flutter/lib/mobile/presentation/search/mobile_search_result.dart
  frontend/appflowy_flutter/lib/mobile/presentation/search/mobile_search_textfield.dart
  frontend/appflowy_flutter/lib/mobile/presentation/search/mobile_view_ancestors.dart
  frontend/appflowy_flutter/lib/workspace/application/command_palette/command_palette_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/command_palette/search_result_ext.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/command_palette.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/page_preview.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/recent_views_list.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/search_field.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/search_icon.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/search_recent_view_cell.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/search_result_cell.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/search_results_list.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/search_summary_cell.dart
Labels: v0.9.3

#7971 fix: some search LR issues
  frontend/appflowy_flutter/lib/mobile/presentation/base/mobile_view_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/space/mobile_space_menu.dart
  frontend/appflowy_flutter/lib/mobile/presentation/search/mobile_search_ask_ai_entrance.dart
  frontend/appflowy_flutter/lib/mobile/presentation/search/mobile_search_cell.dart
  frontend/appflowy_flutter/lib/mobile/presentation/search/mobile_search_reference_bottom_sheet.dart
  frontend/appflowy_flutter/lib/mobile/presentation/search/mobile_search_result.dart
  frontend/appflowy_flutter/lib/mobile/presentation/search/mobile_search_special_styles.dart
  frontend/appflowy_flutter/lib/mobile/presentation/search/mobile_search_summary_cell.dart
  frontend/appflowy_flutter/lib/mobile/presentation/search/mobile_search_textfield.dart
  frontend/appflowy_flutter/lib/mobile/presentation/search/mobile_view_ancestors.dart
  frontend/appflowy_flutter/lib/mobile/presentation/search/view_ancestor_cache.dart
  frontend/appflowy_flutter/lib/startup/startup.dart
  frontend/appflowy_flutter/lib/startup/tasks/af_navigator_observer.dart
  frontend/appflowy_flutter/lib/startup/tasks/generate_router.dart
  frontend/appflowy_flutter/lib/workspace/application/action_navigation/action_navigation_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/command_palette/command_palette_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/sidebar/space/space_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/command_palette.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/navigation_bloc_extension.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/page_preview.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/recent_views_list.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/search_ask_ai_entrance.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/search_field.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/search_recent_view_cell.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/search_result_cell.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/search_results_list.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/search_special_styles.dart
  frontend/appflowy_flutter/lib/workspace/presentation/command_palette/widgets/search_summary_cell.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space_menu.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/scrollbar.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text_field.dart
  frontend/resources/flowy_icons/20x/search_icon.svg
  frontend/resources/translations/en-US.json
Labels: v0.9.3

#7966 chore: adjust custom prompt UI
  frontend/appflowy_flutter/lib/ai/service/ai_entities.dart
  frontend/appflowy_flutter/lib/ai/service/ai_prompt_selector_cubit.dart
  frontend/appflowy_flutter/lib/ai/widgets/ai_prompt_modal/ai_prompt_category_list.dart
  frontend/appflowy_flutter/lib/ai/widgets/ai_prompt_modal/ai_prompt_database_modal.dart
  frontend/appflowy_flutter/lib/ai/widgets/ai_prompt_modal/ai_prompt_preview.dart
  frontend/appflowy_flutter/lib/ai/widgets/ai_prompt_modal/ai_prompt_visible_list.dart
  frontend/appflowy_flutter/lib/ai/widgets/prompt_input/select_sources_bottom_sheet.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_markdown_text.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
  frontend/appflowy_flutter/lib/shared/easy_localiation_service.dart
  frontend/appflowy_flutter/lib/startup/deps_resolver.dart
  frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart
  frontend/resources/flowy_icons/20x/eraser.svg
  frontend/rust-lib/flowy-database2/src/services/database/database_editor.rs
Labels: v0.9.3

#7986 feat: add simple dropdown component
  frontend/appflowy_flutter/lib/mobile/presentation/search/mobile_search_icon.dart
  frontend/appflowy_flutter/packages/appflowy_ui/example/lib/main.dart
  frontend/appflowy_flutter/packages/appflowy_ui/example/lib/src/dropdown_menu/dropdown_menu_page.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/component/button/base_button/base_button.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/component/component.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/component/dropdown_menu/dropdown_menu.dart
Labels: v0.9.3

#7993 fix: make retry work in ai generated images
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/resizeable_image.dart
Labels: v0.9.3

#7989 chore: adjust database custom prompt ui
  frontend/appflowy_flutter/lib/ai/widgets/ai_prompt_modal/ai_prompt_database_modal.dart
  frontend/appflowy_flutter/lib/ai/widgets/ai_prompt_modal/ai_prompt_modal.dart
  frontend/appflowy_flutter/lib/ai/widgets/ai_prompt_modal/ai_prompt_visible_list.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/component/modal/modal.dart
Labels: v0.9.3

#7992 fix: workspace name conflicts
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_workspace_view.dart
Labels: v0.9.3

#7991 fix: database padding issue with max document width
  frontend/appflowy_flutter/lib/mobile/presentation/search/mobile_search_reference_bottom_sheet.dart
  frontend/appflowy_flutter/lib/plugins/database/board/presentation/widgets/board_hidden_groups.dart
  frontend/appflowy_flutter/lib/plugins/database/calendar/presentation/calendar_page.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/grid_page.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/header/grid_header.dart
  frontend/appflowy_flutter/lib/plugins/database/tab_bar/tab_bar_view.dart
Labels: v0.9.3

#7998 chore: update CHANGELOG.md
  CHANGELOG.md
Labels: v0.9.3

#7988 chore: bring back animated theme
  frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/appflowy_theme.dart
Labels: v0.9.4
