Repository AppFlowy-IO/AppFlowy, pull requests merged in 2025-01, with the labels that each got.

#7118 feat(flutter_desktop): add button to expand side peek
  frontend/appflowy_flutter/lib/workspace/application/tabs/tabs_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/home_stack.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/button.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/hover.dart
Labels: v0.8.0

#7121 feat(flutter_mobile): adjust bottom sheet quick action button style
  frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_view_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/board/widgets/group_card_header.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/mobile_card_detail_screen.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_view_quick_actions.dart
  frontend/appflowy_flutter/lib/mobile/presentation/widgets/flowy_mobile_quick_action_button.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_message_bubble.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/editable_cell_skeleton/url.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/add_attachment_item.dart
Labels: v0.8.0

#7129 chore: update ar-SA translations
  frontend/resources/translations/ar-SA.json
Labels: translation, v0.8.0

#7136 feat(flutter_desktop): save ai message to page improvements
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_select_sources_cubit.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/select_sources_bottom_sheet.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/select_sources_menu.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_message_action_bar.dart
  frontend/resources/translations/en.json
Labels: v0.8.0

#7135 fix: convert false value in attributes to null
  frontend/appflowy_flutter/lib/plugins/document/application/editor_transaction_adapter.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/home_stack.dart
  frontend/appflowy_flutter/test/unit_test/editor/transaction_adapter_test.dart
Labels: v0.8.0

#7127 fix: count title towards word count(#7042)
  frontend/appflowy_flutter/integration_test/desktop/document/document_more_actions_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/cover_title.dart
  frontend/appflowy_flutter/lib/shared/patterns/common_patterns.dart
  frontend/appflowy_flutter/lib/util/string_extension.dart
  frontend/appflowy_flutter/lib/workspace/application/view_info/view_info_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/more_view_actions/more_view_actions.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/more_view_actions/widgets/view_meta_info.dart
Labels: v0.8.0

#7137 fix: recent icon doesn't work in space icon (#7133)
  frontend/appflowy_flutter/integration_test/desktop/cloud/cloud_runner.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/sidebar/sidebar_icon_test.dart
  frontend/appflowy_flutter/integration_test/shared/emoji.dart
  frontend/appflowy_flutter/lib/mobile/presentation/base/mobile_view_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page_header.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/shared/mobile_page_card.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/emoji_icon_widget.dart
  frontend/appflowy_flutter/lib/shared/icon_emoji_picker/recent_icons.dart
  frontend/appflowy_flutter/lib/startup/tasks/generate_router.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/sidebar_space_header.dart
Labels: v0.8.0

#7138 fix: simple table issues and locale issues
  frontend/appflowy_flutter/lib/plugins/document/application/document_collaborators_bloc.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_drop_handler.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/util.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/visual_drag_area.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_more_action_popup.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/sub_page/sub_page_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toggle/toggle_block_component.dart
  frontend/appflowy_flutter/lib/plugins/inline_actions/handlers/date_reference.dart
  frontend/appflowy_flutter/lib/plugins/inline_actions/handlers/reminder_reference.dart
  frontend/appflowy_flutter/lib/workspace/application/settings/date_time/date_format_ext.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/draggable_item/draggable_item.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.8.0

#7061 feat: custom share url, publish url and copy link to share
  frontend/appflowy_flutter/integration_test/desktop/cloud/workspace/share_menu_test.dart
  frontend/appflowy_flutter/integration_test/desktop/settings/sign_in_page_settings_test.dart
  frontend/appflowy_flutter/lib/core/config/kv_keys.dart
  frontend/appflowy_flutter/lib/env/backend_env.dart
  frontend/appflowy_flutter/lib/env/cloud_env.dart
  frontend/appflowy_flutter/lib/env/env.dart
  frontend/appflowy_flutter/lib/mobile/presentation/setting/self_host/self_host_bottom_sheet.dart
  frontend/appflowy_flutter/lib/mobile/presentation/setting/self_host_setting_group.dart
  frontend/appflowy_flutter/lib/mobile/presentation/setting/widgets/mobile_setting_item_widget.dart
  frontend/appflowy_flutter/lib/plugins/shared/share/constants.dart
  frontend/appflowy_flutter/lib/shared/patterns/common_patterns.dart
  frontend/appflowy_flutter/lib/workspace/application/settings/appflowy_cloud_urls_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/settings_dialog.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/setting_appflowy_cloud.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/setting_cloud.dart
  frontend/resources/translations/en.json
Labels: v0.8.0

#7152 fix: filter out the space when opening new tab
  frontend/appflowy_flutter/integration_test/desktop/cloud/workspace/tabs_test.dart
  frontend/appflowy_flutter/lib/workspace/application/home/home_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/tabs/tabs_bloc.dart
Labels: v0.8.0

#7151 fix: context menu should not auto show when collaborating
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.8.0

#7128 feat(flutter): pre-defined response formats
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_bloc.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_entity.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/chat_mention_page_menu.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/desktop_ai_prompt_input.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/mobile_ai_prompt_input.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/predefined_format_buttons.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_related_question.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/layout_define.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_change_format_bottom_sheet.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_message_action_bar.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_message_bubble.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_text_message.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/custom_image_block_component/image_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/multi_image_block_component/layouts/image_browser_layout.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/resizeable_image.dart
  frontend/appflowy_flutter/lib/workspace/application/tabs/tabs_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/home_stack.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/image_viewer/image_provider.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/image_viewer/interactive_image_viewer.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/resources/flowy_icons/16x/ai_retry_filled.svg
  frontend/resources/flowy_icons/16x/ai_text_auto.svg
  frontend/resources/translations/en.json
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
  frontend/rust-lib/flowy-ai-pub/src/cloud.rs
  frontend/rust-lib/flowy-ai/src/ai_manager.rs
  frontend/rust-lib/flowy-ai/src/chat.rs
  frontend/rust-lib/flowy-ai/src/entities.rs
  frontend/rust-lib/flowy-ai/src/event_handler.rs
  frontend/rust-lib/flowy-ai/src/middleware/chat_service_mw.rs
  frontend/rust-lib/flowy-core/src/deps_resolve/cloud_service_impl.rs
  frontend/rust-lib/flowy-server/src/af_cloud/impls/chat.rs
  frontend/rust-lib/flowy-server/src/default_impl.rs
Labels: v0.8.0

#7169 chore: enable AI seach
  frontend/appflowy_flutter/lib/env/cloud_env.dart
  frontend/appflowy_flutter/lib/env/env.dart
  frontend/appflowy_flutter/lib/plugins/shared/share/constants.dart
  frontend/appflowy_flutter/lib/shared/patterns/common_patterns.dart
  frontend/appflowy_flutter/lib/workspace/application/command_palette/command_palette_bloc.dart
  frontend/rust-lib/flowy-core/src/deps_resolve/search_deps.rs
  frontend/rust-lib/flowy-search/src/document/handler.rs
Labels: v0.8.0

#7173 fix: filter the search results by duplicate ids
  frontend/appflowy_flutter/integration_test/desktop/cloud/workspace/workspace_settings_test.dart
  frontend/appflowy_flutter/integration_test/desktop/settings/shortcuts_settings_test.dart
  frontend/appflowy_flutter/lib/workspace/application/command_palette/command_palette_bloc.dart
Labels: v0.8.0

#7167 chore: update ja-JP translations
  frontend/resources/translations/ja-JP.json
Labels: translation, v0.8.0

#7166 chore: update fr-CA translations
  frontend/resources/translations/fr-CA.json
  frontend/resources/translations/fr-FR.json
Labels: translation, v0.8.0

#7161 Update translations for ko-KR
  frontend/resources/translations/ko-KR.json
Labels: translation, v0.8.0

#7163 fix: can not check text direction automatically on mobile(#7092)
  frontend/appflowy_flutter/integration_test/mobile/settings/default_text_direction_test.dart
  frontend/appflowy_flutter/integration_test/mobile_runner_1.dart
  frontend/appflowy_flutter/lib/mobile/presentation/setting/appearance/rtl_setting.dart
  frontend/appflowy_flutter/lib/workspace/application/settings/appearance/appearance_cubit.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_workspace_view.dart
  frontend/appflowy_flutter/test/widget_test/direction_setting_test.dart
Labels: v0.8.0

#7142 fix: navigation bar issue on linked pages(#7111)
  frontend/appflowy_flutter/integration_test/desktop/document/document_sub_page_test.dart
  frontend/appflowy_flutter/integration_test/desktop/sidebar/sidebar_expand_test.dart
  frontend/appflowy_flutter/lib/startup/startup.dart
  frontend/appflowy_flutter/lib/util/expand_views.dart
  frontend/appflowy_flutter/lib/workspace/application/tabs/tabs_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/view/view_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/folder/_section_folder.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
Labels: v0.8.0

#7174 feat: resize table column width on mobile
  frontend/appflowy_flutter/integration_test/mobile/document/simple_table_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_cell_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_constants.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_style_operation.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_column_resize_handle.dart
Labels: v0.8.0

#7177 fix: remove error message when sending a new message
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_bloc.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_message_stream.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_text_message.dart
Labels: v0.8.0

#7196 fix: search results were filtered accidentally
  frontend/rust-lib/flowy-search/src/document/handler.rs
Labels: v0.8.1

#7189 fix: icons not display in search results
  frontend/appflowy_flutter/integration_test/desktop/command_palette/folder_search_test.dart
  frontend/appflowy_flutter/integration_test/desktop/sidebar/sidebar_recent_icon_test.dart
  frontend/appflowy_flutter/integration_test/desktop/sidebar/sidebar_test_runner.dart
  frontend/appflowy_flutter/integration_test/shared/emoji.dart
  frontend/appflowy_flutter/lib/shared/icon_emoji_picker/icon_picker.dart
  frontend/appflowy_flutter/lib/shared/icon_emoji_picker/recent_icons.dart
  frontend/appflowy_flutter/lib/workspace/application/command_palette/search_result_ext.dart
  frontend/appflowy_flutter/test/unit_test/util/recent_icons_test.dart
Labels: v0.8.1

#7195 fix: retry count should be clear if the value exceeds max retries
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/custom_image_block_component/custom_image_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/resizeable_image.dart
  frontend/appflowy_flutter/lib/shared/appflowy_network_image.dart
  frontend/appflowy_flutter/test/unit_test/image/appflowy_network_image_test.dart
Labels: v0.8.1

#7198 chore: allow customize that forces distribute column widths
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_markdown_text.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_cell_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_row_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/_desktop_simple_table_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/_mobile_simple_table_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_widgets/simple_table_widget.dart
Labels: v0.8.1

#7199 chore: remove iconContent from IconsData
  frontend/appflowy_flutter/integration_test/desktop/cloud/sidebar/sidebar_icon_test.dart
  frontend/appflowy_flutter/integration_test/desktop/command_palette/folder_search_test.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_callout_test.dart
  frontend/appflowy_flutter/integration_test/shared/common_operations.dart
  frontend/appflowy_flutter/integration_test/shared/emoji.dart
  frontend/appflowy_flutter/integration_test/shared/expectation.dart
  frontend/appflowy_flutter/lib/plugins/base/icon/icon_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/emoji_icon_widget.dart
  frontend/appflowy_flutter/lib/shared/icon_emoji_picker/icon_picker.dart
Labels: v0.8.1

#7185 fix: launch review 0.8.1
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/animated_chat_list.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/desktop_ai_prompt_input.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/mobile_ai_prompt_input.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/predefined_format_buttons.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/layout_define.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_change_format_bottom_sheet.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_message_action_bar.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/file/file_selection_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/image_selection_menu.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/resources/flowy_icons/16x/ai_image.svg
  frontend/resources/flowy_icons/16x/ai_text_image.svg
  frontend/resources/translations/en.json
Labels: v0.8.1

#7208 chore: update plan desc
  frontend/resources/translations/ar-SA.json
  frontend/resources/translations/de-DE.json
  frontend/resources/translations/en.json
  frontend/resources/translations/fr-FR.json
  frontend/resources/translations/ja-JP.json
  frontend/resources/translations/ru-RU.json
  frontend/resources/translations/th-TH.json
  frontend/resources/translations/tr-TR.json
  frontend/resources/translations/uk-UA.json
  frontend/resources/translations/vi-VN.json
Labels: v0.8.1

#7207 fix: message scrolling
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/animated_chat_list.dart
Labels: v0.8.1

#7210 Update translations
  frontend/resources/translations/ar-SA.json
  frontend/resources/translations/fr-FR.json
Labels: translation, v0.8.1

#7209 chore: update CHANGELOG.md
  CHANGELOG.md
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_image_block_test.dart
  frontend/appflowy_flutter/integration_test/desktop/settings/shortcuts_settings_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/custom_image_block_component/custom_image_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/custom_image_block_component/image_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/shortcuts/backspace_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/shortcuts/command_shortcuts.dart
Labels: v0.8.1

#7206 chore: reorganize code
  frontend/appflowy_flutter/integration_test/shared/mock/mock_openai_repository.dart
  frontend/appflowy_flutter/lib/ai/ai.dart
  frontend/appflowy_flutter/lib/ai/service/ai_client.dart
  frontend/appflowy_flutter/lib/ai/service/appflowy_ai_service.dart
  frontend/appflowy_flutter/lib/ai/service/error.dart
  frontend/appflowy_flutter/lib/ai/service/openai_client.dart
  frontend/appflowy_flutter/lib/ai/service/text_completion.dart
  frontend/appflowy_flutter/lib/ai/widgets/loading_indicator.dart
  frontend/appflowy_flutter/lib/ai/widgets/prompt_input/action_buttons.dart
  frontend/appflowy_flutter/lib/ai/widgets/prompt_input/desktop_input_text_field.dart
  frontend/appflowy_flutter/lib/ai/widgets/prompt_input/file_attachment_list.dart
  frontend/appflowy_flutter/lib/ai/widgets/prompt_input/layout_define.dart
  frontend/appflowy_flutter/lib/ai/widgets/prompt_input/mention_page_bottom_sheet.dart
  frontend/appflowy_flutter/lib/ai/widgets/prompt_input/mention_page_menu.dart
  frontend/appflowy_flutter/lib/ai/widgets/prompt_input/mentioned_page_text_span.dart
  frontend/appflowy_flutter/lib/ai/widgets/prompt_input/predefined_format_buttons.dart
  frontend/appflowy_flutter/lib/ai/widgets/prompt_input/select_sources_bottom_sheet.dart
  frontend/appflowy_flutter/lib/ai/widgets/prompt_input/select_sources_menu.dart
  frontend/appflowy_flutter/lib/ai/widgets/prompt_input/send_button.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_avatar.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/desktop_chat_input.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/mobile_chat_input.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/layout_define.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_message_action_bar.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_message_bubble.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_text_message.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/user_message_bubble.dart
  frontend/appflowy_flutter/lib/plugins/document/application/editor_transaction_adapter.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/ai_writer_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/ask_ai_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/ask_ai_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/util/ask_ai_node_extension.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/util/learn_more_action.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/widgets/ai_limit_dialog.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/widgets/ai_writer_block_operations.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/widgets/ai_writer_block_widgets.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/widgets/ask_ai_action.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/widgets/ask_ai_action_bloc.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/widgets/ask_ai_block_widgets.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/widgets/barrier_dialog.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/widgets/discard_dialog.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/ask_ai_action.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/openai/widgets/barrier_dialog.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/plugins.dart
  frontend/appflowy_flutter/lib/startup/deps_resolver.dart
  frontend/appflowy_flutter/test/bloc_test/ask_ai_test/ask_ai_action_bloc_test.dart
Labels: v0.8.2

#7228 fix: pass alwaysDistributeColumnWidths to simple table block
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
Labels: v0.8.2

#7216 chore: update ar-SA translations
  frontend/resources/translations/ar-SA.json
Labels: translation

#7224 feat: save multiple messages to a page
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_edit_document_service.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_member_bloc.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_select_message_bloc.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/chat.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_avatar.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/desktop_chat_input.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_message_selector_banner.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_message_action_bar.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_message_bubble.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_text_message.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/message_util.dart
  frontend/appflowy_flutter/lib/plugins/database/tab_bar/tab_bar_view.dart
  frontend/appflowy_flutter/lib/workspace/application/view/view_ext.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/home_stack.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/more_view_actions/more_view_actions.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/more_view_actions/widgets/common_view_action.dart
  frontend/resources/flowy_icons/16x/checkbox_ai_empty.svg
  frontend/resources/flowy_icons/16x/checkbox_ai_minus.svg
  frontend/resources/flowy_icons/16x/checkbox_ai_selected.svg
  frontend/resources/translations/en.json
Labels: v0.8.2

#7233 fix: remove app from homepage url
  frontend/appflowy_flutter/integration_test/desktop/cloud/workspace/workspace_settings_test.dart
  frontend/appflowy_flutter/lib/plugins/document/document_page.dart
  frontend/appflowy_flutter/lib/plugins/shared/share/constants.dart
Labels: v0.8.2

#7242 chore: trim markdown text
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_markdown_text.dart
  frontend/rust-lib/flowy-ai/src/chat.rs
Labels: v0.8.2

#7243 chore: bump table column width when saving chat message to page
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_edit_document_service.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_message_action_bar.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/markdown_simple_table_parser.dart
  frontend/appflowy_flutter/lib/shared/markdown_to_document.dart
  frontend/appflowy_flutter/test/unit_test/simple_table/simple_table_markdown_test.dart
Labels: v0.8.2

#7245 fix: the cursor constantly blinking on Android
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.8.1

#7215 fix: use scale factor to zoom mobile(#7201)
  frontend/appflowy_flutter/integration_test/mobile/settings/scale_factor_test.dart
  frontend/appflowy_flutter/integration_test/shared/base.dart
  frontend/appflowy_flutter/lib/mobile/presentation/setting/appearance/text_scale_setting.dart
Labels: v0.8.2

#7187 feat: enable set customized icons for database views
  frontend/appflowy_flutter/integration_test/desktop/database/database_icon_test.dart
  frontend/appflowy_flutter/integration_test/desktop_runner_9.dart
  frontend/appflowy_flutter/integration_test/shared/emoji.dart
  frontend/appflowy_flutter/lib/mobile/application/mobile_router.dart
  frontend/appflowy_flutter/lib/mobile/presentation/base/mobile_view_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/base/view_page/app_bar_buttons.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/card/card_detail/widgets/row_page_button.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_view_list.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_view_quick_actions.dart
  frontend/appflowy_flutter/lib/mobile/presentation/editor/mobile_editor_screen.dart
  frontend/appflowy_flutter/lib/mobile/presentation/page_item/mobile_view_item.dart
  frontend/appflowy_flutter/lib/plugins/base/emoji/emoji_text.dart
  frontend/appflowy_flutter/lib/plugins/database/tab_bar/desktop/tab_bar_header.dart
  frontend/appflowy_flutter/lib/plugins/database/tab_bar/mobile/mobile_tab_bar_header.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/emoji_icon_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/page_style/_page_style_icon.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/page_style/page_style_bottom_sheet.dart
  frontend/appflowy_flutter/lib/shared/icon_emoji_picker/icon_picker.dart
  frontend/appflowy_flutter/lib/shared/icon_emoji_picker/recent_icons.dart
  frontend/appflowy_flutter/lib/startup/tasks/generate_router.dart
Labels: v0.8.2

#7247 feat: support pasting table from notion, google docs and google sheet
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/paste_from_html.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/appflowy_flutter/test/unit_test/document/html/_html_samples.dart
  frontend/appflowy_flutter/test/unit_test/document/html/paste_from_html_test.dart
Labels: v0.8.2

#7249 chore: bump client api
  frontend/appflowy_flutter/integration_test/desktop/cloud/workspace/workspace_settings_test.dart
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
  frontend/rust-lib/flowy-server/src/af_cloud/impls/folder.rs
Labels: v0.8.2

#7236 feat: support custom image icon
  frontend/appflowy_flutter/integration_test/desktop/sidebar/sidebar_icon_test.dart
  frontend/appflowy_flutter/integration_test/mobile/document/icon_test.dart
  frontend/appflowy_flutter/integration_test/shared/common_operations.dart
  frontend/appflowy_flutter/integration_test/shared/emoji.dart
  frontend/appflowy_flutter/integration_test/shared/expectation.dart
  frontend/appflowy_flutter/lib/mobile/application/mobile_router.dart
  frontend/appflowy_flutter/lib/mobile/presentation/base/mobile_view_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/base/view_page/app_bar_buttons.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/section_folder/mobile_home_section_folder.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/shared/mobile_page_card.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/space/mobile_space.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/tab/mobile_space_tab.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_select_message_bloc.dart
  frontend/appflowy_flutter/lib/plugins/base/emoji/emoji_picker_screen.dart
  frontend/appflowy_flutter/lib/plugins/document/document.dart
  frontend/appflowy_flutter/lib/plugins/document/document_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/emoji_picker_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/cover/document_immersive_cover.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/document_cover_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/emoji_icon_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_page_block.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/page_style/_page_style_icon.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/page_style/_page_style_icon_bloc.dart
  frontend/appflowy_flutter/lib/shared/icon_emoji_picker/flowy_icon_emoji_picker.dart
  frontend/appflowy_flutter/lib/shared/icon_emoji_picker/icon_uploader.dart
  frontend/appflowy_flutter/lib/shared/icon_emoji_picker/tab.dart
  frontend/appflowy_flutter/lib/startup/tasks/generate_router.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_more_action_button.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/rename_view_popover.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/view_title_bar.dart
Labels: v0.8.2

#7251 chore: only enable document integrity check when enableDocumentInternalLog is on
  frontend/appflowy_flutter/lib/plugins/document/application/document_bloc.dart
  frontend/appflowy_flutter/lib/plugins/document/application/document_collab_adapter.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/paste_from_html.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/keyboard_interceptor/keyboard_interceptor.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/appflowy_flutter/test/unit_test/document/html/_html_samples.dart
  frontend/appflowy_flutter/test/unit_test/document/html/paste_from_html_test.dart
Labels: v0.8.2

#7262 chore: support pasting image links that have no file extension
  frontend/appflowy_flutter/integration_test/desktop/document/document_copy_and_paste_test.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_message_action_bar.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_paste_command.dart
  frontend/appflowy_flutter/lib/shared/patterns/common_patterns.dart
Labels: v0.8.2

#7266 fix: v0.8.2 launch review issues
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/paste_from_html.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/paste_from_in_app_json.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/shortcuts/command_shortcuts.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/shortcuts/custom_delete_command.dart
  frontend/appflowy_flutter/lib/shared/patterns/common_patterns.dart
  frontend/appflowy_flutter/test/unit_test/document/html/_html_samples.dart
  frontend/appflowy_flutter/test/unit_test/document/html/paste_from_html_test.dart
Labels: v0.8.2

#7267 chore: rename [Font Scale Factor] to [Display Size]
  frontend/appflowy_flutter/lib/mobile/presentation/setting/appearance/appearance_setting_group.dart
  frontend/appflowy_flutter/lib/mobile/presentation/setting/appearance/text_scale_setting.dart
  frontend/resources/translations/en.json
Labels: v0.8.2

#7257 chore: cancel button not visible in [Reset to Default] for shortcuts(#7171)
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_shortcuts_view.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/shared/settings_alert_dialog.dart
Labels: v0.8.2

#7260 New Arabic Translations
  frontend/resources/translations/ar-SA.json
Labels: translation, v0.8.2

#7276 chore: update CHANGELOG.md
  CHANGELOG.md
Labels: v0.8.2

#7274 fix(flutter_mobile): drop focus on tap outside
  frontend/appflowy_flutter/ios/Podfile.lock
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/mobile_chat_input.dart
Labels: v0.8.3
