Repository AppFlowy-IO/AppFlowy, pull requests merged in 2025-03, with the labels that each got.

#7439 fix: the locked hint is not visible when there's a cover
  frontend/appflowy_flutter/lib/mobile/presentation/base/mobile_view_page.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/view_title_bar.dart
  frontend/resources/flowy_icons/16x/lock_page_fill.svg
Labels: v0.8.5

#7432 fix: potential issues with displaying CircleAvatar
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/user_avatar.dart
Labels: v0.8.5

#7441 fix: can't open the relation field in the linked database
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_grid/desktop_grid_relation_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_row_detail/desktop_row_detail_relation_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/relation_cell_editor.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/row/relation_row_detail.dart
Labels: v0.8.5

#7440 fix: error display when showing SnackBar with dialog
  frontend/appflowy_flutter/lib/plugins/database/widgets/row/row_detail.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/multi_image_block_component/multi_image_menu.dart
Labels: v0.8.5

#7442 fix: unable to delete the callout block when it's in the first line
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_component.dart
Labels: v0.8.5

#7443 fix: hide the improve writing button
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/util.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items/simple_columns_item.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.8.5

#7445 Fix/launch review 0.8.5
  frontend/appflowy_flutter/lib/ai/service/ai_prompt_input_bloc.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_related_question.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/ai_writer_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/ai_writer_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/operations/ai_writer_cubit.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/operations/ai_writer_entities.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/markdown_text_robot.dart
  frontend/rust-lib/flowy-ai/src/completion.rs
Labels: v0.8.5

#7451 chore: update changelog
  CHANGELOG.md
Labels: v0.8.5

#7473 chore: bump version 0.8.6 & update changelog
  CHANGELOG.md
  frontend/Makefile.toml
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.8.6

#7479 feat: support nested list in callout block and quote block
  frontend/appflowy_flutter/lib/plugins/document/application/document_data_pb_extension.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_option_cubit.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/util.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/option/option_actions.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/option/turn_into_option_action.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/ai_writer_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_shortcuts.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/columns/simple_column_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/columns/simple_columns_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/database/database_view_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/error/error_block_component_builder.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/file/file_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/custom_image_block_component/custom_image_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/multi_image_block_component/multi_image_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/math_equation/math_equation_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/migration/editor_migration.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/aa_menu/_block_items.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/add_block_menu_item_builder.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/numbered_list/numbered_list_icon.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/outline/outline_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/page_block/custom_page_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/plugins.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/quote/quote_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/quote/quote_block_shortcuts.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_cell_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_row_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/sub_page/sub_page_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toggle/toggle_block_component.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/appflowy_flutter/test/unit_test/document/turn_into/turn_into_test.dart
Labels: v0.8.7

#7449 feat: support custom icons for callout
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/emoji_picker_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_component.dart
Labels: v0.8.7

#7491 fix: callout block build error
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_component.dart
Labels: v0.8.7

#7493 feat: make the columns block same width width the editor
  frontend/appflowy_flutter/lib/plugins/document/application/document_rules.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/draggable_option_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/util.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/columns/simple_column_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/columns/simple_column_block_width_resizer.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/columns/simple_column_node_extension.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/columns/simple_columns_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/custom_image_block_component/custom_image_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/outline/outline_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items/simple_columns_item.dart
Labels: v0.8.7

#7496 feat: ensure the ai writer block visible when generating result
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.8.7

#7490 fix: don't include icon while exporting callout to md
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/callout_node_parser.dart
Labels: v0.8.7

#7508 fix: remove layout builder in quote block
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/columns/simple_columns_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/quote/quote_block_component.dart
  frontend/appflowy_flutter/macos/Podfile.lock
Labels: v0.8.7

#7518 chore: disable add messages to page when chat is empty
  frontend/appflowy_flutter/lib/plugins/ai_chat/application/chat_select_message_bloc.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/chat.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_message_selector_banner.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/more_view_actions/widgets/common_view_action.dart
Labels: v0.8.7

#7497 fix: emoji picker position error
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/emoji_icon_widget.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/emoji_picker/emoji_menu_item.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/emoji_picker/emoji_shortcut_event.dart
Labels: v0.8.7

#7492 fix: the slash menu position sometimes is wrong with auto scrolling
  frontend/appflowy_flutter/lib/mobile/presentation/selection_menu/mobile_selection_menu.dart
Labels: v0.8.7

#7525 fix: unable to paste iframe in editor
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/paste_from_plain_text.dart
Labels: v0.8.7

#7528 chore: update dsa_pub.pem on Windows
  frontend/appflowy_flutter/dsa_pub.pem
Labels: v0.8.7

#7534 fix: stop generating in ai chat and writer
  frontend/appflowy_flutter/lib/ai/widgets/prompt_input/send_button.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
  frontend/resources/translations/en.json
Labels: v0.8.7

#7535 fix: continue writing edge case
  frontend/appflowy_flutter/lib/plugins/document/document_page.dart
Labels: v0.8.7

#7536 chore: add tooltip for disabled select messages
  frontend/appflowy_flutter/lib/plugins/ai_chat/chat.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/more_view_actions/widgets/common_view_action.dart
  frontend/resources/translations/en.json
Labels: v0.8.7

#7533 chore: use tooltip instead of multi line for related questions
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_related_question.dart
Labels: v0.8.7

#7543 chore: update unsplash client
  frontend/appflowy_flutter/macos/Podfile.lock
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.8.7

#7540 fix: the workflow of switching to Local in app
  frontend/appflowy_flutter/lib/env/cloud_env.dart
  frontend/appflowy_flutter/lib/mobile/presentation/setting/cloud/appflowy_cloud_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/undo_redo/custom_undo_redo_commands.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/mobile_sign_in_screen.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/anonymous_sign_in_button.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/sign_in_agreement.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/sign_in_anonymous_button.dart
  frontend/appflowy_flutter/macos/Podfile.lock
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/resources/translations/en.json
Labels: v0.8.7

#7552 fix: message hover action flashing
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_message_bubble.dart
Labels: v0.8.7

#7553 fix: quote block flashes on the AI chat page while generating an answer.
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_markdown_text.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/quote/quote_block_component.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.8.7

#7555 fix: first added cover might be invisible
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/cover/document_immersive_cover_bloc.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/document_cover_widget.dart
Labels: v0.8.7

#7557 chore: update template link url
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/footer/sidebar_footer.dart
Labels: v0.8.7

#7532 fix: some launch review issues
  frontend/appflowy_flutter/integration_test/desktop/document/document_option_action_test.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_inline_math_equation_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_option_cubit.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/option/turn_into_option_action.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/ai_writer_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/operations/ai_writer_entities.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/desktop_toolbar/desktop_floating_toolbar.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/desktop_toolbar/toolbar_animation.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items/todo_list_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toggle/toggle_block_shortcuts.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toolbar_item/custom_format_toolbar_items.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toolbar_item/custom_hightlight_color_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toolbar_item/custom_link_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toolbar_item/custom_placeholder_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toolbar_item/custom_text_align_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toolbar_item/custom_text_color_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toolbar_item/more_option_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toolbar_item/text_heading_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toolbar_item/text_suggestions_toolbar_item.dart
  frontend/appflowy_flutter/test/unit_test/document/turn_into/turn_into_test.dart
  frontend/resources/flowy_icons/16x/ai_explain.svg
  frontend/resources/flowy_icons/20x/ai_explain.svg
  frontend/resources/flowy_icons/20x/toolbar_arrow_down.svg
  frontend/resources/flowy_icons/20x/toolbar_text_color.svg
  frontend/resources/flowy_icons/20x/toolbar_text_highlight.svg
  frontend/resources/translations/en.json
Labels: v0.8.7

#7523 chore: implement ai writer history
  frontend/appflowy_flutter/lib/ai/service/appflowy_ai_service.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/operations/ai_writer_cubit.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/operations/ai_writer_entities.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/markdown_text_robot.dart
  frontend/appflowy_flutter/test/bloc_test/ai_writer_test/ai_writer_bloc_test.dart
  frontend/rust-lib/event-integration-test/src/chat_event.rs
  frontend/rust-lib/flowy-ai-pub/src/cloud.rs
  frontend/rust-lib/flowy-ai/src/completion.rs
  frontend/rust-lib/flowy-ai/src/entities.rs
Labels: v0.8.7

#7568 fix: optimize cover title position offset calculation
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/callout/callout_block_shortcuts.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/document_cover_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/quote/quote_block_shortcuts.dart
Labels: v0.8.7

#7574 fix: continue writing empty text case
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/operations/ai_writer_cubit.dart
Labels: v0.8.7

#7559 feat: allow user scroll during generation
  frontend/appflowy_flutter/lib/plugins/document/document_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/ai_writer_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/operations/ai_writer_block_operations.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/operations/ai_writer_cubit.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/widgets/ai_writer_gesture_detector.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/widgets/ai_writer_scroll_wrapper.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/markdown_text_robot.dart
  frontend/appflowy_flutter/lib/util/throttle.dart
  frontend/appflowy_flutter/test/bloc_test/ai_writer_test/ai_writer_bloc_test.dart
Labels: v0.8.8

#7576 chore: ai writer more actions
  frontend/appflowy_flutter/lib/ai/widgets/prompt_input/desktop_prompt_text_field.dart
  frontend/appflowy_flutter/lib/ai/widgets/prompt_input/select_sources_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/ai_writer_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/operations/ai_writer_node_extension.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/suggestion_action_bar.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/widgets/ai_writer_prompt_input_more_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/widgets/ai_writer_suggestion_actions.dart
  frontend/resources/translations/en.json
Labels: v0.8.8

#7580 fix: using date picker with @ menu get some errors
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_date_block.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/appflowy_date_picker_base.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/desktop_date_picker.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/widgets/date_picker_dialog.dart
Labels: v0.8.8

#7578 feat: revamp toolbar link
  frontend/appflowy_flutter/integration_test/desktop/document/document_toolbar_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/desktop_toolbar/desktop_floating_toolbar.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/desktop_toolbar/link/link_create_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/desktop_toolbar/link/link_edit_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/desktop_toolbar/link/link_hover_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/desktop_toolbar/link/link_search_text_field.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/desktop_toolbar/link/link_styles.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/desktop_toolbar/toolbar_cubit.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/emoji_icon_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_page_block.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toolbar_item/custom_link_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
  frontend/appflowy_flutter/macos/Podfile.lock
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/src/flowy_overlay/appflowy_popover.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/resources/flowy_icons/20x/toolbar_link_earth.svg
  frontend/resources/flowy_icons/20x/toolbar_link_edit.svg
  frontend/resources/flowy_icons/20x/toolbar_link_unlink.svg
  frontend/resources/translations/en.json
Labels: v0.8.8

#7579 chore: update slash menu icons on mobile
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items/image_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items/mobile_items.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items/sub_page_item.dart
  frontend/resources/flowy_icons/20x/slash_menu_image.svg
Labels: v0.8.8

#7599 fix: pass response format in ai writer
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/operations/ai_writer_cubit.dart
Labels: v0.8.8

#7615 fix: ai text insertion
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/operations/ai_writer_block_operations.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/operations/ai_writer_cubit.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/widgets/ai_writer_scroll_wrapper.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/markdown_text_robot.dart
Labels: v0.8.8

#7616 fix(mobile): settings page crashes
  frontend/appflowy_flutter/lib/workspace/application/settings/ai/settings_ai_bloc.dart
Labels: v0.8.8

#7618 chore: adjust ai writer popover content area
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/ai_writer_block_component.dart
Labels: v0.8.8

#7621 chore: bump editor ref
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.8.8

#7598 fix: undo not working for toggle heading
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_option_cubit.dart
Labels: v0.8.8

#7584 Update translations
  frontend/resources/translations/ar-SA.json
  frontend/resources/translations/ru-RU.json
Labels: translation, v0.8.8

#7582 feat: support use ":" keyword to create emojis
  frontend/appflowy_flutter/integration_test/desktop/uncategorized/emoji_shortcut_test.dart
  frontend/appflowy_flutter/integration_test/desktop/uncategorized/uncategorized_test_runner_1.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/shortcuts/character_shortcuts.dart
  frontend/appflowy_flutter/lib/plugins/emoji/emoji_actions_command.dart
  frontend/appflowy_flutter/lib/plugins/emoji/emoji_handler.dart
  frontend/appflowy_flutter/lib/plugins/emoji/emoji_menu.dart
Labels: v0.8.8

#7622 fix: numbered list generated by ai should keep the same index as the input
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/operations/ai_writer_cubit.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/markdown_text_robot.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/numbered_list/numbered_list_icon.dart
Labels: v0.8.8

#7627 chore: bump version 0.8.8
  frontend/Makefile.toml
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.8.8

#7626 chore: adjust popover shadows
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/ai_writer_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/widgets/ai_writer_prompt_input_more_button.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/src/flowy_overlay/appflowy_popover.dart
Labels: v0.8.8

#7630 chore: adjust popover shadows
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/src/flowy_overlay/appflowy_popover.dart
Labels: v0.8.8

#7632 chore: adjust suggestion action button position
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/ai_writer_block_component.dart
Labels: v0.8.8

#7623 fix: add animation for floating toolbar
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/desktop_toolbar/desktop_floating_toolbar.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.8.8

#7631 fix: toolbar launch review issues
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/option/turn_into_option_action.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/ai_writer_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/toolbar_extension.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/desktop_toolbar/desktop_floating_toolbar.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/desktop_toolbar/link/link_create_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/desktop_toolbar/link/link_hover_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toolbar_item/custom_format_toolbar_items.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toolbar_item/custom_link_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toolbar_item/custom_placeholder_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toolbar_item/custom_text_align_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toolbar_item/more_option_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toolbar_item/text_heading_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toolbar_item/text_suggestions_toolbar_item.dart
  frontend/appflowy_flutter/lib/startup/startup.dart
  frontend/appflowy_flutter/lib/workspace/application/settings/appearance/desktop_appearance.dart
  frontend/appflowy_flutter/packages/flowy_infra/lib/theme_extension_v2.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.8.8

#7634 chore: adjust default model name
  frontend/appflowy_flutter/lib/ai/service/ai_model_state_notifier.dart
  frontend/appflowy_flutter/lib/ai/widgets/prompt_input/select_model_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/widgets/ai_writer_prompt_input_more_button.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/setting_ai_view/model_selection.dart
  frontend/resources/translations/en.json
Labels: v0.8.8

#7648 chore: hide formats when using specific ai writer commands
  frontend/appflowy_flutter/lib/ai/widgets/prompt_input/desktop_prompt_text_field.dart
  frontend/appflowy_flutter/lib/ai/widgets/prompt_input/select_model_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/ai_writer_block_component.dart
Labels: v0.8.8

#7635 feat: support i18n in the 'delete my account' operation
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/account/account_deletion.dart
  frontend/resources/translations/ar-SA.json
  frontend/resources/translations/de-DE.json
  frontend/resources/translations/en.json
  frontend/resources/translations/fr-FR.json
  frontend/resources/translations/ko-KR.json
  frontend/resources/translations/tr-TR.json
  frontend/resources/translations/vi-VN.json
  frontend/resources/translations/zh-CN.json
Labels: v0.8.8

#7656 chore: use emoji instead of Local for copy
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/setting_ai_view/model_selection.dart
Labels: v0.8.8

#7655 fix: show cursor at end of selection when generating
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/widgets/ai_writer_scroll_wrapper.dart
Labels: v0.8.8
