Repository AppFlowy-IO/AppFlowy, pull requests merged in 2025-02, with the labels that each got.

#7313 fix: editor stuck on image loading loop when uploading image in row document
  frontend/appflowy_flutter/integration_test/desktop/cloud/cloud_runner.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/database/database_image_test.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/database/database_test_runner.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/resizeable_image.dart
Labels: v0.8.3

#7314 fix: unable to upload file on Android devices
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.8.3

#7204 chore: optional response format
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
  frontend/rust-lib/flowy-ai/src/chat.rs
  frontend/rust-lib/flowy-ai/src/completion.rs
Labels: 0.8.4

#7329 feat(i18n): Add Turkish (tr-TR) language translation
  frontend/resources/translations/tr-TR.json
Labels: 0.8.4

#7281 fix(flutter_desktop): selection going missing while scrolling
  frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/user_text_message.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/text.dart
Labels: 0.8.4

#7328 feat: integrate auto_updater for macOS
  frontend/appflowy_flutter/dsa_pub.pem
  frontend/appflowy_flutter/integration_test/desktop/cloud/data_migration/anon_user_data_migration_test.dart
  frontend/appflowy_flutter/integration_test/desktop/cloud/uncategorized/appflowy_cloud_auth_test.dart
  frontend/appflowy_flutter/ios/Podfile.lock
  frontend/appflowy_flutter/lib/startup/deps_resolver.dart
  frontend/appflowy_flutter/lib/startup/startup.dart
  frontend/appflowy_flutter/lib/startup/tasks/auto_update_task.dart
  frontend/appflowy_flutter/lib/startup/tasks/device_info_task.dart
  frontend/appflowy_flutter/lib/startup/tasks/prelude.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/footer/sidebar_upgarde_application_button.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/space/shared_widget.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/about/app_version.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/account/account_sign_in_out.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_account_view.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/dialogs.dart
  frontend/appflowy_flutter/macos/Podfile.lock
  frontend/appflowy_flutter/macos/Runner/AppDelegate.swift
  frontend/appflowy_flutter/macos/Runner/DebugProfile.entitlements
  frontend/appflowy_flutter/macos/Runner/Info.plist
  frontend/appflowy_flutter/macos/Runner/Release.entitlements
  frontend/appflowy_flutter/packages/appflowy_backend/example/macos/Podfile
  frontend/appflowy_flutter/packages/appflowy_backend/example/macos/Runner.xcodeproj/project.pbxproj
  frontend/appflowy_flutter/packages/appflowy_backend/example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/style_widget/primary_rounded_button.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/appflowy_flutter/windows/runner/Runner.rc
  frontend/resources/flowy_icons/16x/sidebar_upgrade_version.svg
  frontend/resources/translations/en.json
Labels: 0.8.4

#7346 feat: integrate version checker for Linux
  frontend/appflowy_flutter/lib/shared/version_checker/version_checker.dart
  frontend/appflowy_flutter/lib/startup/tasks/auto_update_task.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/sidebar.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/about/app_version.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/resources/translations/en.json
Labels: 0.8.4

#7355 chore: disable impeller on android
  frontend/appflowy_flutter/android/app/src/main/AndroidManifest.xml
Labels: v0.8.4

#7349 fix: gallery not rendering in row page
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/multi_image_block_component/layouts/image_browser_layout.dart
Labels: v0.8.4

#7333 fix: support exporting more content to markdown
  frontend/appflowy_flutter/integration_test/desktop/uncategorized/share_markdown_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/ask_ai_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/util/ask_ai_node_extension.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/multi_image_block_component/multi_image_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/custom_image_node_parser.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/custom_paragraph_node_parser.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/database_node_parser.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/document_markdown_parsers.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/parsers/sub_page_node_parser.dart
  frontend/appflowy_flutter/lib/plugins/shared/share/export_tab.dart
  frontend/appflowy_flutter/lib/plugins/shared/share/share_bloc.dart
  frontend/appflowy_flutter/lib/shared/markdown_to_document.dart
  frontend/appflowy_flutter/lib/workspace/application/export/document_exporter.dart
  frontend/appflowy_flutter/test/unit_test/markdown/markdown_parser_test.dart
Labels: v0.8.4

#7353 feat: lock page
  frontend/appflowy_flutter/lib/plugins/database/board/presentation/board_page.dart
  frontend/appflowy_flutter/lib/plugins/database/calendar/presentation/calendar_page.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/grid_page.dart
  frontend/appflowy_flutter/lib/plugins/database/grid/presentation/widgets/row/row.dart
  frontend/appflowy_flutter/lib/plugins/database/tab_bar/tab_bar_view.dart
  frontend/appflowy_flutter/lib/plugins/document/document_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/workspace/application/view/view_ext.dart
  frontend/appflowy_flutter/lib/workspace/application/view/view_lock_status_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/view/view_service.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_action_type.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_more_action_button.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/account/account_deletion.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/more_view_actions/more_view_actions.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/more_view_actions/widgets/lock_page_action.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/view_title_bar.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/resources/flowy_icons/16x/lock_page.svg
  frontend/resources/flowy_icons/16x/unlock_page.svg
  frontend/resources/translations/en.json
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
  frontend/rust-lib/flowy-error/src/code.rs
  frontend/rust-lib/flowy-error/src/errors.rs
  frontend/rust-lib/flowy-folder/src/entities/view.rs
  frontend/rust-lib/flowy-folder/src/event_handler.rs
  frontend/rust-lib/flowy-folder/src/event_map.rs
  frontend/rust-lib/flowy-folder/src/manager.rs
  frontend/rust-lib/flowy-folder/src/view_operation.rs
Labels: v0.8.4

#7351 chore: update translations
  frontend/resources/translations/ar-SA.json
  frontend/resources/translations/ckb-KU.json
  frontend/resources/translations/fr-FR.json
  frontend/resources/translations/zh-CN.json
Labels: translation, v0.8.4

#7270 feat: support upload svg as icon
  frontend/appflowy_flutter/assets/test/images/sample.svg
  frontend/appflowy_flutter/integration_test/desktop/sidebar/sidebar_icon_test.dart
  frontend/appflowy_flutter/integration_test/mobile/document/icon_test.dart
  frontend/appflowy_flutter/integration_test/shared/common_operations.dart
  frontend/appflowy_flutter/integration_test/shared/emoji.dart
  frontend/appflowy_flutter/integration_test/shared/expectation.dart
  frontend/appflowy_flutter/lib/mobile/presentation/database/view/database_view_quick_actions.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/tab/mobile_space_tab.dart
  frontend/appflowy_flutter/lib/plugins/database/tab_bar/desktop/tab_bar_header.dart
  frontend/appflowy_flutter/lib/plugins/document/document_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/emoji_icon_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/page_style/_page_style_icon_bloc.dart
  frontend/appflowy_flutter/lib/shared/appflowy_network_svg.dart
  frontend/appflowy_flutter/lib/shared/icon_emoji_picker/flowy_icon_emoji_picker.dart
  frontend/appflowy_flutter/lib/shared/icon_emoji_picker/icon_uploader.dart
  frontend/appflowy_flutter/lib/workspace/application/view/view_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/view/view_service.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/rename_view_popover.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/view_title_bar.dart
  frontend/appflowy_flutter/packages/flowy_svg/lib/src/flowy_svg.dart
  frontend/rust-lib/flowy-document/src/entities.rs
  frontend/rust-lib/flowy-document/src/event_handler.rs
  frontend/rust-lib/flowy-document/src/event_map.rs
Labels: v0.8.4

#7370 fix: save image should not copy the image
  frontend/appflowy_flutter/android/app/src/main/AndroidManifest.xml
  frontend/appflowy_flutter/ios/Podfile.lock
  frontend/appflowy_flutter/ios/Runner/Info.plist
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_markdown_text.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_text_message.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/image/custom_image_block_component/custom_image_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_constants.dart
  frontend/appflowy_flutter/lib/shared/permission/permission_checker.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.8.4

#7372 chore: update collab version
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
Labels: v0.8.4

#7373 fix: clear background color of header row & header column
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/simple_table/simple_table_operations/simple_table_header_operation.dart
Labels: v0.8.4

#7376 chore: add ai images label
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_plan_comparison_dialog.dart
  frontend/resources/translations/en.json
Labels: v0.8.4

#7380 fix: lock page issues
  frontend/appflowy_flutter/lib/mobile/presentation/base/mobile_view_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_view_page.dart
  frontend/appflowy_flutter/lib/plugins/document/document_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/database/database_view_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
  frontend/appflowy_flutter/lib/shared/version_checker/version_checker.dart
  frontend/resources/translations/en.json
Labels: v0.8.4

#7385 fix: auto updater issue on Windows
  frontend/appflowy_flutter/lib/shared/version_checker/version_checker.dart
Labels: v0.8.4

#7397 chore: update CHANGELOG.md
  CHANGELOG.md
Labels: v0.8.4

#7392 feat: use flutter_distrubutor to build linux and macos packages
  .github/workflows/release.yml
  frontend/appflowy_flutter/distribute_options.yaml
  frontend/appflowy_flutter/linux/CMakeLists.txt
  frontend/appflowy_flutter/linux/packaging/appimage/make_config.yaml
  frontend/appflowy_flutter/linux/packaging/deb/make_config.yaml
  frontend/appflowy_flutter/linux/packaging/rpm/make_config.yaml
  frontend/appflowy_flutter/macos/packaging/assets/background.jpg
  frontend/appflowy_flutter/macos/packaging/dmg/make_config.json
  frontend/appflowy_flutter/macos/packaging/dmg/make_config.yaml
  frontend/scripts/docker-buildfiles/Dockerfile
  frontend/scripts/flatpack-buildfiles/dbus-interface.xml
  frontend/scripts/flatpack-buildfiles/io.appflowy.AppFlowy.desktop
  frontend/scripts/flatpack-buildfiles/io.appflowy.AppFlowy.metainfo.xml
  frontend/scripts/flatpack-buildfiles/io.appflowy.AppFlowy.service
  frontend/scripts/flatpack-buildfiles/launcher.sh
  frontend/scripts/flutter_release_build/build_linux.sh
  frontend/scripts/flutter_release_build/build_macos.sh
  frontend/scripts/linux_distribution/appimage/AppImageBuilder.yml
  frontend/scripts/linux_distribution/deb/AppFlowy.desktop
  frontend/scripts/linux_distribution/deb/DEBIAN/postinst
  frontend/scripts/linux_distribution/deb/DEBIAN/postrm
  frontend/scripts/linux_distribution/deb/build_deb.sh
  frontend/scripts/linux_distribution/flatpak/README.md
  frontend/scripts/linux_distribution/packaging/io.appflowy.AppFlowy.metainfo.xml
  frontend/scripts/linux_distribution/packaging/io.appflowy.AppFlowy.service
  frontend/scripts/linux_distribution/packaging/launcher.sh
  frontend/scripts/linux_installer/postinst
Labels: v0.8.5

#7414 fix: adjust other user message alignment
  frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/user_message_bubble.dart
Labels: v0.8.5

#7401 fix: add shortcut to create Inline Math Equation
  frontend/appflowy_flutter/integration_test/desktop/document/document_alignment_test.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_inline_math_equation_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/align_toolbar_item/custom_text_align_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/math_equation/math_equation_shortcut.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/shortcuts/command_shortcuts.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_shortcuts_view.dart
  frontend/resources/translations/en.json
Labels: v0.8.5

#7402 feat: support columns block in editor on desktop
  frontend/appflowy_flutter/integration_test/desktop/cloud/document/document_option_actions_test.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_multi_image_block_test.dart
  frontend/appflowy_flutter/lib/mobile/presentation/selection_menu/mobile_selection_menu_item_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/application/document_bloc.dart
  frontend/appflowy_flutter/lib/plugins/document/application/document_rules.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/block_action_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/draggable_option_button.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/util.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/actions/drag_to_reorder/visual_drag_area.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/columns/simple_column_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/columns/simple_column_block_width_resizer.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/columns/simple_column_node_extension.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/columns/simple_columns_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/columns/simple_columns_block_constant.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_copy_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/plugins.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items/columns_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items/slash_menu_items.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items_builder.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
  frontend/appflowy_flutter/lib/startup/tasks/rust_sdk.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/resources/flowy_icons/16x/slash_menu_icon_four_columns.svg
  frontend/resources/flowy_icons/16x/slash_menu_icon_three_columns.svg
  frontend/resources/flowy_icons/16x/slash_menu_icon_two_columns.svg
  frontend/resources/translations/en.json
Labels: v0.8.5

#7361 Update Arabic translations
  frontend/resources/translations/ar-SA.json
Labels: translation, v0.8.5
