Repository AppFlowy-IO/AppFlowy, pull requests merged in 2025-04, with the labels that each got.

#7659 fix: the checklist item will disappear when reordering
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/desktop_row_detail/desktop_row_detail_checklist_cell.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell_editor/checklist_cell_editor.dart
  frontend/appflowy_flutter/lib/plugins/document/application/document_bloc.dart
  frontend/appflowy_flutter/macos/Podfile.lock
Labels: v0.8.8

#7654 fix: some launch review issues for non-search-bar emoji picker
  frontend/appflowy_flutter/lib/plugins/emoji/emoji_handler.dart
  frontend/appflowy_flutter/lib/plugins/emoji/emoji_menu.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/widget/flowy_tooltip.dart
Labels: v0.8.8

#7661 fix: link menu issues
  frontend/appflowy_flutter/integration_test/desktop/document/document_toolbar_test.dart
  frontend/appflowy_flutter/integration_test/shared/document_test_operations.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_page.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/desktop_toolbar/link/link_hover_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/desktop_toolbar/link/link_styles.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toolbar_item/text_suggestions_toolbar_item.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.8.8

#7669 Arabic Translation updates
  frontend/resources/translations/ar-SA.json
Labels: translation, v0.8.8

#7674 fix: after applying different ai model, the selection menu doesn't show the new model
  frontend/appflowy_flutter/lib/flutter/af_dropdown_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/setting_ai_view/model_selection.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/shared/settings_dropdown.dart
  frontend/rust-lib/flowy-ai/src/ai_manager.rs
  frontend/rust-lib/flowy-ai/src/event_handler.rs
  frontend/rust-lib/flowy-ai/src/local_ai/controller.rs
  frontend/rust-lib/flowy-ai/src/local_ai/resource.rs
Labels: v0.8.8

#7672 fix: emoji menu should only be triggered when “:” has a followed letter
  frontend/appflowy_flutter/integration_test/desktop/uncategorized/emoji_shortcut_test.dart
  frontend/appflowy_flutter/lib/plugins/emoji/emoji_actions_command.dart
  frontend/appflowy_flutter/lib/plugins/emoji/emoji_handler.dart
  frontend/appflowy_flutter/lib/plugins/emoji/emoji_menu.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.8.8

#7676 fix: only log document event when enableDocumentInternalLog is enabled
  frontend/appflowy_flutter/lib/plugins/document/application/document_bloc.dart
Labels: v0.8.8

#7695 fix: clear text field upon selection
  frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/select_option_cell_editor_bloc.dart
Labels: v0.8.9

#7694 fix: translations
  frontend/appflowy_flutter/lib/mobile/presentation/base/view_page/more_bottom_sheet.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_message_action_bar.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_message_bubble.dart
  frontend/appflowy_flutter/lib/plugins/database/widgets/cell/editable_cell_skeleton/url.dart
  frontend/appflowy_flutter/lib/plugins/shared/share/export_tab.dart
  frontend/appflowy_flutter/lib/plugins/shared/share/publish_tab.dart
  frontend/appflowy_flutter/lib/plugins/shared/share/share_tab.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/sites/constants.dart
  frontend/resources/translations/ar-SA.json
  frontend/resources/translations/de-DE.json
  frontend/resources/translations/el-GR.json
  frontend/resources/translations/en.json
  frontend/resources/translations/es-VE.json
  frontend/resources/translations/fr-FR.json
  frontend/resources/translations/he.json
  frontend/resources/translations/ja-JP.json
  frontend/resources/translations/ko-KR.json
  frontend/resources/translations/ru-RU.json
  frontend/resources/translations/th-TH.json
  frontend/resources/translations/tr-TR.json
  frontend/resources/translations/uk-UA.json
  frontend/resources/translations/vi-VN.json
  frontend/resources/translations/zh-CN.json
  frontend/resources/translations/zh-TW.json
Labels: v0.8.9

#7706 feat: customize app name, app icon and font on Windows
  frontend/appflowy_flutter/lib/shared/error_page/error_page.dart
  frontend/appflowy_flutter/lib/workspace/application/notification/notification_service.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_shortcuts_view.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/setting_appflowy_cloud.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/theme_upload/theme_upload_learn_more_button.dart
  frontend/scripts/white_label/i18n_white_label.sh
  frontend/scripts/white_label/icon_white_label.sh
  frontend/scripts/white_label/resources/my_company_logo.ico
  frontend/scripts/white_label/resources/my_company_logo.png
  frontend/scripts/white_label/resources/my_company_logo.svg
  frontend/scripts/white_label/white_label.sh
  frontend/scripts/white_label/windows_white_label.sh
Labels: v0.8.9

#7667 feat(i18n): Add initial Marathi (mr-IN) translations
  frontend/appflowy_flutter/assets/translations/mr-IN.json
  frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart
  frontend/appflowy_flutter/packages/flowy_infra/lib/language.dart
  frontend/resources/translations/mr-IN.json
Labels: translation, v0.8.9

#7673 fix: icon and emoji don't align in the mention page menu.
  frontend/appflowy_flutter/lib/mobile/presentation/inline_actions/mobile_inline_actions_menu_group.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/header/emoji_icon_widget.dart
  frontend/appflowy_flutter/lib/plugins/inline_actions/handlers/child_page.dart
  frontend/appflowy_flutter/lib/plugins/inline_actions/handlers/inline_page_reference.dart
  frontend/appflowy_flutter/lib/plugins/inline_actions/inline_actions_result.dart
  frontend/appflowy_flutter/lib/plugins/inline_actions/widgets/inline_actions_menu_group.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/view/view_item.dart
Labels: v0.8.9

#7712 fix: use normal underline for AI suggested text style
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
Labels: v0.8.9

#7716 chore: bump version
  frontend/Makefile.toml
  frontend/appflowy_flutter/pubspec.yaml
Labels: v0.8.9

#7675 chore: update translation
  frontend/resources/translations/zh-CN.json
Labels: translation, v0.8.9

#7685 feat: sign in with passcode
  frontend/appflowy_flutter/integration_test/desktop/cloud/data_migration/anon_user_data_migration_test.dart
  frontend/appflowy_flutter/lib/mobile/presentation/setting/about/about_setting_group.dart
  frontend/appflowy_flutter/lib/mobile/presentation/setting/workspace/invite_members_screen.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/file/file_util.dart
  frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart
  frontend/appflowy_flutter/lib/startup/tasks/appflowy_cloud_task.dart
  frontend/appflowy_flutter/lib/user/application/auth/af_cloud_auth_service.dart
  frontend/appflowy_flutter/lib/user/application/auth/af_cloud_mock_auth_service.dart
  frontend/appflowy_flutter/lib/user/application/auth/auth_service.dart
  frontend/appflowy_flutter/lib/user/application/auth/backend_auth_service.dart
  frontend/appflowy_flutter/lib/user/application/sign_in_bloc.dart
  frontend/appflowy_flutter/lib/user/application/user_service.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/desktop_sign_in_screen.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/mobile_sign_in_screen.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/anonymous_sign_in_button.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/anonymous_sign_in_button/anonymous_sign_in_button.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/continue_with/continue_with_email.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/continue_with/continue_with_email_and_password.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/continue_with/continue_with_magic_link_or_passcode_page.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/continue_with/continue_with_password.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/continue_with/continue_with_password_page.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/logo/logo.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/magic_link_sign_in_buttons.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/sign_in_agreement.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/sign_in_anonymous_button.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/sign_in_or_logout_button.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/third_party_sign_in_button/third_party_sign_in_button.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/third_party_sign_in_button/third_party_sign_in_buttons.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/widgets.dart
  frontend/appflowy_flutter/lib/user/presentation/widgets/auth_form_container.dart
  frontend/appflowy_flutter/lib/user/presentation/widgets/flowy_logo_title.dart
  frontend/appflowy_flutter/lib/workspace/application/sidebar/billing/sidebar_plan_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/account/account_sign_in_out.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/dialogs.dart
  frontend/appflowy_flutter/packages/appflowy_ui/README.md
  frontend/appflowy_flutter/packages/appflowy_ui/lib/appflowy_ui.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/data/builder.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/resources/translations/en.json
  frontend/rust-lib/.vscode/launch.json
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
  frontend/rust-lib/flowy-server/src/af_cloud/impls/user/cloud_service_impl.rs
  frontend/rust-lib/flowy-server/src/local_server/impls/user.rs
  frontend/rust-lib/flowy-server/src/supabase/api/user.rs
  frontend/rust-lib/flowy-user-pub/src/cloud.rs
  frontend/rust-lib/flowy-user/src/entities/auth.rs
  frontend/rust-lib/flowy-user/src/event_handler.rs
  frontend/rust-lib/flowy-user/src/event_map.rs
  frontend/rust-lib/flowy-user/src/user_manager/manager.rs
Labels: v0.8.9

#7692 feat: revamp link preivew
  frontend/appflowy_flutter/integration_test/desktop/document/document_copy_and_paste_test.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_link_preview_test.dart
  frontend/appflowy_flutter/integration_test/desktop/document/document_test_runner_4.dart
  frontend/appflowy_flutter/integration_test/desktop/uncategorized/emoji_shortcut_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/custom_paste_command.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/paste_from_html.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/copy_and_paste/paste_from_plain_text.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/desktop_toolbar/link/link_create_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/desktop_toolbar/link/link_hover_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/desktop_toolbar/link/link_replace_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/link_embed/link_embed_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/link_embed/link_embed_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/link_preview/custom_link_parser.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/link_preview/custom_link_preview.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/link_preview/custom_link_preview_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/link_preview/link_preview_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/link_preview/paste_as/paste_as_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/link_preview/shared.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_block.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_link_block.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_link_error_preview.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_link_preview.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/menu/menu_extension.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toolbar_item/custom_hightlight_color_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
  frontend/appflowy_flutter/lib/plugins/emoji/emoji_handler.dart
  frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart
  frontend/appflowy_flutter/lib/util/default_extensions.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/data/builder.dart
  frontend/appflowy_flutter/packages/flowy_infra/lib/theme_extension_v2.dart
  frontend/appflowy_flutter/packages/flowy_infra_ui/lib/widget/flowy_tooltip.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/resources/flowy_icons/20x/embed_fullscreen.svg
  frontend/resources/flowy_icons/20x/turninto.svg
  frontend/resources/flowy_icons/40x/embed_error.svg
  frontend/resources/translations/en.json
Labels: v0.8.9

#7719 chore: adjust replace, insert below, discard selection behavior
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/operations/ai_writer_cubit.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/widgets/ai_writer_scroll_wrapper.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/markdown_text_robot.dart
Labels: v0.8.9

#7723 fix: adjust ghost button hover color
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/data/builder.dart
Labels: v0.8.9

#7725 fix: unable to accept the response from 'mark longer'
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/base/markdown_text_robot.dart
  frontend/appflowy_flutter/test/unit_test/document/text_robot/markdown_text_robot_test.dart
Labels: v0.8.9

#7730 fix: otp launch review issues
  frontend/appflowy_flutter/integration_test/shared/common_operations.dart
  frontend/appflowy_flutter/lib/user/application/sign_in_bloc.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/desktop_sign_in_screen.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/sign_in_screen.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/continue_with/continue_with_email_and_password.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/continue_with/continue_with_magic_link_or_passcode_page.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/continue_with/continue_with_password_page.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/sign_in_agreement.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/third_party_sign_in_button/third_party_sign_in_buttons.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/component/textfield/textfield.dart
  frontend/resources/translations/en.json
Labels: v0.8.9

#7735 fix: open board row as page
  frontend/appflowy_flutter/lib/plugins/database/board/presentation/board_page.dart
Labels: v0.8.9

#7751 refactor: use script to generate design tokens
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/ai_writer_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/link_embed/link_embed_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/link_preview/custom_link_preview.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toolbar_item/custom_format_toolbar_items.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toolbar_item/custom_hightlight_color_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toolbar_item/custom_link_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toolbar_item/custom_text_align_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toolbar_item/custom_text_color_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toolbar_item/text_heading_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/toolbar_item/text_suggestions_toolbar_item.dart
  frontend/appflowy_flutter/packages/appflowy_ui/example/lib/main.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/component/textfield/textfield.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/appflowy_theme.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/color_scheme/base/base_scheme.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/color_scheme/base/blue.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/color_scheme/base/green.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/color_scheme/base/magenta.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/color_scheme/base/neutral.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/color_scheme/base/orange.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/color_scheme/base/purple.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/color_scheme/base/red.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/color_scheme/base/subtle.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/color_scheme/base/yellow.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/color_scheme/border/border_color_scheme.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/color_scheme/color_scheme.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/data/appflowy_default/primitive.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/data/appflowy_default/semantic.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/data/builder.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/data/built_in_themes.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/data/data.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/definition/base_theme.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/definition/border_radius/border_radius.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/definition/color_scheme/background_color_scheme.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/definition/color_scheme/border_color_scheme.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/definition/color_scheme/brand_color_scheme.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/definition/color_scheme/color_scheme.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/definition/color_scheme/fill_color_scheme.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/definition/color_scheme/icon_color_scheme.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/definition/color_scheme/other_color_scheme.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/definition/color_scheme/surface_color_scheme.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/definition/color_scheme/text_color_scheme.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/definition/shadow/shadow.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/definition/spacing/spacing.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/definition/text_style/base/default_text_style.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/definition/text_style/text_style.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/dimensions.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/theme.dart
  frontend/appflowy_flutter/packages/appflowy_ui/script/Primitive.Mode 1.tokens.json
  frontend/appflowy_flutter/packages/appflowy_ui/script/Semantic.Dark Mode.tokens.json
  frontend/appflowy_flutter/packages/appflowy_ui/script/Semantic.Light Mode.tokens.json
  frontend/appflowy_flutter/packages/appflowy_ui/script/generate_theme.dart
Labels: v0.9.0

#7752 feat: change password in settings page
  frontend/appflowy_flutter/integration_test/shared/settings.dart
  frontend/appflowy_flutter/lib/mobile/presentation/setting/personal_info/personal_info_setting_group.dart
  frontend/appflowy_flutter/lib/user/application/password/password_bloc.dart
  frontend/appflowy_flutter/lib/user/application/password/password_http_service.dart
  frontend/appflowy_flutter/lib/user/application/sign_in_bloc.dart
  frontend/appflowy_flutter/lib/user/application/user_service.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/continue_with/continue_with_email_and_password.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/continue_with/continue_with_magic_link_or_passcode_page.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/continue_with/continue_with_password_page.dart
  frontend/appflowy_flutter/lib/user/presentation/widgets/flowy_logo_title.dart
  frontend/appflowy_flutter/lib/workspace/application/user/settings_user_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/footer/sidebar_toast.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/shared/sidebar_setting.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/about/app_version.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/account/account_deletion.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/account/account_sign_in_out.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/account/account_user_profile.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/account/email/email_section.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/account/password/change_password.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/account/password/password_suffix_icon.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/account/password/setup_password.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/pages/settings_account_view.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/shared/settings_category.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/shared/settings_category_spacer.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/shared/settings_header.dart
  frontend/appflowy_flutter/macos/Podfile.lock
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/component/button/base_button/base.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/component/button/base_button/base_text_button.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/component/button/filled_button/filled_text_button.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/component/button/outlined_button/outlined_text_button.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/component/textfield/textfield.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/text_style/base/default_text_style.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/text_style/text_style.dart
  frontend/resources/flowy_icons/20x/hide_password.svg
  frontend/resources/flowy_icons/20x/password_close.svg
  frontend/resources/flowy_icons/20x/show_password.svg
  frontend/resources/translations/en.json
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/event-integration-test/tests/user/local_test/auth_test.rs
  frontend/rust-lib/flowy-server/src/local_server/impls/chat.rs
  frontend/rust-lib/flowy-user/src/entities/auth.rs
  frontend/rust-lib/flowy-user/src/entities/user_profile.rs
Labels: v0.9.0

#7787 fix: crash when trying to delete emoji
  frontend/appflowy_flutter/integration_test/desktop/uncategorized/emoji_shortcut_test.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/slash_menu/slash_menu_items/emoji_item.dart
  frontend/appflowy_flutter/lib/plugins/emoji/emoji_actions_command.dart
  frontend/appflowy_flutter/lib/plugins/emoji/emoji_handler.dart
  frontend/appflowy_flutter/lib/plugins/emoji/emoji_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/emoji_picker/emoji_menu_item.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/emoji_picker/emoji_picker.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/emoji_picker/emoji_shortcut_event.dart
Labels: v0.9.0

#7773 fix: some mention text can not display correctly
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/link_preview/custom_link_preview.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/link_preview/link_parsers/default_parser.dart
Labels: v0.9.0

#7801 fix: custom font doesn't apply to settings page
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
  frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart
  frontend/appflowy_flutter/lib/user/application/password/password_http_service.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/members/inivitation/member_http_service.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/members/workspace_member_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_menu.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/data/appflowy_default/semantic.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/data/custom/custom_theme.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/definition/text_style/base/default_text_style.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/definition/text_style/text_style.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/definition/theme_data.dart
  frontend/resources/flowy_icons/20x/settings_page_ai.svg
  frontend/resources/flowy_icons/20x/settings_page_bell.svg
  frontend/resources/flowy_icons/20x/settings_page_cloud.svg
  frontend/resources/flowy_icons/20x/settings_page_credit_card.svg
  frontend/resources/flowy_icons/20x/settings_page_database.svg
  frontend/resources/flowy_icons/20x/settings_page_earth.svg
  frontend/resources/flowy_icons/20x/settings_page_keyboard.svg
  frontend/resources/flowy_icons/20x/settings_page_plan.svg
  frontend/resources/flowy_icons/20x/settings_page_user.svg
  frontend/resources/flowy_icons/20x/settings_page_users.svg
  frontend/resources/flowy_icons/20x/settings_page_workspace.svg
Labels: v0.9.0

#7807 fix: windows scaling issue
  frontend/appflowy_flutter/lib/startup/startup.dart
  frontend/appflowy_flutter/lib/startup/tasks/app_widget.dart
  frontend/appflowy_flutter/lib/startup/tasks/appflowy_cloud_task.dart
  frontend/appflowy_flutter/lib/startup/tasks/auto_update_task.dart
  frontend/appflowy_flutter/lib/startup/tasks/debug_task.dart
  frontend/appflowy_flutter/lib/startup/tasks/device_info_task.dart
  frontend/appflowy_flutter/lib/startup/tasks/feature_flag_task.dart
  frontend/appflowy_flutter/lib/startup/tasks/file_storage_task.dart
  frontend/appflowy_flutter/lib/startup/tasks/hot_key.dart
  frontend/appflowy_flutter/lib/startup/tasks/load_plugin.dart
  frontend/appflowy_flutter/lib/startup/tasks/localization.dart
  frontend/appflowy_flutter/lib/startup/tasks/memory_leak_detector.dart
  frontend/appflowy_flutter/lib/startup/tasks/platform_error_catcher.dart
  frontend/appflowy_flutter/lib/startup/tasks/platform_service.dart
  frontend/appflowy_flutter/lib/startup/tasks/recent_service_task.dart
  frontend/appflowy_flutter/lib/startup/tasks/rust_sdk.dart
  frontend/appflowy_flutter/lib/startup/tasks/sentry.dart
  frontend/appflowy_flutter/lib/startup/tasks/windows.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/desktop_sign_in_screen.dart
  frontend/appflowy_flutter/lib/workspace/application/command_palette/command_palette_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/recent/cached_recent_service.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/home_stack.dart
  frontend/appflowy_flutter/packages/appflowy_backend/lib/dispatch/dispatch.dart
  frontend/appflowy_flutter/pubspec.lock
  frontend/appflowy_flutter/pubspec.yaml
  frontend/appflowy_flutter/windows/runner/flutter_window.cpp
Labels: v0.9.0

#7804 feat: support mobile search
  frontend/appflowy_flutter/integration_test/mobile/search/search_test.dart
  frontend/appflowy_flutter/ios/Podfile.lock
  frontend/appflowy_flutter/lib/mobile/presentation/home/mobile_home_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/tab/ai_bubble_button.dart
  frontend/appflowy_flutter/lib/mobile/presentation/home/tab/mobile_space_tab.dart
  frontend/appflowy_flutter/lib/mobile/presentation/mobile_bottom_navigation_bar.dart
  frontend/appflowy_flutter/lib/mobile/presentation/search/mobile_search_ask_ai_entrance.dart
  frontend/appflowy_flutter/lib/mobile/presentation/search/mobile_search_cell.dart
  frontend/appflowy_flutter/lib/mobile/presentation/search/mobile_search_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/search/mobile_search_result.dart
  frontend/appflowy_flutter/lib/mobile/presentation/search/mobile_search_textfield.dart
  frontend/appflowy_flutter/lib/mobile/presentation/search/mobile_view_ancestors.dart
  frontend/appflowy_flutter/lib/mobile/presentation/search/view_ancestor_cache.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/mobile_chat_input.dart
  frontend/appflowy_flutter/lib/startup/deps_resolver.dart
  frontend/appflowy_flutter/lib/startup/tasks/generate_router.dart
  frontend/appflowy_flutter/lib/workspace/application/command_palette/command_palette_bloc.dart
  frontend/appflowy_flutter/lib/workspace/application/command_palette/search_result_ext.dart
  frontend/appflowy_flutter/test/unit_test/search/split_search_test.dart
  frontend/resources/flowy_icons/24x/m_home_ai_chat_icon.svg
  frontend/resources/flowy_icons/24x/m_home_search_icon.svg
  frontend/resources/flowy_icons/24x/m_home_search_icon_active.svg
  frontend/resources/translations/en.json
Labels: v0.9.0

#7772 feat: support new design for mobile link
  frontend/appflowy_flutter/integration_test/mobile/document/toolbar_test.dart
  frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_edit_link_widget.dart
  frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_header.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/desktop_toolbar/link/link_create_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/desktop_toolbar/link/link_edit_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/desktop_toolbar/link/link_extension.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/desktop_toolbar/link/link_hover_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/desktop_toolbar/link/link_replace_menu.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/desktop_toolbar/link/link_search_text_field.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/desktop_toolbar/link/link_styles.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_item/utils.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/aa_menu/_block_items.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/basic_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/link_toolbar_item.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/toolbar_item_builder.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_style.dart
  frontend/resources/flowy_icons/20x/mobile_icon_remove_link.svg
Labels: v0.9.0

#7809 feat: display joined at and user avatar in members page
  frontend/Makefile.toml
  frontend/appflowy_flutter/lib/workspace/presentation/settings/settings_dialog.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/members/inivitation/inivite_member_by_link.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/members/workspace_member_page.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/settings/widgets/settings_menu_element.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/user_avatar.dart
  frontend/appflowy_flutter/pubspec.yaml
  frontend/resources/translations/en.json
  frontend/rust-lib/Cargo.lock
  frontend/rust-lib/Cargo.toml
  frontend/rust-lib/flowy-server/src/af_cloud/impls/user/dto.rs
  frontend/rust-lib/flowy-server/src/local_server/impls/user.rs
  frontend/rust-lib/flowy-sqlite/migrations/2025-04-22-150142_workspace_member_joined_at/down.sql
  frontend/rust-lib/flowy-sqlite/migrations/2025-04-22-150142_workspace_member_joined_at/up.sql
  frontend/rust-lib/flowy-sqlite/src/schema.rs
  frontend/rust-lib/flowy-user-pub/src/entities.rs
  frontend/rust-lib/flowy-user-pub/src/sql/member_sql.rs
  frontend/rust-lib/flowy-user-pub/src/sql/user_sql.rs
  frontend/rust-lib/flowy-user/src/entities/workspace.rs
  frontend/rust-lib/flowy-user/src/user_manager/manager_user_workspace.rs
Labels: v0.9.0

#7805 feat: built-in custom prompts
  frontend/appflowy_flutter/assets/built_in_prompts.json
  frontend/appflowy_flutter/lib/ai/ai.dart
  frontend/appflowy_flutter/lib/ai/service/ai_entities.dart
  frontend/appflowy_flutter/lib/ai/service/ai_prompt_selector_cubit.dart
  frontend/appflowy_flutter/lib/ai/service/appflowy_ai_service.dart
  frontend/appflowy_flutter/lib/ai/widgets/ai_prompt_modal/ai_prompt_category_list.dart
  frontend/appflowy_flutter/lib/ai/widgets/ai_prompt_modal/ai_prompt_modal.dart
  frontend/appflowy_flutter/lib/ai/widgets/ai_prompt_modal/ai_prompt_preview.dart
  frontend/appflowy_flutter/lib/ai/widgets/ai_prompt_modal/ai_prompt_visible_list.dart
  frontend/appflowy_flutter/lib/ai/widgets/prompt_input/browse_prompts_button.dart
  frontend/appflowy_flutter/lib/ai/widgets/prompt_input/desktop_prompt_input.dart
  frontend/appflowy_flutter/lib/ai/widgets/prompt_input/mentioned_page_text_span.dart
  frontend/appflowy_flutter/lib/ai/widgets/prompt_input/prompt_input_text_controller.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/chat_input/mobile_chat_input.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/ai/ai_writer_block_component.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/dialog_v2.dart
  frontend/appflowy_flutter/packages/appflowy_ui/example/lib/src/modal/modal_page.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/component/textfield/textfield.dart
  frontend/appflowy_flutter/pubspec.yaml
  frontend/resources/translations/en.json
Labels: v0.9.0

#7817 chore: hide appflowy avatar in ai chat
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/ai_message_bubble.dart
Labels: v0.9.0

#7802 refactor: deeplink handler
  frontend/appflowy_flutter/lib/startup/tasks/appflowy_cloud_task.dart
  frontend/appflowy_flutter/lib/startup/tasks/deeplink/deeplink_handler.dart
  frontend/appflowy_flutter/lib/startup/tasks/deeplink/expire_login_deeplink_handler.dart
  frontend/appflowy_flutter/lib/startup/tasks/deeplink/invitation_deeplink_handler.dart
  frontend/appflowy_flutter/lib/startup/tasks/deeplink/login_deeplink_handler.dart
  frontend/appflowy_flutter/lib/startup/tasks/deeplink/payment_deeplink_handler.dart
  frontend/appflowy_flutter/lib/user/application/sign_in_bloc.dart
  frontend/appflowy_flutter/lib/user/presentation/screens/sign_in_screen/widgets/continue_with/continue_with_password_page.dart
  frontend/appflowy_flutter/lib/workspace/application/user/user_workspace_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/_sidebar_workspace_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/sidebar_workspace.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/workspace_notifier.dart
  frontend/appflowy_flutter/macos/Podfile.lock
  frontend/appflowy_flutter/test/unit_test/deeplink/deeplink_test.dart
Labels: v0.9.0

#7829 fix: custom prompt launch review issues
  frontend/appflowy_flutter/assets/built_in_prompts.json
  frontend/appflowy_flutter/lib/ai/widgets/ai_prompt_modal/ai_prompt_category_list.dart
  frontend/appflowy_flutter/lib/ai/widgets/ai_prompt_modal/ai_prompt_visible_list.dart
  frontend/appflowy_flutter/lib/ai/widgets/prompt_input/desktop_prompt_input.dart
  frontend/appflowy_flutter/lib/ai/widgets/prompt_input/prompt_input_text_controller.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
Labels: v0.9.0

#7833 chore: new design for custom prompt
  frontend/appflowy_flutter/lib/ai/widgets/ai_prompt_modal/ai_prompt_category_list.dart
  frontend/appflowy_flutter/lib/ai/widgets/ai_prompt_modal/ai_prompt_modal.dart
  frontend/appflowy_flutter/lib/ai/widgets/ai_prompt_modal/ai_prompt_preview.dart
  frontend/appflowy_flutter/lib/ai/widgets/ai_prompt_modal/ai_prompt_visible_list.dart
  frontend/appflowy_flutter/lib/ai/widgets/prompt_input/prompt_input_text_controller.dart
  frontend/resources/translations/en.json
Labels: v0.9.0

#7837 fix: mobile link LR issues
  frontend/appflowy_flutter/lib/core/helpers/url_launcher.dart
  frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_edit_link_widget.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/desktop_toolbar/link/link_search_text_field.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mobile_toolbar_v3/basic_toolbar_item.dart
  frontend/resources/flowy_icons/24x/m_toolbar_link.svg
Labels: v0.9.0

#7836 fix: some mobile search LR issues
  frontend/appflowy_flutter/integration_test/mobile/search/search_test.dart
  frontend/appflowy_flutter/lib/mobile/application/notification/notification_reminder_bloc.dart
  frontend/appflowy_flutter/lib/mobile/presentation/bottom_sheet/bottom_sheet_edit_link_widget.dart
  frontend/appflowy_flutter/lib/mobile/presentation/search/mobile_search_cell.dart
  frontend/appflowy_flutter/lib/mobile/presentation/search/mobile_search_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/search/mobile_search_result.dart
  frontend/appflowy_flutter/lib/mobile/presentation/search/mobile_search_textfield.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/desktop_toolbar/link/link_styles.dart
  frontend/appflowy_flutter/lib/workspace/application/command_palette/search_result_ext.dart
  frontend/resources/translations/en.json
Labels: v0.9.0

#7825 fix: some notification center launch review issues
  frontend/appflowy_flutter/integration_test/desktop/document/document_with_date_reminder_test.dart
  frontend/appflowy_flutter/integration_test/mobile/document/toolbar_test.dart
  frontend/appflowy_flutter/lib/mobile/application/notification/notification_reminder_bloc.dart
  frontend/appflowy_flutter/lib/mobile/presentation/mobile_bottom_navigation_bar.dart
  frontend/appflowy_flutter/lib/mobile/presentation/notifications/mobile_notifications_page.dart
  frontend/appflowy_flutter/lib/mobile/presentation/notifications/widgets/multi_select_notification_item.dart
  frontend/appflowy_flutter/lib/mobile/presentation/notifications/widgets/notification_item.dart
  frontend/appflowy_flutter/lib/mobile/presentation/notifications/widgets/shared.dart
  frontend/appflowy_flutter/lib/mobile/presentation/notifications/widgets/slide_actions.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_configuration.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/link_embed/link_embed_block_component.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_date_block.dart
  frontend/appflowy_flutter/lib/shared/red_dot.dart
  frontend/appflowy_flutter/lib/user/application/reminder/reminder_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/desktop_home_screen.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/header/sidebar_top_menu.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/header/sidebar_user.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/shared/sidebar_setting.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/menu/sidebar/workspace/sidebar_workspace.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/navigation.dart
  frontend/appflowy_flutter/lib/workspace/presentation/notifications/notification_panel.dart
  frontend/appflowy_flutter/lib/workspace/presentation/notifications/number_red_dot.dart
  frontend/appflowy_flutter/lib/workspace/presentation/notifications/widgets/inbox_action_bar.dart
  frontend/appflowy_flutter/lib/workspace/presentation/notifications/widgets/notification_button.dart
  frontend/appflowy_flutter/lib/workspace/presentation/notifications/widgets/notification_content_v2.dart
  frontend/appflowy_flutter/lib/workspace/presentation/notifications/widgets/notification_item_v2.dart
  frontend/appflowy_flutter/lib/workspace/presentation/notifications/widgets/notification_tab.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/appflowy_ui.dart
  frontend/appflowy_flutter/packages/appflowy_ui/lib/src/theme/data/appflowy_default/semantic.dart
  frontend/appflowy_flutter/test/bloc_test/grid_test/cell/date_cell_bloc_test.dart
  frontend/resources/flowy_icons/16x/notification_icon_at.svg
  frontend/resources/translations/en.json
Labels: v0.9.0

#7860 fix: user chat message bubble should have flex
  frontend/appflowy_flutter/lib/plugins/ai_chat/chat_page.dart
  frontend/appflowy_flutter/lib/plugins/ai_chat/presentation/message/user_message_bubble.dart
Labels: v0.9.0

#7859 chore: import new prompts and add featured category
  frontend/appflowy_flutter/assets/built_in_prompts.json
  frontend/appflowy_flutter/lib/ai/service/ai_entities.dart
  frontend/appflowy_flutter/lib/ai/service/ai_prompt_selector_cubit.dart
  frontend/appflowy_flutter/lib/ai/service/appflowy_ai_service.dart
  frontend/appflowy_flutter/lib/ai/widgets/ai_prompt_modal/ai_prompt_category_list.dart
  frontend/resources/translations/en.json
Labels: v0.9.0

#7861 fix: revert some date picker code and fix notification issue
  frontend/appflowy_flutter/lib/plugins/database/application/cell/bloc/date_cell_editor_bloc.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/desktop_toolbar/link/link_search_text_field.dart
  frontend/appflowy_flutter/lib/plugins/document/presentation/editor_plugins/mention/mention_date_block.dart
  frontend/appflowy_flutter/lib/user/application/reminder/reminder_bloc.dart
  frontend/appflowy_flutter/lib/workspace/presentation/home/home_stack.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/appflowy_date_picker_base.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/desktop_date_picker.dart
  frontend/appflowy_flutter/lib/workspace/presentation/widgets/date_picker/widgets/date_picker_dialog.dart
Labels: v0.9.0
